-- Cohort-wide smoke test for the selected-member allergy experience.
-- Run after the core views as PATIENT_360_ANALYST.

USE ROLE PATIENT_360_ANALYST;
USE DATABASE PATIENT_360;
USE SCHEMA CORE;
USE WAREHOUSE PATIENT_360_WH;

WITH allergy_counts AS (
    SELECT
        p.PATIENT_ID,
        COUNT(a.CODE) AS ALLERGY_ROWS
    FROM PATIENT AS p
    LEFT JOIN ALLERGY AS a ON a.PATIENT_ID = p.PATIENT_ID
    GROUP BY p.PATIENT_ID
)
SELECT
    COUNT(*) AS PATIENTS,
    COUNT_IF(ALLERGY_ROWS = 0) AS ZERO_ALLERGY_ROWS,
    COUNT_IF(ALLERGY_ROWS = 1) AS ONE_ALLERGY_ROW,
    COUNT_IF(ALLERGY_ROWS > 1) AS MULTIPLE_ALLERGY_ROWS,
    MAX(ALLERGY_ROWS) AS MAX_ALLERGY_ROWS
FROM allergy_counts;

SELECT COUNT(*) AS ALLERGY_ROWS_WITH_MISSING_CITATION_KEY
FROM ALLERGY
WHERE PATIENT_ID IS NULL
   OR ENCOUNTER_ID IS NULL
   OR CODE IS NULL
   OR START_DATE IS NULL;

SELECT COUNT(*) AS ALLERGY_DOCUMENT_ROWS_WITH_REJECTED_CODES
FROM DOCUMENT_SECTION
WHERE SECTION_LOINC = '48765-2'
  AND REJECTED_CODES IS NOT NULL;

WITH allergy_counts AS (
    SELECT
        p.PATIENT_ID,
        p.FIRST_NAME,
        p.LAST_NAME,
        COUNT(a.CODE) AS ALLERGY_ROWS
    FROM PATIENT AS p
    LEFT JOIN ALLERGY AS a ON a.PATIENT_ID = p.PATIENT_ID
    GROUP BY p.PATIENT_ID, p.FIRST_NAME, p.LAST_NAME
),
ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY
                CASE
                    WHEN ALLERGY_ROWS = 0 THEN 'ZERO'
                    WHEN ALLERGY_ROWS = 1 THEN 'ONE'
                    ELSE 'MULTIPLE'
                END
            ORDER BY PATIENT_ID
        ) AS SAMPLE_NUMBER
    FROM allergy_counts
)
SELECT PATIENT_ID, FIRST_NAME, LAST_NAME, ALLERGY_ROWS
FROM ranked
WHERE SAMPLE_NUMBER = 1
ORDER BY ALLERGY_ROWS;
