-- Live smoke checks for the expanded clinical-document answer surface.
-- Every statement runs as the analyst role and returns the fields used by the app.

USE ROLE PATIENT_360_ANALYST;
USE DATABASE PATIENT_360;
USE SCHEMA CORE;
USE WAREHOUSE PATIENT_360_WH;

SET DEMO_PATIENT_ID = '37549f60-b5a3-69cd-dea6-5a71c4bc23cf';

SELECT PATIENT_ID, FIRST_NAME, LAST_NAME, GENDER, BIRTHDATE, DEATHDATE, CITY, STATE
FROM PATIENT WHERE PATIENT_ID = $DEMO_PATIENT_ID;

SELECT PATIENT_ID, ENCOUNTER_ID, START_TS AS "START", ENCOUNTER_CLASS, CODE, DESCRIPTION
FROM ENCOUNTER WHERE PATIENT_ID = $DEMO_PATIENT_ID ORDER BY START_TS DESC LIMIT 5;

SELECT PATIENT_ID, ENCOUNTER_ID, START_DATE AS "START", CODE, DESCRIPTION
FROM CONDITION WHERE PATIENT_ID = $DEMO_PATIENT_ID ORDER BY START_DATE DESC LIMIT 10;

SELECT PATIENT_ID, ENCOUNTER_ID, START_TS AS "START", CODE, DESCRIPTION, DISPENSES
FROM MEDICATION WHERE PATIENT_ID = $DEMO_PATIENT_ID ORDER BY START_TS DESC LIMIT 10;

SELECT PATIENT_ID, ENCOUNTER_ID, START_DATE AS "START", CAREPLAN_ID, CODE, DESCRIPTION
FROM CAREPLAN WHERE PATIENT_ID = $DEMO_PATIENT_ID ORDER BY START_DATE DESC LIMIT 10;

SELECT PATIENT_ID, ENCOUNTER_ID, SOURCE_FILE_ROW_NUMBER AS ROW_ID,
       OBSERVATION_TS AS OBSERVED_AT, CODE, DESCRIPTION, VALUE_TEXT AS "VALUE", UNITS
FROM OBSERVATION
WHERE PATIENT_ID = $DEMO_PATIENT_ID AND LOWER(CATEGORY) = 'laboratory'
ORDER BY OBSERVATION_TS DESC LIMIT 10;

SELECT PATIENT_ID, ENCOUNTER_ID, START_TS AS "START", CODE, DESCRIPTION
FROM PROCEDURE WHERE PATIENT_ID = $DEMO_PATIENT_ID ORDER BY START_TS DESC LIMIT 10;

SELECT PATIENT_ID, ENCOUNTER_ID, IMMUNIZATION_TS AS "START", CODE, DESCRIPTION
FROM IMMUNIZATION WHERE PATIENT_ID = $DEMO_PATIENT_ID ORDER BY IMMUNIZATION_TS DESC LIMIT 10;

SELECT c.PATIENT_ID, c.CLAIM_ID, c.APPOINTMENT_ID AS ENCOUNTER_ID,
       c.SERVICE_TS AS SERVICE_DATE, e.ENCOUNTER_CLASS
FROM CLAIM AS c
INNER JOIN ENCOUNTER AS e
    ON c.PATIENT_ID = e.PATIENT_ID AND c.APPOINTMENT_ID = e.ENCOUNTER_ID
WHERE c.PATIENT_ID = $DEMO_PATIENT_ID
ORDER BY c.SERVICE_TS DESC LIMIT 5;

SELECT PATIENT_ID, START_TS AS "START", END_TS AS "END", MEMBER_ID, PAYER_ID, PAYER_NAME
FROM MEMBER_COVERAGE WHERE PATIENT_ID = $DEMO_PATIENT_ID ORDER BY START_TS DESC LIMIT 10;

SELECT SECTION_LOINC, COUNT(*) AS ROWS_WITH_EVIDENCE
FROM DOCUMENT_SECTION
WHERE PATIENT_ID = $DEMO_PATIENT_ID
  AND SECTION_LOINC IN ('11450-4', '10160-0', '18776-5', '47519-4', '11369-6')
GROUP BY SECTION_LOINC
ORDER BY SECTION_LOINC;

SELECT COUNT(*) AS MINIMIZED_PATIENT_COLUMNS_PRESENT
FROM PATIENT_360.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'PATIENT'
  AND COLUMN_NAME IN (
      'ADDRESS', 'ZIP', 'COUNTY', 'FIPS', 'LATITUDE', 'LONGITUDE',
      'INCOME', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE',
      'MAIDEN_NAME', 'BIRTHPLACE'
  );
