-- Patient 360 load and safety gates.
-- Run after 90_roles_grants.sql, as the object owner.
-- Any FAIL stops the build. Do not explain a mismatch away.
-- Document gates fail closed until patient-360/generated/document_section.csv has been loaded.
-- The grant probe is a session temporary table and is dropped at the end.

USE DATABASE PATIENT_360;
USE SCHEMA CORE;
USE WAREHOUSE PATIENT_360_WH;

CREATE OR REPLACE TEMPORARY TABLE PATIENT_360.CORE._GATE (
    CHECK_NAME VARCHAR,
    EXPECTED_VALUE NUMBER(18, 2),
    ACTUAL_VALUE NUMBER(18, 2),
    STATUS VARCHAR
);

INSERT INTO PATIENT_360.CORE._GATE (CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE, STATUS)
SELECT CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE,
    CASE WHEN ACTUAL_VALUE = EXPECTED_VALUE THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT 'raw_patients_rows' AS CHECK_NAME, 108 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PATIENTS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_patient_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.PATIENT) - (SELECT COUNT(*) FROM PATIENT_360.RAW.PATIENTS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_encounters_rows' AS CHECK_NAME, 5571 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ENCOUNTERS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_encounter_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.ENCOUNTER) - (SELECT COUNT(*) FROM PATIENT_360.RAW.ENCOUNTERS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_claims_rows' AS CHECK_NAME, 9421 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_claim_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.CLAIM) - (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_claims_transactions_rows' AS CHECK_NAME, 85047 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_claim_line_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.CLAIM_LINE) - (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_conditions_rows' AS CHECK_NAME, 3517 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CONDITIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_condition_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.CONDITION) - (SELECT COUNT(*) FROM PATIENT_360.RAW.CONDITIONS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_medications_rows' AS CHECK_NAME, 3850 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.MEDICATIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_medication_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.MEDICATION) - (SELECT COUNT(*) FROM PATIENT_360.RAW.MEDICATIONS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_observations_rows' AS CHECK_NAME, 68648 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.OBSERVATIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_observation_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.OBSERVATION) - (SELECT COUNT(*) FROM PATIENT_360.RAW.OBSERVATIONS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_procedures_rows' AS CHECK_NAME, 15884 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PROCEDURES) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_procedure_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.PROCEDURE) - (SELECT COUNT(*) FROM PATIENT_360.RAW.PROCEDURES)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_allergies_rows' AS CHECK_NAME, 105 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ALLERGIES) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_allergy_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.ALLERGY) - (SELECT COUNT(*) FROM PATIENT_360.RAW.ALLERGIES)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_careplans_rows' AS CHECK_NAME, 349 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CAREPLANS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_careplan_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.CAREPLAN) - (SELECT COUNT(*) FROM PATIENT_360.RAW.CAREPLANS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_immunizations_rows' AS CHECK_NAME, 1549 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.IMMUNIZATIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_immunization_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.IMMUNIZATION) - (SELECT COUNT(*) FROM PATIENT_360.RAW.IMMUNIZATIONS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_imaging_studies_rows' AS CHECK_NAME, 478 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.IMAGING_STUDIES) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_imaging_study_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.IMAGING_STUDY) - (SELECT COUNT(*) FROM PATIENT_360.RAW.IMAGING_STUDIES)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_devices_rows' AS CHECK_NAME, 524 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.DEVICES) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_device_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.DEVICE) - (SELECT COUNT(*) FROM PATIENT_360.RAW.DEVICES)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_supplies_rows' AS CHECK_NAME, 2225 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.SUPPLIES) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_supply_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.SUPPLY) - (SELECT COUNT(*) FROM PATIENT_360.RAW.SUPPLIES)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_payer_transitions_rows' AS CHECK_NAME, 3815 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PAYER_TRANSITIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_payer_transition_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.PAYER_TRANSITION) - (SELECT COUNT(*) FROM PATIENT_360.RAW.PAYER_TRANSITIONS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_payers_rows' AS CHECK_NAME, 10 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PAYERS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_payer_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.PAYER) - (SELECT COUNT(*) FROM PATIENT_360.RAW.PAYERS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_organizations_rows' AS CHECK_NAME, 278 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ORGANIZATIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_organization_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.ORGANIZATION) - (SELECT COUNT(*) FROM PATIENT_360.RAW.ORGANIZATIONS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_providers_rows' AS CHECK_NAME, 278 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PROVIDERS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_provider_matches_raw' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.PROVIDER) - (SELECT COUNT(*) FROM PATIENT_360.RAW.PROVIDERS)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_document_section_matches_core' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION) - (SELECT COUNT(*) FROM PATIENT_360.RAW.DOCUMENT_SECTION)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'unique_patients_id' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID) FROM PATIENT_360.RAW.PATIENTS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'unique_encounters_id' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID) FROM PATIENT_360.RAW.ENCOUNTERS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'unique_claims_id' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID) FROM PATIENT_360.RAW.CLAIMS) AS ACTUAL_VALUE
) AS gate_rows;

INSERT INTO PATIENT_360.CORE._GATE (CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE, STATUS)
SELECT CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE,
    CASE WHEN ACTUAL_VALUE = EXPECTED_VALUE THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT 'unique_claims_transactions_id' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID) FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'unique_careplans_id' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID) FROM PATIENT_360.RAW.CAREPLANS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'unique_imaging_studies_instance' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID || '|' || SERIES_UID || '|' || INSTANCE_UID) FROM PATIENT_360.RAW.IMAGING_STUDIES) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'unique_payers_id' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID) FROM PATIENT_360.RAW.PAYERS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'unique_organizations_id' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID) FROM PATIENT_360.RAW.ORGANIZATIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'unique_providers_id' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT ID) FROM PATIENT_360.RAW.PROVIDERS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'medication_business_key_extra_rows' AS CHECK_NAME, 9 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT PATIENT || '|' || ENCOUNTER || '|' || CODE || '|' || TO_VARCHAR("START")) FROM PATIENT_360.RAW.MEDICATIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'observation_business_key_extra_rows' AS CHECK_NAME, 18 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT PATIENT || '|' || COALESCE(ENCOUNTER, '') || '|' || CODE || '|' || TO_VARCHAR(DATE) || '|' || VALUE) FROM PATIENT_360.RAW.OBSERVATIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'supply_business_key_extra_rows' AS CHECK_NAME, 11 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT PATIENT || '|' || ENCOUNTER || '|' || CODE || '|' || TO_VARCHAR(DATE)) FROM PATIENT_360.RAW.SUPPLIES) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'condition_business_key_extra_rows' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT PATIENT || '|' || ENCOUNTER || '|' || CODE || '|' || TO_VARCHAR("START")) FROM PATIENT_360.RAW.CONDITIONS) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'allergy_business_key_extra_rows' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) - COUNT(DISTINCT PATIENT || '|' || ENCOUNTER || '|' || CODE || '|' || TO_VARCHAR("START")) FROM PATIENT_360.RAW.ALLERGIES) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_encounter_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ENCOUNTERS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_encounter_organization' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ENCOUNTERS c LEFT JOIN PATIENT_360.RAW.ORGANIZATIONS p ON c.ORGANIZATION = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_encounter_provider' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ENCOUNTERS c LEFT JOIN PATIENT_360.RAW.PROVIDERS p ON c.PROVIDER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_encounter_payer' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ENCOUNTERS c LEFT JOIN PATIENT_360.RAW.PAYERS p ON c.PAYER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENTID = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_appointment' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.APPOINTMENTID = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_provider' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS c LEFT JOIN PATIENT_360.RAW.PROVIDERS p ON c.PROVIDERID = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_supervising_provider' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS c LEFT JOIN PATIENT_360.RAW.PROVIDERS p ON c.SUPERVISINGPROVIDERID = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_primary_payer' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS c LEFT JOIN PATIENT_360.RAW.PAYERS p ON c.PRIMARYPATIENTINSURANCEID = p.ID WHERE c.PRIMARYPATIENTINSURANCEID IS NOT NULL AND p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_secondary_payer' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS c LEFT JOIN PATIENT_360.RAW.PAYERS p ON c.SECONDARYPATIENTINSURANCEID = p.ID WHERE c.SECONDARYPATIENTINSURANCEID IS NOT NULL AND p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_line_claim' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS c LEFT JOIN PATIENT_360.RAW.CLAIMS p ON c.CLAIMID = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_line_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENTID = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_line_appointment' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.APPOINTMENTID = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_line_provider' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS c LEFT JOIN PATIENT_360.RAW.PROVIDERS p ON c.PROVIDERID = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_claim_line_place_of_service' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS c LEFT JOIN PATIENT_360.RAW.ORGANIZATIONS p ON c.PLACEOFSERVICE = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_provider_organization' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PROVIDERS c LEFT JOIN PATIENT_360.RAW.ORGANIZATIONS p ON c.ORGANIZATION = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_coverage_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PAYER_TRANSITIONS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_coverage_payer' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PAYER_TRANSITIONS c LEFT JOIN PATIENT_360.RAW.PAYERS p ON c.PAYER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_coverage_secondary_payer' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PAYER_TRANSITIONS c LEFT JOIN PATIENT_360.RAW.PAYERS p ON c.SECONDARY_PAYER = p.ID WHERE c.SECONDARY_PAYER IS NOT NULL AND p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_conditions_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CONDITIONS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_conditions_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CONDITIONS c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_medications_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.MEDICATIONS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_medications_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.MEDICATIONS c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_procedures_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PROCEDURES c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_procedures_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.PROCEDURES c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_allergies_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ALLERGIES c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_allergies_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.ALLERGIES c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_careplans_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CAREPLANS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_careplans_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.CAREPLANS c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
) AS gate_rows;

INSERT INTO PATIENT_360.CORE._GATE (CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE, STATUS)
SELECT CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE,
    CASE WHEN ACTUAL_VALUE = EXPECTED_VALUE THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT 'orphan_immunizations_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.IMMUNIZATIONS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_immunizations_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.IMMUNIZATIONS c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_imaging_studies_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.IMAGING_STUDIES c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_imaging_studies_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.IMAGING_STUDIES c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_devices_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.DEVICES c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_devices_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.DEVICES c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_supplies_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.SUPPLIES c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_supplies_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.SUPPLIES c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_observations_patient' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.OBSERVATIONS c LEFT JOIN PATIENT_360.RAW.PATIENTS p ON c.PATIENT = p.ID WHERE p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'orphan_observations_encounter_when_present' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.OBSERVATIONS c LEFT JOIN PATIENT_360.RAW.ENCOUNTERS p ON c.ENCOUNTER = p.ID WHERE c.ENCOUNTER IS NOT NULL AND p.ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'observations_blank_encounter_and_category' AS CHECK_NAME, 3060 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.OBSERVATIONS WHERE ENCOUNTER IS NULL AND CATEGORY IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'observations_blank_encounter_only' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.OBSERVATIONS WHERE ENCOUNTER IS NULL AND CATEGORY IS NOT NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'observations_blank_category_only' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.RAW.OBSERVATIONS WHERE ENCOUNTER IS NOT NULL AND CATEGORY IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_columns_named_ssn_drivers_or_passport' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'CORE' AND COLUMN_NAME IN ('SSN', 'DRIVERS', 'PASSPORT')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'core_patient_precise_or_financial_columns' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (
        SELECT COUNT(*)
        FROM PATIENT_360.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'CORE'
          AND TABLE_NAME = 'PATIENT'
          AND COLUMN_NAME IN (
              'ADDRESS', 'ZIP', 'COUNTY', 'FIPS', 'LATITUDE', 'LONGITUDE',
              'INCOME', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE',
              'MAIDEN_NAME', 'BIRTHPLACE'
          )
    ) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'raw_patients_has_three_restricted_columns' AS CHECK_NAME, 3 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'RAW' AND TABLE_NAME = 'PATIENTS' AND COLUMN_NAME IN ('SSN', 'DRIVERS', 'PASSPORT')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'a1c_rows' AS CHECK_NAME, 720 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.OBSERVATION WHERE CODE = '4548-4') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'a1c_patients' AS CHECK_NAME, 39 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT PATIENT_ID) FROM PATIENT_360.CORE.OBSERVATION WHERE CODE = '4548-4') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'medication_review_conditions' AS CHECK_NAME, 692 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.CONDITION WHERE DESCRIPTION = 'Medication review due (situation)') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'coverage_spans_without_member_id' AS CHECK_NAME, 1082 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.PAYER_TRANSITION WHERE MEMBER_ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'deaths' AS CHECK_NAME, 9 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.PATIENT WHERE DEATHDATE IS NOT NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_cohort_patients' AS CHECK_NAME, 97 AS EXPECTED_VALUE, (SELECT MAX(COHORT_PATIENT_COUNT) FROM PATIENT_360.CORE.RISK_SCORE) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_cohort_events' AS CHECK_NAME, 14 AS EXPECTED_VALUE, (SELECT MAX(COHORT_EVENT_COUNT) FROM PATIENT_360.CORE.RISK_SCORE) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_base_rate_pct' AS CHECK_NAME, 14.43 AS EXPECTED_VALUE, (SELECT MAX(BASE_RATE_PCT) FROM PATIENT_360.CORE.RISK_SCORE) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_excluded_born_on_or_after_index' AS CHECK_NAME, 4 AS EXPECTED_VALUE, (SELECT MAX(EXCLUDED_BORN_ON_OR_AFTER_INDEX) FROM PATIENT_360.CORE.RISK_SCORE) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_excluded_dead_on_or_before_index' AS CHECK_NAME, 7 AS EXPECTED_VALUE, (SELECT MAX(EXCLUDED_DEAD_ON_OR_BEFORE_INDEX) FROM PATIENT_360.CORE.RISK_SCORE) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_excluded_no_prior_encounter' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT MAX(EXCLUDED_NO_PRIOR_ENCOUNTER) FROM PATIENT_360.CORE.RISK_SCORE) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_0_patients' AS CHECK_NAME, 19 AS EXPECTED_VALUE, (SELECT PATIENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '0') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_0_events' AS CHECK_NAME, 1 AS EXPECTED_VALUE, (SELECT EVENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '0') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_0_rate_pct' AS CHECK_NAME, 5.26 AS EXPECTED_VALUE, (SELECT EVENT_RATE_PCT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '0') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_1_patients' AS CHECK_NAME, 37 AS EXPECTED_VALUE, (SELECT PATIENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '1') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_1_events' AS CHECK_NAME, 6 AS EXPECTED_VALUE, (SELECT EVENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '1') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_1_rate_pct' AS CHECK_NAME, 16.22 AS EXPECTED_VALUE, (SELECT EVENT_RATE_PCT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '1') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_2_patients' AS CHECK_NAME, 35 AS EXPECTED_VALUE, (SELECT PATIENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_2_events' AS CHECK_NAME, 5 AS EXPECTED_VALUE, (SELECT EVENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_2_rate_pct' AS CHECK_NAME, 14.29 AS EXPECTED_VALUE, (SELECT EVENT_RATE_PCT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_3_patients' AS CHECK_NAME, 6 AS EXPECTED_VALUE, (SELECT PATIENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '3') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_3_events' AS CHECK_NAME, 2 AS EXPECTED_VALUE, (SELECT EVENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '3') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_3_rate_pct' AS CHECK_NAME, 33.33 AS EXPECTED_VALUE, (SELECT EVENT_RATE_PCT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '3') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_4_patients' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT PATIENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '4') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_4_events' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT EVENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '4') AS ACTUAL_VALUE
) AS gate_rows;

INSERT INTO PATIENT_360.CORE._GATE (CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE, STATUS)
SELECT CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE,
    CASE WHEN ACTUAL_VALUE = EXPECTED_VALUE THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT 'risk_bucket_4_rate_absent' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT IFF(EVENT_RATE_PCT IS NULL, 0, 1) FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = '4') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_ge_2_patients' AS CHECK_NAME, 41 AS EXPECTED_VALUE, (SELECT PATIENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = 'GE_2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_ge_2_events' AS CHECK_NAME, 7 AS EXPECTED_VALUE, (SELECT EVENT_COUNT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = 'GE_2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_bucket_ge_2_rate_pct' AS CHECK_NAME, 17.07 AS EXPECTED_VALUE, (SELECT EVENT_RATE_PCT FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET = 'GE_2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_buckets_sum_to_cohort' AS CHECK_NAME, 97 AS EXPECTED_VALUE, (SELECT SUM(PATIENT_COUNT) FROM PATIENT_360.CORE.RISK_SCORE WHERE SCORE_BUCKET IN ('0', '1', '2', '3', '4')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_feature_on_or_after_index' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.RISK_FEATURE WHERE EVENT_TS >= TIMESTAMP '2023-01-01 00:00:00') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_feature_document_rows' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.RISK_FEATURE WHERE SOURCE_TABLE = 'DOCUMENT_SECTION') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_feature_ddl_has_no_document_section' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT IFF(GET_DDL('VIEW', 'PATIENT_360.CORE.RISK_FEATURE') ILIKE '%DOCUMENT_SECTION%', 1, 0)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_cohort_ddl_has_no_document_section' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT IFF(GET_DDL('VIEW', 'PATIENT_360.CORE.RISK_COHORT') ILIKE '%DOCUMENT_SECTION%', 1, 0)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_score_ddl_has_no_document_section' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT IFF(GET_DDL('VIEW', 'PATIENT_360.CORE.RISK_SCORE') ILIKE '%DOCUMENT_SECTION%', 1, 0)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_feature_conditions_match_pre_index' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.RISK_FEATURE WHERE SOURCE_TABLE = 'CONDITION') - (SELECT COUNT(*) FROM PATIENT_360.CORE.CONDITION WHERE START_DATE < DATE '2023-01-01')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_feature_encounters_match_pre_index' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.RISK_FEATURE WHERE SOURCE_TABLE = 'ENCOUNTER') - (SELECT COUNT(*) FROM PATIENT_360.CORE.ENCOUNTER WHERE START_TS < TIMESTAMP '2023-01-01 00:00:00')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'risk_feature_observations_match_pre_index' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT (SELECT COUNT(*) FROM PATIENT_360.CORE.RISK_FEATURE WHERE SOURCE_TABLE = 'OBSERVATION') - (SELECT COUNT(*) FROM PATIENT_360.CORE.OBSERVATION WHERE OBSERVATION_TS < TIMESTAMP '2023-01-01 00:00:00')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'demo_patient_identity' AS CHECK_NAME, 1 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.PATIENT WHERE PATIENT_ID = '37549f60-b5a3-69cd-dea6-5a71c4bc23cf' AND FIRST_NAME = 'Alexandra16' AND LAST_NAME = 'Mosciski958' AND CITY = 'Waltham' AND STATE = 'Massachusetts' AND BIRTHDATE = DATE '1981-05-25') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'demo_fexofenadine_row' AS CHECK_NAME, 1 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.MEDICATION WHERE PATIENT_ID = '37549f60-b5a3-69cd-dea6-5a71c4bc23cf' AND CODE = '997501' AND DESCRIPTION = 'Fexofenadine hydrochloride 60 MG Oral Tablet' AND START_TS = TIMESTAMP '2005-06-18 13:48:14' AND ENCOUNTER_ID = '37549f60-b5a3-69cd-bd30-c7a0b0133ccf') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'demo_allergy_csv_match' AS CHECK_NAME, 1 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.ALLERGY WHERE PATIENT_ID = '37549f60-b5a3-69cd-dea6-5a71c4bc23cf' AND CODE = '609328004' AND DESCRIPTION = 'Allergic disposition (finding)' AND START_DATE = DATE '2005-06-18' AND ENCOUNTER_ID = '37549f60-b5a3-69cd-bd30-c7a0b0133ccf') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'demo_allergy_assertion_code_not_in_csv' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.ALLERGY WHERE PATIENT_ID = '37549f60-b5a3-69cd-dea6-5a71c4bc23cf' AND CODE = '419199007') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'document_ids' AS CHECK_NAME, 108 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'document_id_patient_id_mismatches' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE DOCUMENT_ID <> PATIENT_ID) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'patients_missing_document' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.PATIENT p LEFT JOIN (SELECT DISTINCT PATIENT_ID FROM PATIENT_360.CORE.DOCUMENT_SECTION) d ON d.PATIENT_ID = p.PATIENT_ID WHERE d.PATIENT_ID IS NULL) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'document_element_duplicate_groups' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM (SELECT DOCUMENT_ID, ELEMENT_ID FROM PATIENT_360.CORE.DOCUMENT_SECTION GROUP BY DOCUMENT_ID, ELEMENT_ID HAVING COUNT(*) > 1)) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_10160_0_documents' AS CHECK_NAME, 105 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '10160-0') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_30954_2_documents' AS CHECK_NAME, 108 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '30954-2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_11450_4_documents' AS CHECK_NAME, 108 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '11450-4') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_46240_8_documents' AS CHECK_NAME, 108 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '46240-8') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_8716_3_documents' AS CHECK_NAME, 108 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '8716-3') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_11369_6_documents' AS CHECK_NAME, 108 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '11369-6') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_29762_2_documents' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '29762-2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'document_section_rows' AS CHECK_NAME, 96806 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_47519_4_documents' AS CHECK_NAME, 107 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '47519-4') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_18776_5_documents' AS CHECK_NAME, 101 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '18776-5') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_47420_5_documents' AS CHECK_NAME, 94 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '47420-5') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'section_48765_2_documents' AS CHECK_NAME, 21 AS EXPECTED_VALUE, (SELECT COUNT(DISTINCT DOCUMENT_ID) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '48765-2') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'narrative_medications_desc_cells' AS CHECK_NAME, 3850 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE REGEXP_LIKE(ELEMENT_ID, '^medications-desc-[0-9]+$')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'narrative_conditions_desc_cells' AS CHECK_NAME, 3517 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE REGEXP_LIKE(ELEMENT_ID, '^conditions-desc-[0-9]+$')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'narrative_encounters_desc_cells' AS CHECK_NAME, 5571 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE REGEXP_LIKE(ELEMENT_ID, '^encounters-desc-[0-9]+$')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'narrative_procedures_desc_cells' AS CHECK_NAME, 15884 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE REGEXP_LIKE(ELEMENT_ID, '^procedures-desc-[0-9]+$')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'narrative_immunizations_desc_cells' AS CHECK_NAME, 1549 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE REGEXP_LIKE(ELEMENT_ID, '^immunizations-desc-[0-9]+$')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'narrative_careplans_desc_cells' AS CHECK_NAME, 349 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE REGEXP_LIKE(ELEMENT_ID, '^careplans-desc-[0-9]+$')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'narrative_allergies_desc_cells' AS CHECK_NAME, 105 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE REGEXP_LIKE(ELEMENT_ID, '^allergies-desc-[0-9]+$')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'demo_medication_desc_cell' AS CHECK_NAME, 1 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE DOCUMENT_ID = '37549f60-b5a3-69cd-dea6-5a71c4bc23cf' AND SECTION_LOINC = '10160-0' AND ELEMENT_ID = 'medications-desc-2' AND TEXT ILIKE '%Fexofenadine hydrochloride 60 MG Oral Tablet%') AS ACTUAL_VALUE
) AS gate_rows;

INSERT INTO PATIENT_360.CORE._GATE (CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE, STATUS)
SELECT CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE,
    CASE WHEN ACTUAL_VALUE = EXPECTED_VALUE THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT 'demo_medication_code_cell' AS CHECK_NAME, 1 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE DOCUMENT_ID = '37549f60-b5a3-69cd-dea6-5a71c4bc23cf' AND SECTION_LOINC = '10160-0' AND ELEMENT_ID = 'medications-code-2' AND (CODE = '997501' OR TEXT ILIKE '%997501%')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'demo_allergy_code_cell' AS CHECK_NAME, 1 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE DOCUMENT_ID = '37549f60-b5a3-69cd-dea6-5a71c4bc23cf' AND SECTION_LOINC = '48765-2' AND ELEMENT_ID = 'allergies-code-1' AND (CODE = '609328004' OR TEXT ILIKE '%609328004%')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'no_openfda_objects' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG = 'PATIENT_360' AND TABLE_NAME ILIKE '%OPENFDA%') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'no_discharge_objects' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG = 'PATIENT_360' AND TABLE_NAME ILIKE '%DISCHARGE%') AS ACTUAL_VALUE
    UNION ALL
    SELECT 'no_dose_order_objects' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG = 'PATIENT_360' AND TABLE_NAME IN ('DOSE_ORDER', 'MEDICATION_ORDER')) AS ACTUAL_VALUE
    UNION ALL
    SELECT 'no_discharge_summary_sections' AS CHECK_NAME, 0 AS EXPECTED_VALUE, (SELECT COUNT(*) FROM PATIENT_360.CORE.DOCUMENT_SECTION WHERE SECTION_LOINC = '18842-5' OR SECTION_TITLE ILIKE '%discharge summary%') AS ACTUAL_VALUE
) AS gate_rows;

SHOW GRANTS TO ROLE PATIENT_360_ANALYST;

CREATE OR REPLACE TEMPORARY TABLE PATIENT_360.CORE._ANALYST_GRANT_PROBE AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

INSERT INTO PATIENT_360.CORE._GATE (CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE, STATUS)
SELECT CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE,
    CASE WHEN ACTUAL_VALUE = EXPECTED_VALUE THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (
    SELECT 'analyst_privilege_on_raw' AS CHECK_NAME,
        0 AS EXPECTED_VALUE,
        COUNT_IF(UPPER("name") LIKE 'PATIENT_360.RAW%') AS ACTUAL_VALUE
    FROM PATIENT_360.CORE._ANALYST_GRANT_PROBE
    UNION ALL
    SELECT 'analyst_select_on_core_patient',
        1,
        IFF(COUNT_IF(UPPER("privilege") = 'SELECT' AND UPPER("name") = 'PATIENT_360.CORE.PATIENT') >= 1, 1, 0)
    FROM PATIENT_360.CORE._ANALYST_GRANT_PROBE
    UNION ALL
    SELECT 'analyst_select_on_sem_member',
        1,
        IFF(COUNT_IF(UPPER("privilege") = 'SELECT' AND UPPER("name") LIKE '%SEM_MEMBER') >= 1, 1, 0)
    FROM PATIENT_360.CORE._ANALYST_GRANT_PROBE
) AS gate_rows;

SHOW SEMANTIC VIEWS LIKE 'SEM_MEMBER' IN SCHEMA PATIENT_360.CORE;

CREATE OR REPLACE TEMPORARY TABLE PATIENT_360.CORE._SEM_PROBE AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

INSERT INTO PATIENT_360.CORE._GATE (CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE, STATUS)
SELECT 'semantic_view_sem_member' AS CHECK_NAME,
    1 AS EXPECTED_VALUE,
    (SELECT COUNT(*) FROM PATIENT_360.CORE._SEM_PROBE) AS ACTUAL_VALUE,
    CASE
        WHEN (SELECT COUNT(*) FROM PATIENT_360.CORE._SEM_PROBE) = 1 THEN 'PASS'
        ELSE 'FAIL'
    END AS STATUS;

SELECT CHECK_NAME, EXPECTED_VALUE, ACTUAL_VALUE, STATUS
FROM PATIENT_360.CORE._GATE
ORDER BY CASE WHEN STATUS = 'FAIL' THEN 0 ELSE 1 END, CHECK_NAME;

SELECT COUNT(*) AS FAILED_GATE_COUNT
FROM PATIENT_360.CORE._GATE
WHERE STATUS = 'FAIL';

-- Make Snowflake CLI exit non-zero when a gate fails.
SELECT CASE
    WHEN COUNT_IF(STATUS = 'FAIL') = 0 THEN 0
    ELSE TO_NUMBER('EXPECTED_CHECKS_FAILED')
END AS ASSERT_ZERO_FAILED_GATES
FROM PATIENT_360.CORE._GATE;

DROP TABLE IF EXISTS PATIENT_360.CORE._GATE;
DROP TABLE IF EXISTS PATIENT_360.CORE._ANALYST_GRANT_PROBE;
DROP TABLE IF EXISTS PATIENT_360.CORE._SEM_PROBE;
