-- Concordia bootstrap. Run once by a privileged role (ACCOUNTADMIN on the hackathon account).
-- Account-level changes are limited to: seven CONCORDIA_* roles, two XS warehouses,
-- one database, and the CORTEX_USER database role grant. The account EVENT_TABLE
-- (snowflake.telemetry.events) is not touched. ACCOUNTADMIN owns nothing below.

CREATE ROLE IF NOT EXISTS CONCORDIA_ADMIN;
CREATE ROLE IF NOT EXISTS CONCORDIA_INGEST;
CREATE ROLE IF NOT EXISTS CONCORDIA_TRANSFORM;
CREATE ROLE IF NOT EXISTS CONCORDIA_APP_OWNER;
CREATE ROLE IF NOT EXISTS CONCORDIA_APP;
CREATE ROLE IF NOT EXISTS CONCORDIA_AUDITOR;
CREATE ROLE IF NOT EXISTS CONCORDIA_TEST;

GRANT ROLE CONCORDIA_INGEST TO ROLE CONCORDIA_ADMIN;
GRANT ROLE CONCORDIA_TRANSFORM TO ROLE CONCORDIA_ADMIN;
GRANT ROLE CONCORDIA_APP TO ROLE CONCORDIA_APP_OWNER;
GRANT ROLE CONCORDIA_ADMIN TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_APP_OWNER TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_AUDITOR TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_TEST TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_ADMIN TO USER IDENTIFIER($CONCORDIA_USER);
GRANT ROLE CONCORDIA_APP_OWNER TO USER IDENTIFIER($CONCORDIA_USER);
GRANT ROLE CONCORDIA_APP TO USER IDENTIFIER($CONCORDIA_USER);
GRANT ROLE CONCORDIA_AUDITOR TO USER IDENTIFIER($CONCORDIA_USER);
GRANT ROLE CONCORDIA_TEST TO USER IDENTIFIER($CONCORDIA_USER);

CREATE WAREHOUSE IF NOT EXISTS CONCORDIA_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Concordia transform and deploy. XS, 60 s auto-suspend.';
CREATE WAREHOUSE IF NOT EXISTS CONCORDIA_APP_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Concordia Streamlit and Cortex. XS, 60 s auto-suspend.';
GRANT USAGE, OPERATE ON WAREHOUSE CONCORDIA_WH TO ROLE CONCORDIA_ADMIN;
GRANT USAGE ON WAREHOUSE CONCORDIA_WH TO ROLE CONCORDIA_TRANSFORM;
GRANT USAGE ON WAREHOUSE CONCORDIA_WH TO ROLE CONCORDIA_INGEST;
GRANT USAGE ON WAREHOUSE CONCORDIA_WH TO ROLE CONCORDIA_TEST;
GRANT USAGE ON WAREHOUSE CONCORDIA_APP_WH TO ROLE CONCORDIA_APP_OWNER;
GRANT USAGE ON WAREHOUSE CONCORDIA_APP_WH TO ROLE CONCORDIA_APP;
GRANT USAGE ON WAREHOUSE CONCORDIA_APP_WH TO ROLE CONCORDIA_AUDITOR;
GRANT USAGE ON WAREHOUSE CONCORDIA_APP_WH TO ROLE CONCORDIA_ADMIN;

CREATE DATABASE IF NOT EXISTS CONCORDIA COMMENT = 'Concordia governed supply-chain analytics. Synthetic data only.';
GRANT OWNERSHIP ON DATABASE CONCORDIA TO ROLE CONCORDIA_ADMIN COPY CURRENT GRANTS;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE CONCORDIA_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONCORDIA_APP_OWNER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONCORDIA_ADMIN;
