-- Landing: stage, raw VARIANT records, idempotent merge, quarantine. Runs as CONCORDIA_ADMIN.

USE ROLE CONCORDIA_ADMIN;
USE WAREHOUSE CONCORDIA_WH;
USE DATABASE CONCORDIA;

CREATE STAGE IF NOT EXISTS LAND.WORLD_STAGE
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Synthetic source extracts (ERP, MES, WMS, TMS, CRM, IoT), governance contract, manifest.';
CREATE FILE FORMAT IF NOT EXISTS LAND.JSONL_FMT TYPE = JSON COMPRESSION = AUTO STRIP_OUTER_ARRAY = FALSE;
CREATE FILE FORMAT IF NOT EXISTS LAND.JSON_FMT TYPE = JSON COMPRESSION = AUTO STRIP_OUTER_ARRAY = FALSE;

CREATE TABLE IF NOT EXISTS LAND.RAW_RECORD (
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SOURCE_OBJECT VARCHAR NOT NULL,
  SOURCE_RECORD_ID VARCHAR NOT NULL,
  SOURCE_REVISION NUMBER NOT NULL,
  RECORDED_AT TIMESTAMP_TZ,
  EXTRACTED_AT TIMESTAMP_TZ,
  VISIBLE_AT TIMESTAMP_TZ NOT NULL,
  ORIGIN VARCHAR NOT NULL,
  GENERATOR_VERSION VARCHAR,
  SEED_STREAM VARCHAR,
  SCENARIO_ID VARCHAR,
  PAYLOAD VARIANT NOT NULL,
  PAYLOAD_HASH VARCHAR NOT NULL,
  FILE_NAME VARCHAR,
  LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
) CHANGE_TRACKING = TRUE
  COMMENT = 'Append-only. Idempotency key (SOURCE_SYSTEM, SOURCE_RECORD_ID + object, SOURCE_REVISION, PAYLOAD_HASH).';

CREATE TRANSIENT TABLE IF NOT EXISTS LAND.RAW_INCOMING (DOC VARIANT, FILE_NAME VARCHAR);

CREATE TABLE IF NOT EXISTS LAND.QUARANTINE (
  SOURCE_SYSTEM VARCHAR, SOURCE_OBJECT VARCHAR, SOURCE_RECORD_ID VARCHAR, SOURCE_REVISION NUMBER,
  REASON VARCHAR, DETAIL VARCHAR, VISIBLE_AT TIMESTAMP_TZ, DETECTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE STREAM IF NOT EXISTS LAND.RAW_RECORD_STREAM ON TABLE LAND.RAW_RECORD APPEND_ONLY = TRUE;

CREATE OR REPLACE PROCEDURE LAND.LOAD_EXTRACTS(PATTERN VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  copied NUMBER DEFAULT 0;
  inserted NUMBER DEFAULT 0;
  started TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP();
  run_id VARCHAR DEFAULT UUID_STRING();
BEGIN
  TRUNCATE TABLE LAND.RAW_INCOMING;
  EXECUTE IMMEDIATE 'COPY INTO LAND.RAW_INCOMING (DOC, FILE_NAME) FROM (SELECT $1, METADATA$FILENAME FROM @LAND.WORLD_STAGE/sources/) '
    || 'FILE_FORMAT = (FORMAT_NAME = ''LAND.JSONL_FMT'') PATTERN = ''' || :PATTERN || ''' ON_ERROR = ABORT_STATEMENT';
  SELECT COUNT(*) INTO :copied FROM LAND.RAW_INCOMING;
  MERGE INTO LAND.RAW_RECORD t
  USING (
    SELECT DOC:source_system::VARCHAR AS SOURCE_SYSTEM, DOC:source_object::VARCHAR AS SOURCE_OBJECT,
           DOC:source_record_id::VARCHAR AS SOURCE_RECORD_ID, DOC:source_revision::NUMBER AS SOURCE_REVISION,
           DOC:recorded_at::TIMESTAMP_TZ AS RECORDED_AT, DOC:extracted_at::TIMESTAMP_TZ AS EXTRACTED_AT,
           DOC:visible_at::TIMESTAMP_TZ AS VISIBLE_AT, DOC:origin::VARCHAR AS ORIGIN, DOC:generator_version::VARCHAR AS GENERATOR_VERSION,
           DOC:seed_stream::VARCHAR AS SEED_STREAM, DOC:scenario_id::VARCHAR AS SCENARIO_ID, DOC:payload AS PAYLOAD,
           DOC:payload_hash::VARCHAR AS PAYLOAD_HASH, FILE_NAME
    FROM LAND.RAW_INCOMING
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SOURCE_SYSTEM, SOURCE_OBJECT, SOURCE_RECORD_ID, SOURCE_REVISION, PAYLOAD_HASH ORDER BY EXTRACTED_AT) = 1
  ) s
  ON t.SOURCE_SYSTEM = s.SOURCE_SYSTEM AND t.SOURCE_OBJECT = s.SOURCE_OBJECT AND t.SOURCE_RECORD_ID = s.SOURCE_RECORD_ID
     AND t.SOURCE_REVISION = s.SOURCE_REVISION AND t.PAYLOAD_HASH = s.PAYLOAD_HASH
  WHEN NOT MATCHED THEN INSERT (SOURCE_SYSTEM, SOURCE_OBJECT, SOURCE_RECORD_ID, SOURCE_REVISION, RECORDED_AT, EXTRACTED_AT, VISIBLE_AT,
                                ORIGIN, GENERATOR_VERSION, SEED_STREAM, SCENARIO_ID, PAYLOAD, PAYLOAD_HASH, FILE_NAME)
    VALUES (s.SOURCE_SYSTEM, s.SOURCE_OBJECT, s.SOURCE_RECORD_ID, s.SOURCE_REVISION, s.RECORDED_AT, s.EXTRACTED_AT, s.VISIBLE_AT,
            s.ORIGIN, s.GENERATOR_VERSION, s.SEED_STREAM, s.SCENARIO_ID, s.PAYLOAD, s.PAYLOAD_HASH, s.FILE_NAME);
  inserted := SQLROWCOUNT;
  INSERT INTO GOV.PIPELINE_RUN SELECT :run_id, :started, CURRENT_TIMESTAMP(), 'LAND.LOAD_EXTRACTS', 'SUCCEEDED', :copied, :inserted,
    OBJECT_CONSTRUCT('pattern', :PATTERN, 'duplicates_ignored', :copied - :inserted);
  TRUNCATE TABLE LAND.RAW_INCOMING;
  RETURN OBJECT_CONSTRUCT('run_id', :run_id, 'copied', :copied, 'inserted', :inserted, 'duplicates_ignored', :copied - :inserted);
END;
$$;

-- Governance contract file -> GOV master tables (MDM publication, not hidden truth).
CREATE OR REPLACE PROCEDURE LAND.LOAD_GOVERNANCE()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
  CREATE OR REPLACE TEMPORARY TABLE LAND.GOV_DOC AS
    SELECT $1 AS DOC FROM @LAND.WORLD_STAGE/governance.json (FILE_FORMAT => 'LAND.JSON_FMT');
  DELETE FROM GOV.ITEM;
  INSERT INTO GOV.ITEM SELECT f.value:item_id, f.value:name, f.value:item_type, f.value:family, f.value:inventory_class, f.value:home_facility_id, f.value:unit_weight_kg
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:items) f;
  DELETE FROM GOV.PARTY;
  INSERT INTO GOV.PARTY SELECT f.value:party_id, f.value:party_type, f.value:name, f.value:country, f.value:currency, f.value:parent_party_id, f.value:geography_id
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:parties) f;
  DELETE FROM GOV.SHIP_TO;
  INSERT INTO GOV.SHIP_TO SELECT f.value:ship_to_id, f.value:customer_id, f.value:geography_id, f.value:timezone, f.value:calendar_id, f.value:country
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:ship_tos) f;
  DELETE FROM GOV.FACILITY;
  INSERT INTO GOV.FACILITY SELECT f.value:facility_id, f.value:name, f.value:kind, f.value:country, f.value:timezone, f.value:calendar_id
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:facilities) f;
  DELETE FROM GOV.GEOGRAPHY;
  INSERT INTO GOV.GEOGRAPHY SELECT f.value:geography_id, f.value:name, f.value:country, f.value:timezone
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:geographies) f;
  DELETE FROM GOV.CALENDAR;
  INSERT INTO GOV.CALENDAR SELECT f.value:calendar_id, f.value:name, f.value:shutdowns
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:calendars) f;
  DELETE FROM GOV.LANE;
  INSERT INTO GOV.LANE SELECT f.value:lane_id, f.value:origin_id, f.value:destination_id, f.value:mode, f.value:transit_mu, f.value:carrier
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:lanes) f;
  DELETE FROM GOV.SUPPLY;
  INSERT INTO GOV.SUPPLY SELECT f.value:supplier_id, f.value:item_id FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:supply) f;
  DELETE FROM GOV.SUBSTITUTION;
  INSERT INTO GOV.SUBSTITUTION
    SELECT f.value:item_id, f.value:substitute_item_id, f.value:valid_from::DATE, f.value:valid_to::DATE, f.value:approved_by
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:substitutions) f;
  DELETE FROM GOV.UOM_CONVERSION;
  INSERT INTO GOV.UOM_CONVERSION SELECT f.value:item_id, f.value:from_uom, f.value:to_uom, f.value:factor::NUMBER(18,6)
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:uom) f;
  DELETE FROM GOV.SOURCE_ALIAS;
  INSERT INTO GOV.SOURCE_ALIAS (SOURCE_SYSTEM, ENTITY_TYPE, SOURCE_KEY, CANONICAL_ID, METHOD)
    SELECT f.value:source_system, f.value:entity_type, f.value:source_key, f.value:canonical_id, f.value:method
    FROM LAND.GOV_DOC, LATERAL FLATTEN(DOC:aliases) f;

  -- Governed business-day calendars, 2024-2027.
  DELETE FROM GOV.CALENDAR_DAY;
  INSERT INTO GOV.CALENDAR_DAY
    WITH days AS (SELECT DATEADD(day, SEQ4(), '2024-01-01'::DATE) AS DAY FROM TABLE(GENERATOR(ROWCOUNT => 1461))),
    flagged AS (
      SELECT c.CALENDAR_ID, d.DAY,
             DAYOFWEEKISO(d.DAY) <= 5 AND NOT ARRAY_CONTAINS(TO_VARCHAR(d.DAY, 'YYYY-MM-DD')::VARIANT, c.SHUTDOWNS) AS IS_BUSINESS
      FROM GOV.CALENDAR c CROSS JOIN days d
    )
    SELECT CALENDAR_ID, DAY, IS_BUSINESS,
           SUM(IFF(IS_BUSINESS, 1, 0)) OVER (PARTITION BY CALENDAR_ID ORDER BY DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
    FROM flagged;
  RETURN OBJECT_CONSTRUCT('items', (SELECT COUNT(*) FROM GOV.ITEM), 'aliases', (SELECT COUNT(*) FROM GOV.SOURCE_ALIAS),
                          'calendar_days', (SELECT COUNT(*) FROM GOV.CALENDAR_DAY));
END;
$$;

GRANT READ, WRITE ON STAGE LAND.WORLD_STAGE TO ROLE CONCORDIA_INGEST;
GRANT SELECT ON TABLE LAND.RAW_RECORD TO ROLE CONCORDIA_TRANSFORM;
GRANT SELECT, INSERT ON TABLE LAND.QUARANTINE TO ROLE CONCORDIA_TRANSFORM;
GRANT SELECT ON STREAM LAND.RAW_RECORD_STREAM TO ROLE CONCORDIA_TRANSFORM;
