-- Canonical layer: tables, deterministic resolution, event ledger, knowledge graph, task.
-- Runs as CONCORDIA_ADMIN. WORLD_ID separates the product world ('MERIDIAN') from
-- golden evaluation worlds ('EVAL:<case>'), which exist only for SQL parity tests.

USE ROLE CONCORDIA_ADMIN;
USE WAREHOUSE CONCORDIA_WH;
USE DATABASE CONCORDIA;

CREATE OR REPLACE FUNCTION CORE.PARSE_DATE(S VARCHAR)
RETURNS DATE
AS $$ COALESCE(TRY_TO_DATE(S, 'YYYY-MM-DD'), TRY_TO_DATE(S, 'MM/DD/YYYY'), TRY_TO_DATE(S, 'DD.MM.YYYY')) $$;

CREATE OR REPLACE FUNCTION CORE.MINOR(S VARCHAR)
RETURNS NUMBER(38,0)
AS $$ IFF(S IS NULL, NULL, ROUND(TO_NUMBER(S, 38, 2) * 100, 0)::NUMBER(38,0)) $$;

CREATE TABLE IF NOT EXISTS CORE.PO_LINE (
  WORLD_ID VARCHAR, LINE_ID VARCHAR, SUPPLIER_ID VARCHAR, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, TIMEZONE VARCHAR, CALENDAR_ID VARCHAR,
  ORDERED_QTY NUMBER(38,6), ISSUED_ON DATE, BUYER_REQUESTED_ON DATE, ACK_ON DATE, ACK_PROMISE_ON DATE, ACK_VISIBLE_AT TIMESTAMP_TZ,
  FIRST_RECEIPT_ON DATE, CANCELLATION VARCHAR, SUPPLIER_REJECTED_QTY NUMBER(38,6), INCOTERM VARCHAR,
  IDENTITY_RESOLVED BOOLEAN, UOM_RESOLVED BOOLEAN, TIMEZONE_RESOLVED BOOLEAN, DISPOSITION_MISSING BOOLEAN,
  VISIBLE_AT TIMESTAMP_TZ, SOURCE_REF VARCHAR, SEQ NUMBER
);
CREATE TABLE IF NOT EXISTS CORE.PO_ACCEPTANCE (
  WORLD_ID VARCHAR, EVENT_ID VARCHAR, LINE_ID VARCHAR, RECEIPT_ID VARCHAR, ACCEPTED_ON DATE, QTY NUMBER(38,6), VISIBLE_AT TIMESTAMP_TZ, SEQ NUMBER
);
CREATE TABLE IF NOT EXISTS CORE.SO_LINE (
  WORLD_ID VARCHAR, LINE_ID VARCHAR, CUSTOMER_ID VARCHAR, SHIP_TO_ID VARCHAR, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, GEOGRAPHY_ID VARCHAR,
  TIMEZONE VARCHAR, CALENDAR_ID VARCHAR, INCOTERM VARCHAR, ORDERED_QTY NUMBER(38,6), ORDER_ON DATE, REQUESTED_SHIP_ON DATE,
  ORIGINAL_PROMISE_ON DATE, CANCELLATION VARCHAR, SUBSTITUTE VARCHAR, HOLD_START DATE, HOLD_END DATE, HOLD_RECORDED_ON DATE,
  SHORT_CLOSE_QTY NUMBER(38,6), SHORT_CLOSE_APPROVED_ON DATE, IDENTITY_RESOLVED BOOLEAN, UOM_RESOLVED BOOLEAN,
  VISIBLE_AT TIMESTAMP_TZ, SOURCE_REF VARCHAR, SEQ NUMBER
);
CREATE TABLE IF NOT EXISTS CORE.SO_SHIPMENT (
  WORLD_ID VARCHAR, SHIP_ID VARCHAR, LINE_ID VARCHAR, SHIP_ON DATE, QTY NUMBER(38,6), SHIPPED_ITEM_ID VARCHAR, FACILITY_ID VARCHAR, VISIBLE_AT TIMESTAMP_TZ
);
CREATE TABLE IF NOT EXISTS CORE.SO_DELIVERY_EVENT (
  WORLD_ID VARCHAR, EVENT_ID VARCHAR, LINE_ID VARCHAR, SHIPMENT_ID VARCHAR, KIND VARCHAR, EVENT_ON DATE, QTY NUMBER(38,6),
  LOCATION_ID VARCHAR, VISIBLE_AT TIMESTAMP_TZ, SEQ NUMBER
);
CREATE TABLE IF NOT EXISTS CORE.PROMISE_REVISION (
  WORLD_ID VARCHAR, LINE_ID VARCHAR, REVISION NUMBER, KIND VARCHAR, PROMISE_ON DATE, RECORDED_ON DATE, VISIBLE_AT TIMESTAMP_TZ
);
CREATE TABLE IF NOT EXISTS CORE.WORLD_FACILITY (WORLD_ID VARCHAR, FACILITY_ID VARCHAR, TIMEZONE VARCHAR, CALENDAR_ID VARCHAR, COUNTRY VARCHAR);
CREATE TABLE IF NOT EXISTS CORE.INVENTORY_SNAPSHOT (
  WORLD_ID VARCHAR, SNAPSHOT_ID VARCHAR, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, INVENTORY_CLASS VARCHAR, ON_HAND NUMBER(38,6),
  QUALITY_HOLD NUMBER(38,6), ALLOCATED NUMBER(38,6), IN_TRANSIT NUMBER(38,6), ERP_BOOK NUMBER(38,6), TAKEN_LOCAL TIMESTAMP_NTZ,
  VISIBLE_AT TIMESTAMP_TZ, SEQ NUMBER
);
CREATE TABLE IF NOT EXISTS CORE.DEMAND_EVENT (
  WORLD_ID VARCHAR, DEMAND_ID VARCHAR, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, INVENTORY_CLASS VARCHAR, DEMAND_ON DATE, QTY NUMBER(38,6),
  SOURCE VARCHAR, VISIBLE_AT TIMESTAMP_TZ
);
CREATE TABLE IF NOT EXISTS CORE.RECEIPT (
  WORLD_ID VARCHAR, RECEIPT_ID VARCHAR, LINE_ID VARCHAR, SUPPLIER_ID VARCHAR, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, ACCEPTED_QTY NUMBER(38,6),
  ACCEPTED_ON DATE, RECEIVED_ON DATE, INCOTERM VARCHAR, ORIGIN_COUNTRY VARCHAR, DEST_COUNTRY VARCHAR, CALENDAR_ID VARCHAR,
  VISIBLE_AT TIMESTAMP_TZ, SEQ NUMBER
);
CREATE TABLE IF NOT EXISTS CORE.COST_COMPONENT (
  WORLD_ID VARCHAR, COMPONENT_ID VARCHAR, RECEIPT_ID VARCHAR, KIND VARCHAR, OBLIGATION_VISIBLE_AT TIMESTAMP_TZ, AMOUNT_MINOR NUMBER(38,0),
  AMOUNT_VISIBLE_AT TIMESTAMP_TZ, CURRENCY VARCHAR, INVOICE_DATE DATE, ECONOMIC_DATE DATE, FX_RATE NUMBER(38,12), FX_VISIBLE_AT TIMESTAMP_TZ,
  CHARGEABLE_WEIGHT NUMBER(38,6), VOLUME NUMBER(38,6), ALLOCATION_POOL_ID VARCHAR, CUSTOMS_VALUE_MINOR NUMBER(38,0),
  MERCHANDISE_VALUE_MINOR NUMBER(38,0), BUYER_CHARGED BOOLEAN, SOURCE_DOCUMENT_ID VARCHAR, SEQ NUMBER
);
CREATE TABLE IF NOT EXISTS CORE.FX_RATE (CURRENCY VARCHAR, RATE_DATE DATE, USD_PER_UNIT NUMBER(38,12), VISIBLE_AT TIMESTAMP_TZ);
CREATE TABLE IF NOT EXISTS CORE.FEEDBACK (
  WORLD_ID VARCHAR, FEEDBACK_ID VARCHAR, LINE_ID VARCHAR, KIND VARCHAR, RATING NUMBER, QTY NUMBER(38,6), TEXT VARCHAR, FEEDBACK_ON DATE, VISIBLE_AT TIMESTAMP_TZ
);
CREATE TABLE IF NOT EXISTS CORE.PRODUCTION_ORDER (
  WORLD_ID VARCHAR, ORDER_ID VARCHAR, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, QTY NUMBER(38,6), START_ON DATE, COMPLETE_ON DATE,
  HOLD_QTY NUMBER(38,6), HOLD_RELEASE_ON DATE, VISIBLE_AT TIMESTAMP_TZ
);
CREATE TABLE IF NOT EXISTS CORE.PRODUCTION_CONSUMPTION (
  WORLD_ID VARCHAR, ISSUE_ID VARCHAR, ORDER_ID VARCHAR, COMPONENT_ID VARCHAR, FACILITY_ID VARCHAR,
  QTY NUMBER(38,6), ISSUED_ON DATE, LOT_ID VARCHAR, VISIBLE_AT TIMESTAMP_TZ
);
CREATE TABLE IF NOT EXISTS CORE.BOM (
  WORLD_ID VARCHAR, PARENT_ID VARCHAR, COMPONENT_ID VARCHAR, QTY_PER NUMBER(38,6), REVISION VARCHAR, VALID_FROM DATE, VALID_TO DATE
);
CREATE TABLE IF NOT EXISTS CORE.PROMISE_CONFLICT (
  WORLD_ID VARCHAR, LINE_ID VARCHAR, ERP_LATEST_PROMISE DATE, CRM_PROMISE DATE, ORIGINAL_PROMISE DATE, DETECTED_AT TIMESTAMP_TZ
);
CREATE TABLE IF NOT EXISTS CORE.RESOLUTION_CANDIDATE (
  SOURCE_SYSTEM VARCHAR, ENTITY_TYPE VARCHAR, SOURCE_KEY VARCHAR, CANDIDATE_ID VARCHAR, METHOD VARCHAR, SCORE NUMBER(9,4), STATUS VARCHAR
);
CREATE TABLE IF NOT EXISTS CORE.EVENT_LEDGER (
  EVENT_ID VARCHAR, EVENT_TYPE VARCHAR, ACTION VARCHAR, BIZ_STEP VARCHAR, DISPOSITION VARCHAR, EVENT_TIME TIMESTAMP_TZ, RECORD_TIME TIMESTAMP_TZ,
  EVENT_TIMEZONE VARCHAR, READ_POINT VARCHAR, ITEM_ID VARCHAR, QTY NUMBER(38,6), UOM VARCHAR, BIZ_TRANSACTION VARCHAR, SOURCE_PARTY VARCHAR,
  DESTINATION_PARTY VARCHAR, SOURCE_SYSTEM VARCHAR, SOURCE_RECORD_ID VARCHAR, ORIGIN VARCHAR, PAYLOAD VARIANT, APPENDED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_TZ
) COMMENT = 'Append-only EPCIS 2.0-inspired ledger. Not EPCIS certified.';
ALTER TABLE CORE.EVENT_LEDGER ADD COLUMN IF NOT EXISTS LOT_ID VARCHAR;
CREATE TABLE IF NOT EXISTS CORE.IOT_EVENT (
  EVENT_ID VARCHAR, SENSOR_ID VARCHAR, EVENT_TYPE VARCHAR, EVENT_TIME TIMESTAMP_TZ, TRUCK_ID VARCHAR,
  RECEIPT_ID VARCHAR, SHIPMENT_ID VARCHAR, LOT_ID VARCHAR, ITEM_ID VARCHAR, FACILITY_ID VARCHAR,
  TEMPERATURE_C NUMBER(9,3), VISIBLE_AT TIMESTAMP_TZ, ORIGIN VARCHAR
);
CREATE TABLE IF NOT EXISTS CORE.LOT_TRACE (
  LOT_ID VARCHAR, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, QTY NUMBER(38,6), SOURCE_TYPE VARCHAR,
  SOURCE_ID VARCHAR, EVENT_TIME TIMESTAMP_TZ, VISIBLE_AT TIMESTAMP_TZ, ORIGIN VARCHAR
);
CREATE TABLE IF NOT EXISTS CORE.KG_NODE (NODE_ID VARCHAR, NODE_TYPE VARCHAR, LABEL VARCHAR, PROPS VARIANT, ORIGIN VARCHAR);
CREATE TABLE IF NOT EXISTS CORE.KG_EDGE (
  EDGE_TYPE VARCHAR, SRC_ID VARCHAR, DST_ID VARCHAR, VALID_FROM DATE, VALID_TO DATE, RECORDED_AT TIMESTAMP_TZ, EVIDENCE_ID VARCHAR,
  ORIGIN VARCHAR, RESOLUTION_METHOD VARCHAR
);

-- ---------------------------------------------------------------- deterministic resolution for the product world
CREATE OR REPLACE PROCEDURE CORE.RESOLVE()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  started TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_TZ;
  run_id VARCHAR DEFAULT UUID_STRING();
  raw_rows NUMBER;
BEGIN
  SELECT COUNT(*) INTO :raw_rows FROM LAND.RAW_RECORD;

  CREATE OR REPLACE TEMPORARY TABLE CORE.R AS
    SELECT SOURCE_SYSTEM AS SYS, SOURCE_OBJECT AS OBJ, SOURCE_RECORD_ID AS RID, SOURCE_REVISION AS REV, VISIBLE_AT, PAYLOAD AS P, ORIGIN
    FROM LAND.RAW_RECORD;
  CREATE OR REPLACE TEMPORARY TABLE CORE.A AS SELECT SOURCE_SYSTEM, ENTITY_TYPE, SOURCE_KEY, CANONICAL_ID FROM GOV.SOURCE_ALIAS;

  -- FX
  DELETE FROM CORE.FX_RATE;
  INSERT INTO CORE.FX_RATE
    SELECT P:currency::VARCHAR, P:rate_date::DATE, P:usd_per_unit::NUMBER(38,12), VISIBLE_AT
    FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'FX_RATE'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV) = 1;

  DELETE FROM CORE.WORLD_FACILITY WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.WORLD_FACILITY SELECT 'MERIDIAN', FACILITY_ID, TIMEZONE, CALENDAR_ID, COUNTRY FROM GOV.FACILITY;

  -- Acceptances: MES ACCEPT and RELEASE dispositions, local plant date.
  CREATE OR REPLACE TEMPORARY TABLE CORE.DISP AS
    SELECT RID, P:receipt_ref::VARCHAR AS RECEIPT_ID, P:kind::VARCHAR AS KIND, P:qty::NUMBER(38,6) AS QTY,
           TRY_TO_TIMESTAMP_NTZ(P:local_ts::VARCHAR)::DATE AS ON_DAY, P:release_on::DATE AS RELEASE_ON, VISIBLE_AT
    FROM CORE.R WHERE SYS = 'MES' AND OBJ = 'DISPOSITION'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV) = 1;
  CREATE OR REPLACE TEMPORARY TABLE CORE.WRC AS
    SELECT r.RID AS RECEIPT_ID, r.P:po_ref::VARCHAR AS LINE_ID, ai.CANONICAL_ID AS ITEM_ID, af.CANONICAL_ID AS FACILITY_ID,
           r.P:qty::NUMBER(38,6) * u.FACTOR AS QTY, r.P:received_date::DATE AS RECEIVED_ON, r.VISIBLE_AT
    FROM CORE.R r
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'WMS' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = r.P:gtin::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'WMS' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = r.P:site::VARCHAR
    LEFT JOIN GOV.UOM_CONVERSION u ON u.ITEM_ID = ai.CANONICAL_ID AND u.FROM_UOM = r.P:uom::VARCHAR AND u.TO_UOM = 'EA'
    WHERE r.SYS = 'WMS' AND r.OBJ = 'RECEIPT'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.RID ORDER BY r.REV) = 1;

  DELETE FROM CORE.PO_ACCEPTANCE WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.PO_ACCEPTANCE
    SELECT 'MERIDIAN', d.RID, w.LINE_ID, d.RECEIPT_ID, d.ON_DAY, d.QTY, d.VISIBLE_AT, ROW_NUMBER() OVER (ORDER BY d.RID)
    FROM CORE.DISP d JOIN CORE.WRC w ON w.RECEIPT_ID = d.RECEIPT_ID
    WHERE d.KIND IN ('ACCEPT', 'RELEASE') AND d.QTY > 0;

  -- PO lines
  DELETE FROM CORE.PO_LINE WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.PO_LINE
    WITH po AS (
      SELECT RID, P, VISIBLE_AT FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'PO_LINE'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV DESC) = 1
    ), ack AS (
      SELECT RID, P:ack_date::DATE AS ACK_ON, P:promised_date::DATE AS ACK_PROMISE_ON, VISIBLE_AT
      FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'PO_ACK'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV) = 1
    ), cancel AS (
      SELECT RID, P:reason::VARCHAR AS REASON FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'PO_CANCEL'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV DESC) = 1
    ), disposed AS (
      SELECT DISTINCT RECEIPT_ID FROM CORE.DISP
    ), rc AS (
      SELECT w.LINE_ID, MIN(w.RECEIVED_ON) AS FIRST_RECEIPT_ON, BOOLOR_AGG(dd.RECEIPT_ID IS NULL) AS DISPOSITION_MISSING
      FROM CORE.WRC w LEFT JOIN disposed dd ON dd.RECEIPT_ID = w.RECEIPT_ID GROUP BY w.LINE_ID
    ), rej AS (
      SELECT w.LINE_ID, SUM(d.QTY) AS REJECTED FROM CORE.DISP d JOIN CORE.WRC w ON w.RECEIPT_ID = d.RECEIPT_ID
      WHERE d.KIND = 'SUPPLIER_REJECT' GROUP BY w.LINE_ID
    )
    SELECT 'MERIDIAN', po.RID, sup.CANONICAL_ID, itm.CANONICAL_ID, fac.CANONICAL_ID, f.TIMEZONE, f.CALENDAR_ID,
           po.P:qty::NUMBER(38,6) * u.FACTOR, CORE.PARSE_DATE(po.P:issued::VARCHAR), CORE.PARSE_DATE(po.P:requested::VARCHAR),
           ack.ACK_ON, ack.ACK_PROMISE_ON, ack.VISIBLE_AT, rc.FIRST_RECEIPT_ON, cancel.REASON, COALESCE(rej.REJECTED, 0), po.P:incoterm::VARCHAR,
           sup.CANONICAL_ID IS NOT NULL AND itm.CANONICAL_ID IS NOT NULL AND fac.CANONICAL_ID IS NOT NULL,
           u.FACTOR IS NOT NULL, f.TIMEZONE IS NOT NULL, COALESCE(rc.DISPOSITION_MISSING, FALSE), po.VISIBLE_AT,
           'ERP.PO_LINE:' || po.RID, ROW_NUMBER() OVER (ORDER BY po.RID)
    FROM po
    LEFT JOIN CORE.A sup ON sup.SOURCE_SYSTEM = 'ERP' AND sup.ENTITY_TYPE = 'SUPPLIER' AND sup.SOURCE_KEY = po.P:vendor_no::VARCHAR
    LEFT JOIN CORE.A itm ON itm.SOURCE_SYSTEM = 'ERP' AND itm.ENTITY_TYPE = 'ITEM' AND itm.SOURCE_KEY = po.P:material_no::VARCHAR
    LEFT JOIN CORE.A fac ON fac.SOURCE_SYSTEM = 'ERP' AND fac.ENTITY_TYPE = 'FACILITY' AND fac.SOURCE_KEY = po.P:plant_code::VARCHAR
    LEFT JOIN GOV.FACILITY f ON f.FACILITY_ID = fac.CANONICAL_ID
    LEFT JOIN GOV.UOM_CONVERSION u ON u.ITEM_ID = itm.CANONICAL_ID AND u.FROM_UOM = po.P:uom::VARCHAR AND u.TO_UOM = 'EA'
    LEFT JOIN ack ON ack.RID = po.RID
    LEFT JOIN cancel ON cancel.RID = po.RID
    LEFT JOIN rc ON rc.LINE_ID = po.RID
    LEFT JOIN rej ON rej.LINE_ID = po.RID;

  -- Receipts for landed cost: one accepted receipt per WMS receipt with accepted quantity.
  DELETE FROM CORE.RECEIPT WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.RECEIPT
    WITH acc AS (
      SELECT RECEIPT_ID, SUM(QTY) AS QTY, MIN(ACCEPTED_ON) AS ACCEPTED_ON, MAX(VISIBLE_AT) AS VISIBLE_AT
      FROM CORE.PO_ACCEPTANCE WHERE WORLD_ID = 'MERIDIAN' GROUP BY RECEIPT_ID
    )
    SELECT 'MERIDIAN', w.RECEIPT_ID, w.LINE_ID, l.SUPPLIER_ID, w.ITEM_ID, w.FACILITY_ID, acc.QTY, acc.ACCEPTED_ON, w.RECEIVED_ON,
           l.INCOTERM, s.COUNTRY, f.COUNTRY, f.CALENDAR_ID, GREATEST(w.VISIBLE_AT, acc.VISIBLE_AT), ROW_NUMBER() OVER (ORDER BY w.RECEIPT_ID)
    FROM CORE.WRC w JOIN acc ON acc.RECEIPT_ID = w.RECEIPT_ID
    LEFT JOIN CORE.PO_LINE l ON l.WORLD_ID = 'MERIDIAN' AND l.LINE_ID = w.LINE_ID
    LEFT JOIN GOV.PARTY s ON s.PARTY_ID = l.SUPPLIER_ID
    LEFT JOIN GOV.FACILITY f ON f.FACILITY_ID = w.FACILITY_ID;

  -- Cost components: first revision = obligation visibility; first revision with an amount = amount visibility.
  DELETE FROM CORE.COST_COMPONENT WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.COST_COMPONENT
    WITH ap AS (
      SELECT RID, P, VISIBLE_AT, REV FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'AP_DOC'
    ), doc AS (
      SELECT RID,
             MIN(VISIBLE_AT) AS OBLIGATION_VISIBLE_AT,
             MIN_BY(P, REV) AS P0,
             MIN_BY(P, IFF(P:amount IS NOT NULL AND NOT IS_NULL_VALUE(P:amount), REV, NULL)) AS PA,
             MIN(IFF(P:amount IS NOT NULL AND NOT IS_NULL_VALUE(P:amount), VISIBLE_AT, NULL)) AS AMOUNT_VISIBLE_AT
      FROM ap GROUP BY RID
    ), fr AS (
      SELECT RID, MIN(VISIBLE_AT) AS OBLIGATION_VISIBLE_AT, MIN_BY(P, REV) AS P0,
             MIN_BY(P, IFF(P:amount IS NOT NULL AND NOT IS_NULL_VALUE(P:amount), REV, NULL)) AS PA,
             MIN(IFF(P:amount IS NOT NULL AND NOT IS_NULL_VALUE(P:amount), VISIBLE_AT, NULL)) AS AMOUNT_VISIBLE_AT
      FROM CORE.R WHERE SYS = 'TMS' AND OBJ = 'FREIGHT_INVOICE' GROUP BY RID
    ), comps AS (
      SELECT doc.RID AS COMPONENT_ID, doc.P0:receipt_ref::VARCHAR AS RECEIPT_ID, doc.P0:doc_type::VARCHAR AS KIND, doc.OBLIGATION_VISIBLE_AT,
             CORE.MINOR(doc.PA:amount::VARCHAR) AS AMOUNT_MINOR, doc.AMOUNT_VISIBLE_AT, doc.P0:currency::VARCHAR AS CURRENCY,
             doc.P0:doc_date::DATE AS INVOICE_DATE, doc.P0:economic_date::DATE AS ECONOMIC_DATE,
             NULL::NUMBER(38,6) AS CHARGEABLE_WEIGHT, NULL::NUMBER(38,6) AS VOLUME, NULL::VARCHAR AS POOL_ID,
             CORE.MINOR(doc.P0:customs_value::VARCHAR) AS CUSTOMS_VALUE_MINOR, CORE.MINOR(doc.P0:merchandise_value::VARCHAR) AS MERCHANDISE_VALUE_MINOR,
             doc.P0:buyer_charged::BOOLEAN AS BUYER_CHARGED, doc.RID AS DOC_ID
      FROM doc
      UNION ALL
      SELECT fr.RID || ':' || m.value:receipt_ref::VARCHAR, m.value:receipt_ref::VARCHAR, 'FREIGHT', fr.OBLIGATION_VISIBLE_AT,
             CORE.MINOR(fr.PA:amount::VARCHAR), fr.AMOUNT_VISIBLE_AT, fr.P0:currency::VARCHAR, fr.P0:invoice_date::DATE, fr.P0:invoice_date::DATE,
             m.value:chargeable_weight_kg::NUMBER(38,6), m.value:volume_m3::NUMBER(38,6), fr.RID, NULL, NULL, FALSE, fr.RID
      FROM fr, LATERAL FLATTEN(fr.P0:members) m
    )
    SELECT 'MERIDIAN', c.COMPONENT_ID, c.RECEIPT_ID, c.KIND, c.OBLIGATION_VISIBLE_AT, c.AMOUNT_MINOR, c.AMOUNT_VISIBLE_AT, c.CURRENCY,
           c.INVOICE_DATE, c.ECONOMIC_DATE,
           IFF(c.CURRENCY = 'USD', 1, fx.USD_PER_UNIT), IFF(c.CURRENCY = 'USD', '1970-01-01T00:00:00Z'::TIMESTAMP_TZ, fx.VISIBLE_AT),
           c.CHARGEABLE_WEIGHT, c.VOLUME, c.POOL_ID, c.CUSTOMS_VALUE_MINOR, c.MERCHANDISE_VALUE_MINOR, COALESCE(c.BUYER_CHARGED, FALSE), c.DOC_ID,
           ROW_NUMBER() OVER (ORDER BY c.COMPONENT_ID)
    FROM comps c
    LEFT JOIN CORE.FX_RATE fx ON fx.CURRENCY = c.CURRENCY
      AND fx.RATE_DATE = IFF(c.KIND = 'MERCHANDISE', c.INVOICE_DATE, c.ECONOMIC_DATE);

  -- Sales lines
  CREATE OR REPLACE TEMPORARY TABLE CORE.TMS AS
    SELECT RID, P:so_ref::VARCHAR AS LINE_ID, P:shipment_ref::VARCHAR AS SHIPMENT_ID, P:event_type::VARCHAR AS KIND,
           P:qty::NUMBER(38,6) AS QTY, P:tz::VARCHAR AS TZ, TRY_TO_TIMESTAMP_NTZ(P:local_ts::VARCHAR)::DATE AS EVENT_ON,
           P:location::VARCHAR AS LOCATION, VISIBLE_AT
    FROM CORE.R WHERE SYS = 'TMS' AND OBJ = 'DELIVERY_EVENT'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV) = 1;
  CREATE OR REPLACE TEMPORARY TABLE CORE.SHIP AS
    SELECT r.RID, r.P:so_ref::VARCHAR AS LINE_ID, r.P:ship_date::DATE AS SHIP_ON, r.P:qty::NUMBER(38,6) * u.FACTOR AS QTY,
           ai.CANONICAL_ID AS SHIPPED_ITEM_ID, af.CANONICAL_ID AS FACILITY_ID, r.VISIBLE_AT
    FROM CORE.R r
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'WMS' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = r.P:gtin::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'WMS' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = r.P:site::VARCHAR
    LEFT JOIN GOV.UOM_CONVERSION u ON u.ITEM_ID = ai.CANONICAL_ID AND u.FROM_UOM = r.P:uom::VARCHAR AND u.TO_UOM = 'EA'
    WHERE r.SYS = 'WMS' AND r.OBJ = 'SHIP_CONFIRM'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.RID ORDER BY r.REV) = 1;

  DELETE FROM CORE.SO_LINE WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.SO_LINE
    WITH so AS (
      SELECT RID, P, VISIBLE_AT FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'SO_LINE'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV DESC) = 1
    ), original AS (
      SELECT RID, P:promise_date::DATE AS PROMISE_ON FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'SO_PROMISE' AND P:kind::VARCHAR = 'ORIGINAL'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV) = 1
    ), change AS (
      SELECT RID,
             MAX(IFF(P:change_type::VARCHAR = 'CUSTOMER_CANCEL', 'CUSTOMER_BEFORE_PICK', IFF(P:change_type::VARCHAR = 'COMPANY_CANCEL', 'COMPANY', NULL))) AS CANCELLATION,
             MAX(IFF(P:change_type::VARCHAR = 'SHORT_CLOSE', P:qty::NUMBER(38,6), NULL)) AS SHORT_QTY,
             MAX(IFF(P:change_type::VARCHAR = 'SHORT_CLOSE', P:approved_on::DATE, NULL)) AS SHORT_ON
      FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'SO_CHANGE' GROUP BY RID
    ), hold AS (
      SELECT RID, P:start::DATE AS HS, P:end::DATE AS HE, P:recorded::DATE AS HR FROM CORE.R WHERE SYS = 'CRM' AND OBJ = 'CUSTOMER_HOLD'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV DESC) = 1
    ), tz_gap AS (
      SELECT DISTINCT LINE_ID FROM CORE.TMS WHERE TZ IS NULL OR TZ = ''
    ), resolved AS (
      SELECT so.RID, so.P, so.VISIBLE_AT, cus.CANONICAL_ID AS CUSTOMER_ID, st.CANONICAL_ID AS SHIP_TO_ID, itm.CANONICAL_ID AS ITEM_ID,
             fac.CANONICAL_ID AS FACILITY_ID, u.FACTOR
      FROM so
      LEFT JOIN CORE.A cus ON cus.SOURCE_SYSTEM = 'ERP' AND cus.ENTITY_TYPE = 'CUSTOMER' AND cus.SOURCE_KEY = so.P:customer_no::VARCHAR
      LEFT JOIN CORE.A st ON st.SOURCE_SYSTEM = 'ERP' AND st.ENTITY_TYPE = 'SHIP_TO' AND st.SOURCE_KEY = so.P:ship_to_no::VARCHAR
      LEFT JOIN CORE.A itm ON itm.SOURCE_SYSTEM = 'ERP' AND itm.ENTITY_TYPE = 'ITEM' AND itm.SOURCE_KEY = so.P:material_no::VARCHAR
      LEFT JOIN CORE.A fac ON fac.SOURCE_SYSTEM = 'ERP' AND fac.ENTITY_TYPE = 'FACILITY' AND fac.SOURCE_KEY = so.P:ship_from::VARCHAR
      LEFT JOIN GOV.UOM_CONVERSION u ON u.ITEM_ID = itm.CANONICAL_ID AND u.FROM_UOM = so.P:uom::VARCHAR AND u.TO_UOM = 'EA'
    ), sub AS (
      SELECT s.LINE_ID FROM CORE.SHIP s JOIN resolved r ON r.RID = s.LINE_ID
      WHERE s.SHIPPED_ITEM_ID <> r.ITEM_ID
        AND NOT EXISTS (SELECT 1 FROM GOV.SUBSTITUTION g WHERE g.ITEM_ID = r.ITEM_ID AND g.SUBSTITUTE_ITEM_ID = s.SHIPPED_ITEM_ID)
      GROUP BY s.LINE_ID
    )
    SELECT 'MERIDIAN', r.RID, r.CUSTOMER_ID, r.SHIP_TO_ID, r.ITEM_ID, r.FACILITY_ID, st.GEOGRAPHY_ID,
           IFF(tz_gap.LINE_ID IS NOT NULL, NULL, IFF(r.P:incoterm::VARCHAR IN ('EXW', 'FCA'), f.TIMEZONE, st.TIMEZONE)),
           IFF(r.P:incoterm::VARCHAR IN ('EXW', 'FCA'), f.CALENDAR_ID, st.CALENDAR_ID),
           r.P:incoterm::VARCHAR, r.P:qty::NUMBER(38,6) * r.FACTOR, r.P:order_date::DATE, CORE.PARSE_DATE(r.P:requested_ship::VARCHAR),
           original.PROMISE_ON, change.CANCELLATION, IFF(sub.LINE_ID IS NOT NULL, 'SILENT', NULL), hold.HS, hold.HE, hold.HR,
           change.SHORT_QTY, change.SHORT_ON,
           r.CUSTOMER_ID IS NOT NULL AND r.SHIP_TO_ID IS NOT NULL AND r.ITEM_ID IS NOT NULL AND r.FACILITY_ID IS NOT NULL,
           r.FACTOR IS NOT NULL, r.VISIBLE_AT, 'ERP.SO_LINE:' || r.RID, ROW_NUMBER() OVER (ORDER BY r.RID)
    FROM resolved r
    LEFT JOIN GOV.SHIP_TO st ON st.SHIP_TO_ID = r.SHIP_TO_ID
    LEFT JOIN GOV.FACILITY f ON f.FACILITY_ID = r.FACILITY_ID
    LEFT JOIN original ON original.RID = r.RID
    LEFT JOIN change ON change.RID = r.RID
    LEFT JOIN hold ON hold.RID = r.RID
    LEFT JOIN tz_gap ON tz_gap.LINE_ID = r.RID
    LEFT JOIN sub ON sub.LINE_ID = r.RID;

  DELETE FROM CORE.SO_SHIPMENT WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.SO_SHIPMENT SELECT 'MERIDIAN', RID, LINE_ID, SHIP_ON, QTY, SHIPPED_ITEM_ID, FACILITY_ID, VISIBLE_AT FROM CORE.SHIP;

  DELETE FROM CORE.SO_DELIVERY_EVENT WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.SO_DELIVERY_EVENT
    SELECT 'MERIDIAN', RID, LINE_ID, SHIPMENT_ID, KIND, EVENT_ON, QTY, LOCATION, VISIBLE_AT, ROW_NUMBER() OVER (ORDER BY RID)
    FROM CORE.TMS WHERE TZ IS NOT NULL AND TZ <> '';

  DELETE FROM CORE.PROMISE_REVISION WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.PROMISE_REVISION
    SELECT 'MERIDIAN', RID, REV, P:kind::VARCHAR, P:promise_date::DATE, P:recorded_on::DATE, VISIBLE_AT
    FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'SO_PROMISE';

  DELETE FROM CORE.PROMISE_CONFLICT WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.PROMISE_CONFLICT
    SELECT 'MERIDIAN', c.RID, MAX_BY(p.PROMISE_ON, p.REVISION), c.P:promise_date::DATE, MIN_BY(p.PROMISE_ON, p.REVISION), CURRENT_TIMESTAMP()::TIMESTAMP_TZ
    FROM CORE.R c JOIN CORE.PROMISE_REVISION p ON p.WORLD_ID = 'MERIDIAN' AND p.LINE_ID = c.RID
    WHERE c.SYS = 'CRM' AND c.OBJ = 'PROMISE_CURRENT'
    GROUP BY c.RID, c.P;

  -- Inventory snapshots and demand
  DELETE FROM CORE.INVENTORY_SNAPSHOT WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.INVENTORY_SNAPSHOT
    WITH book AS (
      SELECT RID, P:book_qty::NUMBER(38,6) AS BOOK FROM CORE.R WHERE SYS = 'ERP' AND OBJ = 'BOOK_STOCK'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY RID ORDER BY REV DESC) = 1
    )
    SELECT 'MERIDIAN', r.RID, ai.CANONICAL_ID, af.CANONICAL_ID, i.INVENTORY_CLASS, r.P:on_hand::NUMBER(38,6), r.P:hold::NUMBER(38,6),
           r.P:allocated::NUMBER(38,6), r.P:in_transit::NUMBER(38,6), COALESCE(book.BOOK, r.P:on_hand::NUMBER(38,6)),
           TRY_TO_TIMESTAMP_NTZ(r.P:taken_local::VARCHAR), r.VISIBLE_AT, ROW_NUMBER() OVER (ORDER BY r.RID)
    FROM CORE.R r
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'WMS' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = r.P:gtin::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'WMS' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = r.P:site::VARCHAR
    LEFT JOIN GOV.ITEM i ON i.ITEM_ID = ai.CANONICAL_ID
    LEFT JOIN book ON book.RID = r.RID
    WHERE r.SYS = 'WMS' AND r.OBJ = 'SNAPSHOT'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.RID ORDER BY r.REV DESC) = 1;

  DELETE FROM CORE.DEMAND_EVENT WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.DEMAND_EVENT
    SELECT 'MERIDIAN', s.RID, s.SHIPPED_ITEM_ID, s.FACILITY_ID, i.INVENTORY_CLASS, s.SHIP_ON, s.QTY, 'WMS.SHIP_CONFIRM', s.VISIBLE_AT
    FROM CORE.SHIP s JOIN GOV.ITEM i ON i.ITEM_ID = s.SHIPPED_ITEM_ID
    UNION ALL
    SELECT 'MERIDIAN', r.RID, ai.CANONICAL_ID, af.CANONICAL_ID, i.INVENTORY_CLASS, TRY_TO_TIMESTAMP_NTZ(r.P:issued_local::VARCHAR)::DATE,
           r.P:qty::NUMBER(38,6), 'MES.MATERIAL_ISSUE', r.VISIBLE_AT
    FROM CORE.R r
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'MES' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = r.P:component::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'MES' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = r.P:plant::VARCHAR
    LEFT JOIN GOV.ITEM i ON i.ITEM_ID = ai.CANONICAL_ID
    WHERE r.SYS = 'MES' AND r.OBJ = 'MATERIAL_ISSUE'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.RID ORDER BY r.REV DESC) = 1;

  DELETE FROM CORE.PRODUCTION_CONSUMPTION WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.PRODUCTION_CONSUMPTION
    SELECT 'MERIDIAN', r.RID, r.P:wo_no::VARCHAR, ai.CANONICAL_ID, af.CANONICAL_ID,
           r.P:qty::NUMBER(38,6), TRY_TO_TIMESTAMP_NTZ(r.P:issued_local::VARCHAR)::DATE,
           'LOT-C-' || r.RID, r.VISIBLE_AT
    FROM CORE.R r
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'MES' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = r.P:component::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'MES' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = r.P:plant::VARCHAR
    WHERE r.SYS = 'MES' AND r.OBJ = 'MATERIAL_ISSUE'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.RID ORDER BY r.REV DESC) = 1;

  -- IoT gate/temperature telemetry and lot genealogy. IoT confirms operational events; metric commitment clocks
  -- remain governed by ERP/WMS/TMS contracts.
  DELETE FROM CORE.IOT_EVENT;
  INSERT INTO CORE.IOT_EVENT
    SELECT r.RID, r.P:sensor_id::VARCHAR, r.P:event_type::VARCHAR, r.P:event_ts::TIMESTAMP_TZ,
           r.P:truck_id::VARCHAR, r.P:receipt_ref::VARCHAR, r.P:shipment_ref::VARCHAR, r.P:lot_id::VARCHAR,
           ai.CANONICAL_ID, af.CANONICAL_ID, r.P:temperature_c::NUMBER(9,3), r.VISIBLE_AT, r.ORIGIN
    FROM CORE.R r
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'IOT' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = r.P:gtin::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'IOT' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = r.P:site::VARCHAR
    WHERE r.SYS = 'IOT' AND r.OBJ = 'DOCK_SENSOR'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.RID ORDER BY r.REV DESC) = 1;

  DELETE FROM CORE.LOT_TRACE;
  INSERT INTO CORE.LOT_TRACE
    SELECT r.P:lot_id::VARCHAR, ai.CANONICAL_ID, af.CANONICAL_ID, r.P:qty::NUMBER(38,6) * u.FACTOR,
           'RECEIPT', r.RID, r.P:received_date::TIMESTAMP_TZ, r.VISIBLE_AT, r.ORIGIN
    FROM CORE.R r
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'WMS' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = r.P:gtin::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'WMS' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = r.P:site::VARCHAR
    LEFT JOIN GOV.UOM_CONVERSION u ON u.ITEM_ID = ai.CANONICAL_ID AND u.FROM_UOM = r.P:uom::VARCHAR AND u.TO_UOM = 'EA'
    WHERE r.SYS = 'WMS' AND r.OBJ = 'RECEIPT'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.RID ORDER BY r.REV DESC) = 1;
  INSERT INTO CORE.LOT_TRACE
    SELECT r.P:lot_id::VARCHAR, ai.CANONICAL_ID, af.CANONICAL_ID, r.P:qty::NUMBER(38,6) * u.FACTOR,
           'SHIPMENT', r.RID, r.P:ship_date::TIMESTAMP_TZ, r.VISIBLE_AT, r.ORIGIN
    FROM CORE.R r
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'WMS' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = r.P:gtin::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'WMS' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = r.P:site::VARCHAR
    LEFT JOIN GOV.UOM_CONVERSION u ON u.ITEM_ID = ai.CANONICAL_ID AND u.FROM_UOM = r.P:uom::VARCHAR AND u.TO_UOM = 'EA'
    WHERE r.SYS = 'WMS' AND r.OBJ = 'SHIP_CONFIRM'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.RID ORDER BY r.REV DESC) = 1;
  INSERT INTO CORE.LOT_TRACE
    SELECT LOT_ID, COMPONENT_ID, FACILITY_ID, QTY, 'CONSUMPTION', ORDER_ID, ISSUED_ON::TIMESTAMP_TZ, VISIBLE_AT, 'SYNTHETIC_MES'
    FROM CORE.PRODUCTION_CONSUMPTION WHERE WORLD_ID = 'MERIDIAN';

  -- Production, BOM, feedback
  DELETE FROM CORE.PRODUCTION_ORDER WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.PRODUCTION_ORDER
    SELECT 'MERIDIAN', w.RID, ai.CANONICAL_ID, af.CANONICAL_ID, w.P:qty::NUMBER(38,6), w.P:start::DATE, w.P:complete::DATE,
           h.P:qty::NUMBER(38,6), h.P:release::DATE, w.VISIBLE_AT
    FROM CORE.R w
    LEFT JOIN CORE.R h ON h.SYS = 'MES' AND h.OBJ = 'PRODUCTION_HOLD' AND h.RID = w.RID
    LEFT JOIN CORE.A ai ON ai.SOURCE_SYSTEM = 'MES' AND ai.ENTITY_TYPE = 'ITEM' AND ai.SOURCE_KEY = w.P:item::VARCHAR
    LEFT JOIN CORE.A af ON af.SOURCE_SYSTEM = 'MES' AND af.ENTITY_TYPE = 'FACILITY' AND af.SOURCE_KEY = w.P:plant::VARCHAR
    WHERE w.SYS = 'MES' AND w.OBJ = 'WORK_ORDER'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY w.RID ORDER BY w.REV DESC) = 1;

  DELETE FROM CORE.BOM WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.BOM
    SELECT DISTINCT 'MERIDIAN', ap.CANONICAL_ID, ac.CANONICAL_ID, r.P:qty_per::NUMBER(38,6), r.P:revision::VARCHAR, r.P:valid_from::DATE, r.P:valid_to::DATE
    FROM CORE.R r
    LEFT JOIN CORE.A ap ON ap.SOURCE_SYSTEM = 'MES' AND ap.ENTITY_TYPE = 'ITEM' AND ap.SOURCE_KEY = r.P:parent::VARCHAR
    LEFT JOIN CORE.A ac ON ac.SOURCE_SYSTEM = 'MES' AND ac.ENTITY_TYPE = 'ITEM' AND ac.SOURCE_KEY = r.P:component::VARCHAR
    WHERE r.SYS = 'MES' AND r.OBJ = 'BOM_LINE';

  DELETE FROM CORE.FEEDBACK WHERE WORLD_ID = 'MERIDIAN';
  INSERT INTO CORE.FEEDBACK
    SELECT 'MERIDIAN', OBJ || ':' || RID, P:so_ref::VARCHAR, OBJ, P:rating::NUMBER, P:qty::NUMBER(38,6), COALESCE(P:comment::VARCHAR, P:text::VARCHAR),
           COALESCE(P:rated_on::DATE, P:returned_on::DATE, P:opened_on::DATE), VISIBLE_AT
    FROM CORE.R WHERE SYS = 'CRM' AND OBJ IN ('RATING', 'RETURN', 'COMPLAINT')
    QUALIFY ROW_NUMBER() OVER (PARTITION BY OBJ, RID ORDER BY REV DESC) = 1;

  -- Quarantine (append-only, one row per record and reason)
  MERGE INTO LAND.QUARANTINE q USING (
    SELECT 'TMS' AS SYS, 'DELIVERY_EVENT' AS OBJ, RID, 1 AS REV, 'TIMEZONE_MISSING' AS REASON, 'Carrier event without timezone; local completion date unknowable.' AS DETAIL, VISIBLE_AT
    FROM CORE.TMS WHERE TZ IS NULL OR TZ = ''
    UNION ALL
    SELECT 'ERP', 'PO_LINE', LINE_ID, 1, IFF(IDENTITY_RESOLVED = FALSE, 'IDENTITY_UNRESOLVED', 'UOM_UNRESOLVED'), 'No administered alias or governed unit conversion.', VISIBLE_AT
    FROM CORE.PO_LINE WHERE WORLD_ID = 'MERIDIAN' AND (IDENTITY_RESOLVED = FALSE OR UOM_RESOLVED = FALSE)
    UNION ALL
    SELECT 'ERP', 'SO_LINE', LINE_ID, 1, IFF(IDENTITY_RESOLVED = FALSE, 'IDENTITY_UNRESOLVED', 'UOM_UNRESOLVED'), 'No administered alias or governed unit conversion.', VISIBLE_AT
    FROM CORE.SO_LINE WHERE WORLD_ID = 'MERIDIAN' AND (IDENTITY_RESOLVED = FALSE OR UOM_RESOLVED = FALSE)
  ) s ON q.SOURCE_SYSTEM = s.SYS AND q.SOURCE_OBJECT = s.OBJ AND q.SOURCE_RECORD_ID = s.RID AND q.REASON = s.REASON
  WHEN NOT MATCHED THEN INSERT (SOURCE_SYSTEM, SOURCE_OBJECT, SOURCE_RECORD_ID, SOURCE_REVISION, REASON, DETAIL, VISIBLE_AT)
    VALUES (s.SYS, s.OBJ, s.RID, s.REV, s.REASON, s.DETAIL, s.VISIBLE_AT);

  -- Steward candidates for unmapped keys. Candidates never publish SAME_AS.
  DELETE FROM CORE.RESOLUTION_CANDIDATE;
  INSERT INTO CORE.RESOLUTION_CANDIDATE
    WITH unmapped AS (
      SELECT DISTINCT 'ERP' AS SYS, 'SUPPLIER' AS ET, P:vendor_no::VARCHAR AS K FROM CORE.R
      WHERE SYS = 'ERP' AND OBJ = 'PO_LINE' AND P:vendor_no::VARCHAR NOT IN (SELECT SOURCE_KEY FROM CORE.A WHERE SOURCE_SYSTEM = 'ERP' AND ENTITY_TYPE = 'SUPPLIER')
      UNION
      SELECT DISTINCT 'ERP', 'SHIP_TO', P:ship_to_no::VARCHAR FROM CORE.R
      WHERE SYS = 'ERP' AND OBJ = 'SO_LINE' AND P:ship_to_no::VARCHAR NOT IN (SELECT SOURCE_KEY FROM CORE.A WHERE SOURCE_SYSTEM = 'ERP' AND ENTITY_TYPE = 'SHIP_TO')
    )
    SELECT u.SYS, u.ET, u.K, a.CANONICAL_ID, 'EDIT_DISTANCE', 1 - EDITDISTANCE(u.K, a.SOURCE_KEY) / GREATEST(LENGTH(u.K), LENGTH(a.SOURCE_KEY)), 'CANDIDATE_ONLY'
    FROM unmapped u JOIN CORE.A a ON a.SOURCE_SYSTEM = u.SYS AND a.ENTITY_TYPE = u.ET
    QUALIFY ROW_NUMBER() OVER (PARTITION BY u.K ORDER BY EDITDISTANCE(u.K, a.SOURCE_KEY), a.CANONICAL_ID) = 1;

  -- Event ledger: append new events only.
  MERGE INTO CORE.EVENT_LEDGER e USING (
    SELECT 'RCV:' || w.RECEIPT_ID AS EVENT_ID, 'ObjectEvent' AS EVENT_TYPE, 'OBSERVE' AS ACTION, 'receiving' AS BIZ_STEP, 'in_progress' AS DISPOSITION,
           w.RECEIVED_ON::TIMESTAMP_TZ AS EVENT_TIME, w.VISIBLE_AT AS RECORD_TIME, f.TIMEZONE AS TZ, w.FACILITY_ID AS READ_POINT, w.ITEM_ID, w.QTY,
           'PO:' || w.LINE_ID AS BIZ_TX, l.SUPPLIER_ID AS SRC_PARTY, w.FACILITY_ID AS DST_PARTY, 'WMS' AS SYS, w.RECEIPT_ID AS RID
    FROM CORE.WRC w LEFT JOIN GOV.FACILITY f ON f.FACILITY_ID = w.FACILITY_ID
    LEFT JOIN CORE.PO_LINE l ON l.WORLD_ID = 'MERIDIAN' AND l.LINE_ID = w.LINE_ID
    UNION ALL
    SELECT 'QD:' || d.RID, 'ObjectEvent', 'OBSERVE', 'inspecting',
           CASE d.KIND WHEN 'ACCEPT' THEN 'conformant' WHEN 'RELEASE' THEN 'conformant' WHEN 'SUPPLIER_REJECT' THEN 'non_conformant'
                       ELSE 'non_sellable_other' END,
           d.ON_DAY::TIMESTAMP_TZ, d.VISIBLE_AT, f.TIMEZONE, w.FACILITY_ID, w.ITEM_ID, d.QTY, 'PO:' || w.LINE_ID, NULL, w.FACILITY_ID, 'MES', d.RID
    FROM CORE.DISP d JOIN CORE.WRC w ON w.RECEIPT_ID = d.RECEIPT_ID LEFT JOIN GOV.FACILITY f ON f.FACILITY_ID = w.FACILITY_ID
    UNION ALL
    SELECT 'SHP:' || s.RID, 'ObjectEvent', 'OBSERVE', 'shipping', 'in_transit', s.SHIP_ON::TIMESTAMP_TZ, s.VISIBLE_AT, f.TIMEZONE, s.FACILITY_ID,
           s.SHIPPED_ITEM_ID, s.QTY, 'SO:' || s.LINE_ID, s.FACILITY_ID, NULL, 'WMS', s.RID
    FROM CORE.SHIP s LEFT JOIN GOV.FACILITY f ON f.FACILITY_ID = s.FACILITY_ID
    UNION ALL
    SELECT 'DLV:' || t.RID, 'ObjectEvent', 'OBSERVE', CASE t.KIND WHEN 'POD' THEN 'receiving' WHEN 'READY' THEN 'staging_outbound' ELSE 'arriving' END,
           CASE t.KIND WHEN 'POD' THEN 'completeness_verified' WHEN 'READY' THEN 'available' ELSE 'in_transit' END,
           t.EVENT_ON::TIMESTAMP_TZ, t.VISIBLE_AT, t.TZ, t.LOCATION, NULL, t.QTY, 'SO:' || t.LINE_ID, NULL, t.LOCATION, 'TMS', t.RID
    FROM CORE.TMS t
  ) s ON e.EVENT_ID = s.EVENT_ID
  WHEN NOT MATCHED THEN INSERT (EVENT_ID, EVENT_TYPE, ACTION, BIZ_STEP, DISPOSITION, EVENT_TIME, RECORD_TIME, EVENT_TIMEZONE, READ_POINT, ITEM_ID, QTY, UOM,
                                BIZ_TRANSACTION, SOURCE_PARTY, DESTINATION_PARTY, SOURCE_SYSTEM, SOURCE_RECORD_ID, ORIGIN)
    VALUES (s.EVENT_ID, s.EVENT_TYPE, s.ACTION, s.BIZ_STEP, s.DISPOSITION, s.EVENT_TIME, s.RECORD_TIME, s.TZ, s.READ_POINT, s.ITEM_ID, s.QTY, 'EA',
            s.BIZ_TX, s.SRC_PARTY, s.DST_PARTY, s.SYS, s.RID, 'SYNTHETIC_' || s.SYS);

  MERGE INTO CORE.EVENT_LEDGER e USING (
    SELECT 'IOT:' || EVENT_ID AS EVENT_ID, EVENT_TIME, VISIBLE_AT, FACILITY_ID, ITEM_ID, LOT_ID,
           IFF(RECEIPT_ID IS NOT NULL, 'PO_RECEIPT:' || RECEIPT_ID, 'SO_SHIPMENT:' || SHIPMENT_ID) AS BIZ_TX,
           EVENT_TYPE, SENSOR_ID, TRUCK_ID, TEMPERATURE_C
    FROM CORE.IOT_EVENT
  ) s ON e.EVENT_ID = s.EVENT_ID
  WHEN NOT MATCHED THEN INSERT (
    EVENT_ID, EVENT_TYPE, ACTION, BIZ_STEP, DISPOSITION, EVENT_TIME, RECORD_TIME, EVENT_TIMEZONE, READ_POINT,
    ITEM_ID, QTY, UOM, BIZ_TRANSACTION, SOURCE_PARTY, DESTINATION_PARTY, SOURCE_SYSTEM, SOURCE_RECORD_ID,
    ORIGIN, PAYLOAD, LOT_ID
  ) VALUES (
    s.EVENT_ID, 'SensorEvent', 'OBSERVE', IFF(s.EVENT_TYPE = 'TRUCK_ARRIVAL', 'arriving', 'departing'),
    'in_transit', s.EVENT_TIME, s.VISIBLE_AT, 'UTC', s.FACILITY_ID, s.ITEM_ID, NULL, 'EA', s.BIZ_TX,
    s.TRUCK_ID, s.FACILITY_ID, 'IOT', s.SENSOR_ID, 'SYNTHETIC_IOT',
    OBJECT_CONSTRUCT('sensor_id', s.SENSOR_ID, 'event_type', s.EVENT_TYPE, 'temperature_c', s.TEMPERATURE_C), s.LOT_ID
  );

  CALL CORE.BUILD_GRAPH();

  INSERT INTO GOV.PIPELINE_RUN SELECT :run_id, :started, CURRENT_TIMESTAMP()::TIMESTAMP_TZ, 'CORE.RESOLVE', 'SUCCEEDED', :raw_rows,
    (SELECT COUNT(*) FROM CORE.PO_LINE WHERE WORLD_ID = 'MERIDIAN') + (SELECT COUNT(*) FROM CORE.SO_LINE WHERE WORLD_ID = 'MERIDIAN'),
    OBJECT_CONSTRUCT('po_lines', (SELECT COUNT(*) FROM CORE.PO_LINE WHERE WORLD_ID = 'MERIDIAN'),
                     'so_lines', (SELECT COUNT(*) FROM CORE.SO_LINE WHERE WORLD_ID = 'MERIDIAN'),
                     'receipts', (SELECT COUNT(*) FROM CORE.RECEIPT WHERE WORLD_ID = 'MERIDIAN'),
                     'quarantine', (SELECT COUNT(*) FROM LAND.QUARANTINE));
  RETURN OBJECT_CONSTRUCT('run_id', :run_id, 'raw_rows', :raw_rows,
    'po_lines', (SELECT COUNT(*) FROM CORE.PO_LINE WHERE WORLD_ID = 'MERIDIAN'),
    'so_lines', (SELECT COUNT(*) FROM CORE.SO_LINE WHERE WORLD_ID = 'MERIDIAN'),
    'receipts', (SELECT COUNT(*) FROM CORE.RECEIPT WHERE WORLD_ID = 'MERIDIAN'),
    'cost_components', (SELECT COUNT(*) FROM CORE.COST_COMPONENT WHERE WORLD_ID = 'MERIDIAN'),
    'snapshots', (SELECT COUNT(*) FROM CORE.INVENTORY_SNAPSHOT WHERE WORLD_ID = 'MERIDIAN'),
    'quarantine', (SELECT COUNT(*) FROM LAND.QUARANTINE));
END;
$$;

-- ---------------------------------------------------------------- knowledge graph projection (rebuildable)
CREATE OR REPLACE PROCEDURE CORE.BUILD_GRAPH()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
  DELETE FROM CORE.KG_NODE;
  INSERT INTO CORE.KG_NODE
    SELECT 'PART:' || ITEM_ID, IFF(ITEM_TYPE = 'FINISHED', 'Product', 'Part'), ITEM_ID || ' · ' || NAME, OBJECT_CONSTRUCT('item_type', ITEM_TYPE, 'family', FAMILY), 'SYNTHETIC_ERP' FROM GOV.ITEM
    UNION ALL SELECT 'PARTY:' || PARTY_ID, INITCAP(PARTY_TYPE), NAME, OBJECT_CONSTRUCT('country', COUNTRY), 'SYNTHETIC_ERP' FROM GOV.PARTY
    UNION ALL SELECT 'FAC:' || FACILITY_ID, IFF(KIND = 'PLANT', 'Plant', 'DC'), NAME, OBJECT_CONSTRUCT('timezone', TIMEZONE, 'country', COUNTRY), 'SYNTHETIC_ERP' FROM GOV.FACILITY
    UNION ALL SELECT DISTINCT 'FAMILY:' || FAMILY, 'ProductFamily', FAMILY, OBJECT_CONSTRUCT(), 'SYNTHETIC_ERP' FROM GOV.ITEM
    UNION ALL SELECT DISTINCT 'COUNTRY:' || COUNTRY, 'Country', COUNTRY, OBJECT_CONSTRUCT(), 'SYNTHETIC_ERP'
      FROM (SELECT COUNTRY FROM GOV.PARTY UNION SELECT COUNTRY FROM GOV.FACILITY UNION SELECT COUNTRY FROM GOV.GEOGRAPHY) WHERE COUNTRY IS NOT NULL
    UNION ALL SELECT 'REGION:' || GEOGRAPHY_ID, 'Region', NAME, OBJECT_CONSTRUCT('country', COUNTRY), 'SYNTHETIC_CRM' FROM GOV.GEOGRAPHY
    UNION ALL SELECT 'SHIPTO:' || SHIP_TO_ID, 'ShipTo', SHIP_TO_ID, OBJECT_CONSTRUCT('geography', GEOGRAPHY_ID), 'SYNTHETIC_CRM' FROM GOV.SHIP_TO
    UNION ALL SELECT 'PO:' || LINE_ID, 'PurchaseOrderLine', LINE_ID, OBJECT_CONSTRUCT('qty', ORDERED_QTY, 'requested', BUYER_REQUESTED_ON), 'SYNTHETIC_ERP' FROM CORE.PO_LINE WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'RCPT:' || RECEIPT_ID, 'Receipt', RECEIPT_ID, OBJECT_CONSTRUCT('accepted', ACCEPTED_QTY, 'on', ACCEPTED_ON), 'SYNTHETIC_WMS' FROM CORE.RECEIPT WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'SO:' || LINE_ID, 'SalesOrderLine', LINE_ID, OBJECT_CONSTRUCT('qty', ORDERED_QTY, 'promise', ORIGINAL_PROMISE_ON), 'SYNTHETIC_ERP' FROM CORE.SO_LINE WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'SHIP:' || SHIP_ID, 'Shipment', SHIP_ID, OBJECT_CONSTRUCT('qty', QTY, 'on', SHIP_ON), 'SYNTHETIC_WMS' FROM CORE.SO_SHIPMENT WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'MO:' || ORDER_ID, 'ProductionOrder', ORDER_ID, OBJECT_CONSTRUCT('qty', QTY, 'complete', COMPLETE_ON), 'SYNTHETIC_MES' FROM CORE.PRODUCTION_ORDER WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'COST:' || COMPONENT_ID, 'CostComponent', KIND || ' ' || SOURCE_DOCUMENT_ID, OBJECT_CONSTRUCT('kind', KIND), 'SYNTHETIC_ERP' FROM CORE.COST_COMPONENT WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'LOT:' || LOT_ID, 'Lot', LOT_ID, OBJECT_CONSTRUCT('item_id', ITEM_ID, 'qty', QTY), ORIGIN FROM CORE.LOT_TRACE
    UNION ALL SELECT 'SENSOR:' || SENSOR_ID, 'IoTSensor', SENSOR_ID, OBJECT_CONSTRUCT('facility_id', FACILITY_ID), 'SYNTHETIC_IOT'
      FROM CORE.IOT_EVENT GROUP BY SENSOR_ID, FACILITY_ID;
  DELETE FROM CORE.KG_EDGE;
  INSERT INTO CORE.KG_EDGE
    SELECT 'SUPPLIES', 'PARTY:' || SUPPLIER_ID, 'PART:' || ITEM_ID, '2025-01-01', NULL, CURRENT_TIMESTAMP()::TIMESTAMP_TZ, NULL, 'SYNTHETIC_ERP', 'ADMINISTERED' FROM GOV.SUPPLY
    UNION ALL SELECT 'COMPONENT_OF', 'PART:' || COMPONENT_ID, 'PART:' || PARENT_ID, VALID_FROM, VALID_TO, CURRENT_TIMESTAMP()::TIMESTAMP_TZ, 'BOM rev ' || REVISION, 'SYNTHETIC_MES', 'EXACT_KEY' FROM CORE.BOM WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'SUBSTITUTES_FOR', 'PART:' || SUBSTITUTE_ITEM_ID, 'PART:' || ITEM_ID, VALID_FROM, VALID_TO,
      CURRENT_TIMESTAMP()::TIMESTAMP_TZ, APPROVED_BY, 'SYNTHETIC_ERP', 'ADMINISTERED' FROM GOV.SUBSTITUTION
    UNION ALL SELECT 'CONSUMES', 'MO:' || ORDER_ID, 'PART:' || COMPONENT_ID, ISSUED_ON, NULL, VISIBLE_AT,
      ISSUE_ID, 'SYNTHETIC_MES', 'EXACT_KEY' FROM CORE.PRODUCTION_CONSUMPTION WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'PARENT_OF', 'PARTY:' || PARENT_PARTY_ID, 'PARTY:' || PARTY_ID, NULL, NULL,
      CURRENT_TIMESTAMP()::TIMESTAMP_TZ, NULL, 'SYNTHETIC_ERP', 'ADMINISTERED'
      FROM GOV.PARTY WHERE PARENT_PARTY_ID IS NOT NULL
    UNION ALL SELECT 'BELONGS_TO_FAMILY', 'PART:' || ITEM_ID, 'FAMILY:' || FAMILY, NULL, NULL,
      CURRENT_TIMESTAMP()::TIMESTAMP_TZ, NULL, 'SYNTHETIC_ERP', 'ADMINISTERED' FROM GOV.ITEM
    UNION ALL SELECT 'IN_COUNTRY', 'FAC:' || FACILITY_ID, 'COUNTRY:' || COUNTRY, NULL, NULL,
      CURRENT_TIMESTAMP()::TIMESTAMP_TZ, NULL, 'SYNTHETIC_ERP', 'ADMINISTERED' FROM GOV.FACILITY
    UNION ALL SELECT 'IN_COUNTRY', 'REGION:' || GEOGRAPHY_ID, 'COUNTRY:' || COUNTRY, NULL, NULL,
      CURRENT_TIMESTAMP()::TIMESTAMP_TZ, NULL, 'SYNTHETIC_CRM', 'ADMINISTERED' FROM GOV.GEOGRAPHY
    UNION ALL SELECT 'IN_REGION', 'SHIPTO:' || SHIP_TO_ID, 'REGION:' || GEOGRAPHY_ID, NULL, NULL,
      CURRENT_TIMESTAMP()::TIMESTAMP_TZ, NULL, 'SYNTHETIC_CRM', 'ADMINISTERED' FROM GOV.SHIP_TO
    UNION ALL SELECT DISTINCT 'CAPABLE_OF_PRODUCING', 'FAC:' || FACILITY_ID, 'PART:' || ITEM_ID, NULL, NULL, CURRENT_TIMESTAMP()::TIMESTAMP_TZ, NULL, 'SYNTHETIC_MES', 'EXACT_KEY' FROM CORE.PRODUCTION_ORDER WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'RECEIVED_FROM', 'RCPT:' || r.RECEIPT_ID, 'PARTY:' || r.SUPPLIER_ID, r.RECEIVED_ON, NULL, r.VISIBLE_AT, r.RECEIPT_ID, 'SYNTHETIC_WMS', 'EXACT_KEY' FROM CORE.RECEIPT r WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'HELD_AT', 'RCPT:' || r.RECEIPT_ID, 'FAC:' || r.FACILITY_ID, r.RECEIVED_ON, NULL, r.VISIBLE_AT, r.RECEIPT_ID, 'SYNTHETIC_WMS', 'GLN' FROM CORE.RECEIPT r WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'FULFILLS', 'RCPT:' || r.RECEIPT_ID, 'PO:' || r.LINE_ID, r.RECEIVED_ON, NULL, r.VISIBLE_AT, r.RECEIPT_ID, 'SYNTHETIC_WMS', 'EXACT_KEY' FROM CORE.RECEIPT r WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'EXECUTED_AT', 'MO:' || ORDER_ID, 'FAC:' || FACILITY_ID, START_ON, COMPLETE_ON, VISIBLE_AT, ORDER_ID, 'SYNTHETIC_MES', 'EXACT_KEY' FROM CORE.PRODUCTION_ORDER WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'PRODUCES', 'MO:' || ORDER_ID, 'PART:' || ITEM_ID, START_ON, COMPLETE_ON, VISIBLE_AT, ORDER_ID, 'SYNTHETIC_MES', 'EXACT_KEY' FROM CORE.PRODUCTION_ORDER WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'PLACED', 'PARTY:' || CUSTOMER_ID, 'SO:' || LINE_ID, ORDER_ON, NULL, VISIBLE_AT, LINE_ID, 'SYNTHETIC_ERP', 'ADMINISTERED' FROM CORE.SO_LINE WHERE WORLD_ID = 'MERIDIAN' AND CUSTOMER_ID IS NOT NULL
    UNION ALL SELECT 'FULFILLS', 'SHIP:' || SHIP_ID, 'SO:' || LINE_ID, SHIP_ON, NULL, VISIBLE_AT, SHIP_ID, 'SYNTHETIC_WMS', 'EXACT_KEY' FROM CORE.SO_SHIPMENT WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'DELIVERED_TO', 'SHIP:' || d.SHIPMENT_ID, 'SHIPTO:' || l.SHIP_TO_ID, d.EVENT_ON, NULL, d.VISIBLE_AT, d.EVENT_ID, 'SYNTHETIC_TMS', 'GLN'
      FROM CORE.SO_DELIVERY_EVENT d JOIN CORE.SO_LINE l ON l.WORLD_ID = d.WORLD_ID AND l.LINE_ID = d.LINE_ID WHERE d.WORLD_ID = 'MERIDIAN' AND d.KIND = 'POD'
    UNION ALL SELECT 'PROMISES', 'PROMISE:' || LINE_ID || ':' || REVISION, 'SO:' || LINE_ID, RECORDED_ON, NULL, VISIBLE_AT, LINE_ID, 'SYNTHETIC_ERP', 'EXACT_KEY' FROM CORE.PROMISE_REVISION WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'COST_OF', 'COST:' || COMPONENT_ID, 'RCPT:' || RECEIPT_ID, ECONOMIC_DATE, NULL, OBLIGATION_VISIBLE_AT, SOURCE_DOCUMENT_ID, 'SYNTHETIC_ERP', 'EXACT_KEY' FROM CORE.COST_COMPONENT WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT IFF(KIND = 'RETURN', 'RETURNED_AGAINST', 'FEEDBACK_ON'), 'FB:' || FEEDBACK_ID, 'SO:' || LINE_ID, FEEDBACK_ON, NULL, VISIBLE_AT, FEEDBACK_ID, 'SYNTHETIC_CRM', 'EXACT_KEY' FROM CORE.FEEDBACK WHERE WORLD_ID = 'MERIDIAN'
    UNION ALL SELECT 'CONTAINS', IFF(SOURCE_TYPE = 'RECEIPT', 'RCPT:', IFF(SOURCE_TYPE = 'SHIPMENT', 'SHIP:', 'MO:')) || SOURCE_ID,
      'LOT:' || LOT_ID, EVENT_TIME::DATE, NULL, VISIBLE_AT, SOURCE_ID, ORIGIN, 'EXACT_KEY' FROM CORE.LOT_TRACE
    UNION ALL SELECT 'SENSES', 'SENSOR:' || SENSOR_ID, 'LOT:' || LOT_ID, EVENT_TIME::DATE, NULL, VISIBLE_AT,
      EVENT_ID, 'SYNTHETIC_IOT', 'GTIN_GLN' FROM CORE.IOT_EVENT
    UNION ALL SELECT 'SAME_AS', SOURCE_SYSTEM || ':' || SOURCE_KEY, CASE ENTITY_TYPE WHEN 'ITEM' THEN 'PART:' WHEN 'FACILITY' THEN 'FAC:' WHEN 'SHIP_TO' THEN 'SHIPTO:' ELSE 'PARTY:' END || CANONICAL_ID,
      VALID_FROM, NULL, CURRENT_TIMESTAMP()::TIMESTAMP_TZ, NULL, 'SYNTHETIC_' || SOURCE_SYSTEM, METHOD FROM GOV.SOURCE_ALIAS;
  RETURN 'nodes=' || (SELECT COUNT(*) FROM CORE.KG_NODE) || ' edges=' || (SELECT COUNT(*) FROM CORE.KG_EDGE);
END;
$$;

-- ---------------------------------------------------------------- stream-triggered pipeline
CREATE TABLE IF NOT EXISTS CORE.STREAM_WATERMARK (CONSUMED_AT TIMESTAMP_TZ, NEW_RECORDS NUMBER);

CREATE OR REPLACE PROCEDURE CORE.RUN_PIPELINE()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  resolved VARIANT;
  published VARIANT;
BEGIN
  INSERT INTO CORE.STREAM_WATERMARK SELECT CURRENT_TIMESTAMP()::TIMESTAMP_TZ, COUNT(*) FROM LAND.RAW_RECORD_STREAM;
  CALL CORE.RESOLVE() INTO :resolved;
  CALL APP.PUBLISH_RESULTS() INTO :published;
  RETURN OBJECT_CONSTRUCT('resolve', :resolved, 'publish', :published);
END;
$$;

CREATE OR REPLACE TASK CORE.RESOLVE_TASK
  WAREHOUSE = CONCORDIA_WH
  SCHEDULE = '60 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('LAND.RAW_RECORD_STREAM')
AS CALL CORE.RUN_PIPELINE();
