-- Metric contract 1.0.0 in SQL. This file is the only numeric authority.
-- *_LINES / *_RECEIPTS / M4_FACILITY return contribution rows for one world and one RECORDED_AS_OF.
-- *_RESULT functions filter period and scope and aggregate with the same expressions the
-- publisher uses (the COUNT_AGG, FILL_AGG and LANDED_AGG templates from scripts/metric_sql.py).

USE ROLE CONCORDIA_ADMIN;
USE WAREHOUSE CONCORDIA_WH;
USE DATABASE CONCORDIA;

-- ---------------------------------------------------------------- M1 inbound supplier OTD
CREATE OR REPLACE FUNCTION CORE.M1_LINES(P_W VARCHAR, P_ASOF TIMESTAMP_TZ)
RETURNS TABLE (LINE_ID VARCHAR, PERIOD_DATE DATE, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, SUPPLIER_ID VARCHAR, GEOGRAPHY_ID VARCHAR,
               CUSTOMER_ID VARCHAR, OUTCOME VARCHAR, REASONS ARRAY, QTY NUMBER(38,6), FILLED_QTY NUMBER(38,6),
               COMMITMENT_ON DATE, COMPLETED_ON DATE, DRIVER VARCHAR)
AS
$$
WITH l AS (
  SELECT * FROM CORE.PO_LINE WHERE WORLD_ID = P_W AND (VISIBLE_AT IS NULL OR VISIBLE_AT <= P_ASOF)
), acc AS (
  SELECT a.LINE_ID, a.ACCEPTED_ON, a.QTY,
         SUM(a.QTY) OVER (PARTITION BY a.LINE_ID ORDER BY a.ACCEPTED_ON, a.SEQ ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING
  FROM CORE.PO_ACCEPTANCE a
  WHERE a.WORLD_ID = P_W AND a.VISIBLE_AT IS NOT NULL AND a.VISIBLE_AT <= P_ASOF
), done AS (
  SELECT l.LINE_ID, MIN(IFF(acc.RUNNING >= l.ORDERED_QTY, acc.ACCEPTED_ON, NULL)) AS COMPLETED, SUM(acc.QTY) AS ACCEPTED_TOTAL
  FROM l JOIN acc ON acc.LINE_ID = l.LINE_ID GROUP BY l.LINE_ID
), x AS (
  SELECT l.*, gc.CALENDAR_ID IS NOT NULL AS HAS_CAL, dl.DAY AS DEADLINE, done.COMPLETED, COALESCE(done.ACCEPTED_TOTAL, 0) AS ACCEPTED_TOTAL
  FROM l
  LEFT JOIN done ON done.LINE_ID = l.LINE_ID
  LEFT JOIN GOV.CALENDAR gc ON gc.CALENDAR_ID = l.CALENDAR_ID
  LEFT JOIN GOV.CALENDAR_DAY c1 ON c1.CALENDAR_ID = l.CALENDAR_ID AND c1.DAY = l.ISSUED_ON
  LEFT JOIN GOV.CALENDAR_DAY dl ON dl.CALENDAR_ID = l.CALENDAR_ID AND dl.IS_BUSINESS AND dl.BUSINESS_ORDINAL = c1.BUSINESS_ORDINAL + 2
), y AS (
  SELECT x.*,
         ARRAY_CONSTRUCT_COMPACT(
           IFF(IDENTITY_RESOLVED = FALSE, 'IDENTITY_UNRESOLVED', NULL),
           IFF(UOM_RESOLVED = FALSE, 'UOM_UNRESOLVED', NULL),
           IFF(TIMEZONE_RESOLVED = FALSE OR TIMEZONE IS NULL OR TIMEZONE = '', 'TIMEZONE_MISSING', NULL),
           IFF(NOT HAS_CAL, 'CALENDAR_MISSING', NULL),
           IFF(DISPOSITION_MISSING = TRUE, 'DISPOSITION_MISSING', NULL),
           IFF(CANCELLATION = 'BUYER_BEFORE_COMMITMENT', 'BUYER_CANCELLED', NULL)) AS FLAGS,
         IFF(HAS_CAL AND ACK_ON IS NOT NULL AND ACK_PROMISE_ON IS NOT NULL AND ACK_VISIBLE_AT IS NOT NULL AND ACK_VISIBLE_AT <= P_ASOF
             AND ACK_ON <= DEADLINE AND NOT (FIRST_RECEIPT_ON IS NOT NULL AND ACK_ON > FIRST_RECEIPT_ON),
             ACK_PROMISE_ON, BUYER_REQUESTED_ON) AS COMMITMENT
  FROM x
)
SELECT LINE_ID, COMMITMENT, ITEM_ID, FACILITY_ID, SUPPLIER_ID, NULL, NULL,
       CASE
         WHEN ARRAY_SIZE(FLAGS) > 0 THEN 'EXCLUDED'
         WHEN CANCELLATION = 'SUPPLIER_LATE' AND COMPLETED IS NULL THEN 'MISS'
         WHEN COMPLETED IS NULL AND COMMITMENT > CONVERT_TIMEZONE(TIMEZONE, P_ASOF)::DATE THEN 'EXCLUDED'
         WHEN COMPLETED IS NOT NULL AND COMPLETED <= COMMITMENT THEN 'HIT'
         ELSE 'MISS' END,
       CASE
         WHEN ARRAY_SIZE(FLAGS) > 0 THEN FLAGS
         WHEN CANCELLATION = 'SUPPLIER_LATE' AND COMPLETED IS NULL THEN ARRAY_CONSTRUCT()
         WHEN COMPLETED IS NULL AND COMMITMENT > CONVERT_TIMEZONE(TIMEZONE, P_ASOF)::DATE THEN ARRAY_CONSTRUCT('FUTURE_OPEN')
         ELSE ARRAY_CONSTRUCT() END,
       IFF(ARRAY_SIZE(FLAGS) > 0, COALESCE(ORDERED_QTY, 0), ORDERED_QTY),
       NULL,
       COMMITMENT, COMPLETED,
       CASE
         WHEN ARRAY_SIZE(FLAGS) > 0 OR (COMPLETED IS NOT NULL AND COMPLETED <= COMMITMENT) THEN NULL
         WHEN COMPLETED IS NULL AND CANCELLATION IS NULL AND COMMITMENT > CONVERT_TIMEZONE(TIMEZONE, P_ASOF)::DATE THEN NULL
         WHEN CANCELLATION = 'SUPPLIER_LATE' THEN 'SUPPLIER_CANCELLED'
         WHEN COALESCE(SUPPLIER_REJECTED_QTY, 0) > 0 THEN 'SUPPLIER_REJECT'
         WHEN COMPLETED IS NULL AND ACCEPTED_TOTAL > 0 THEN 'PARTIAL_RECEIPT'
         WHEN COMPLETED IS NULL THEN 'OPEN_PAST_DUE'
         ELSE 'LATE_RECEIPT' END
FROM y
$$;

-- ---------------------------------------------------------------- M2 outbound customer OTD
CREATE OR REPLACE FUNCTION CORE.M2_LINES(P_W VARCHAR, P_ASOF TIMESTAMP_TZ)
RETURNS TABLE (LINE_ID VARCHAR, PERIOD_DATE DATE, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, SUPPLIER_ID VARCHAR, GEOGRAPHY_ID VARCHAR,
               CUSTOMER_ID VARCHAR, OUTCOME VARCHAR, REASONS ARRAY, QTY NUMBER(38,6), FILLED_QTY NUMBER(38,6),
               COMMITMENT_ON DATE, COMPLETED_ON DATE, DRIVER VARCHAR)
AS
$$
WITH l AS (
  SELECT s.*, gc.CALENDAR_ID IS NOT NULL AS HAS_CAL,
         IFF(s.SHORT_CLOSE_QTY IS NOT NULL AND s.SHORT_CLOSE_APPROVED_ON IS NOT NULL AND s.SHORT_CLOSE_APPROVED_ON <= s.ORIGINAL_PROMISE_ON,
             s.SHORT_CLOSE_QTY, s.ORDERED_QTY) AS REQUIRED,
         IFF(s.INCOTERM IN ('EXW', 'FCA'), 'READY', 'POD') AS MILESTONE
  FROM CORE.SO_LINE s LEFT JOIN GOV.CALENDAR gc ON gc.CALENDAR_ID = s.CALENDAR_ID
  WHERE s.WORLD_ID = P_W AND (s.VISIBLE_AT IS NULL OR s.VISIBLE_AT <= P_ASOF)
), ev AS (
  SELECT e.LINE_ID, e.KIND, e.EVENT_ON, e.QTY, e.SEQ
  FROM CORE.SO_DELIVERY_EVENT e
  WHERE e.WORLD_ID = P_W AND e.VISIBLE_AT IS NOT NULL AND e.VISIBLE_AT <= P_ASOF
), counted AS (
  SELECT ev.LINE_ID, ev.EVENT_ON, ev.QTY, l.REQUIRED,
         SUM(ev.QTY) OVER (PARTITION BY ev.LINE_ID ORDER BY ev.EVENT_ON, ev.SEQ ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING
  FROM ev JOIN l ON l.LINE_ID = ev.LINE_ID AND ev.KIND = l.MILESTONE
), done AS (
  SELECT LINE_ID, MIN(IFF(RUNNING >= REQUIRED, EVENT_ON, NULL)) AS COMPLETED, COUNT(*) AS COUNTED_EVENTS FROM counted GROUP BY LINE_ID
), failed AS (
  SELECT LINE_ID, COUNT(*) AS FAILED_ATTEMPTS FROM ev WHERE KIND IN ('ATTEMPT', 'MISDELIVERY') GROUP BY LINE_ID
), revised AS (
  SELECT LINE_ID, COUNT(*) AS REVISIONS FROM CORE.PROMISE_REVISION
  WHERE WORLD_ID = P_W AND KIND = 'REVISED' AND (VISIBLE_AT IS NULL OR VISIBLE_AT <= P_ASOF) GROUP BY LINE_ID
), x AS (
  SELECT l.*,
         ARRAY_CONSTRUCT_COMPACT(
           IFF(IDENTITY_RESOLVED = FALSE, 'IDENTITY_UNRESOLVED', NULL),
           IFF(UOM_RESOLVED = FALSE, 'UOM_UNRESOLVED', NULL),
           IFF(TIMEZONE IS NULL OR TIMEZONE = '', 'TIMEZONE_MISSING', NULL),
           IFF(NOT HAS_CAL, 'CALENDAR_MISSING', NULL),
           IFF(INCOTERM IS NULL OR INCOTERM = '', 'INCOTERM_MISSING', NULL),
           IFF(INCOTERM IS NOT NULL AND INCOTERM <> '' AND INCOTERM NOT IN ('EXW', 'FCA', 'DAP', 'DDP'), 'INCOTERM_UNSUPPORTED', NULL)) AS FLAGS,
         HOLD_START IS NOT NULL AND HOLD_END IS NOT NULL AND HOLD_RECORDED_ON IS NOT NULL AND HOLD_RECORDED_ON <= ORIGINAL_PROMISE_ON
           AND HOLD_START <= ORIGINAL_PROMISE_ON AND ORIGINAL_PROMISE_ON <= HOLD_END AS HOLD_EXCLUDES,
         done.COMPLETED, COALESCE(failed.FAILED_ATTEMPTS, 0) AS FAILED_ATTEMPTS, COALESCE(done.COUNTED_EVENTS, 0) AS COUNTED_EVENTS,
         COALESCE(revised.REVISIONS, 0) AS REVISIONS
  FROM l
  LEFT JOIN done ON done.LINE_ID = l.LINE_ID
  LEFT JOIN failed ON failed.LINE_ID = l.LINE_ID
  LEFT JOIN revised ON revised.LINE_ID = l.LINE_ID
), y AS (
  SELECT x.*,
         CASE
           WHEN ARRAY_SIZE(FLAGS) > 0 THEN 'EXCLUDED'
           WHEN CANCELLATION = 'CUSTOMER_BEFORE_PICK' THEN 'EXCLUDED'
           WHEN HOLD_EXCLUDES THEN 'EXCLUDED'
           WHEN COMPLETED IS NULL AND ORIGINAL_PROMISE_ON > CONVERT_TIMEZONE(TIMEZONE, P_ASOF)::DATE THEN 'EXCLUDED'
           WHEN COMPLETED IS NOT NULL AND COMPLETED <= ORIGINAL_PROMISE_ON THEN 'HIT'
           ELSE 'MISS' END AS OUTCOME
  FROM x
)
SELECT LINE_ID, ORIGINAL_PROMISE_ON, ITEM_ID, FACILITY_ID, NULL, GEOGRAPHY_ID, CUSTOMER_ID, OUTCOME,
       CASE
         WHEN ARRAY_SIZE(FLAGS) > 0 THEN FLAGS
         WHEN CANCELLATION = 'CUSTOMER_BEFORE_PICK' THEN ARRAY_CONSTRUCT('CUSTOMER_CANCELLED')
         WHEN HOLD_EXCLUDES THEN ARRAY_CONSTRUCT('CUSTOMER_HOLD')
         WHEN OUTCOME = 'EXCLUDED' THEN ARRAY_CONSTRUCT('FUTURE_OPEN')
         ELSE ARRAY_CONSTRUCT() END,
       IFF(ARRAY_SIZE(FLAGS) > 0 OR CANCELLATION = 'CUSTOMER_BEFORE_PICK' OR HOLD_EXCLUDES, COALESCE(ORDERED_QTY, 0), REQUIRED),
       NULL, ORIGINAL_PROMISE_ON, COMPLETED,
       IFF(OUTCOME <> 'MISS', NULL,
         CASE
           WHEN FAILED_ATTEMPTS > 0 THEN 'FAILED_OR_MISDELIVERED'
           WHEN COUNTED_EVENTS > 1 THEN 'PARTIAL_DELIVERY'
           WHEN REVISIONS > 0 THEN 'PROMISE_REVISED'
           WHEN COMPLETED IS NOT NULL THEN 'LATE_DELIVERY'
           WHEN CANCELLATION = 'COMPANY' THEN 'COMPANY_CANCELLED'
           ELSE 'NOT_DELIVERED' END)
FROM y
$$;

-- ---------------------------------------------------------------- M3 unit fill rate
CREATE OR REPLACE FUNCTION CORE.M3_LINES(P_W VARCHAR, P_ASOF TIMESTAMP_TZ)
RETURNS TABLE (LINE_ID VARCHAR, PERIOD_DATE DATE, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, SUPPLIER_ID VARCHAR, GEOGRAPHY_ID VARCHAR,
               CUSTOMER_ID VARCHAR, OUTCOME VARCHAR, REASONS ARRAY, QTY NUMBER(38,6), FILLED_QTY NUMBER(38,6),
               COMMITMENT_ON DATE, COMPLETED_ON DATE, DRIVER VARCHAR)
AS
$$
WITH shipped AS (
  SELECT LINE_ID, SUM(QTY) AS QTY FROM CORE.SO_SHIPMENT
  WHERE WORLD_ID = P_W AND VISIBLE_AT IS NOT NULL AND VISIBLE_AT <= P_ASOF GROUP BY LINE_ID
), l AS (
  SELECT s.*, COALESCE(shipped.QTY, 0) AS SHIPPED_VISIBLE
  FROM CORE.SO_LINE s LEFT JOIN shipped ON shipped.LINE_ID = s.LINE_ID
  WHERE s.WORLD_ID = P_W AND (s.VISIBLE_AT IS NULL OR s.VISIBLE_AT <= P_ASOF)
), x AS (
  SELECT l.*,
         CASE
           WHEN UOM_RESOLVED = FALSE OR ORDERED_QTY IS NULL THEN 'UOM_UNRESOLVED'
           WHEN CANCELLATION = 'CUSTOMER_BEFORE_PICK' THEN 'CUSTOMER_CANCELLED' END AS EXCLUSION,
         LEAST(IFF(CANCELLATION = 'COMPANY' OR SUBSTITUTE = 'SILENT', 0, SHIPPED_VISIBLE), ORDERED_QTY) AS CAPPED
  FROM l
)
SELECT LINE_ID, REQUESTED_SHIP_ON, ITEM_ID, FACILITY_ID, NULL, GEOGRAPHY_ID, CUSTOMER_ID,
       CASE WHEN EXCLUSION IS NOT NULL THEN 'EXCLUDED' WHEN CAPPED < ORDERED_QTY THEN 'MISS' ELSE 'HIT' END,
       IFF(EXCLUSION IS NOT NULL, ARRAY_CONSTRUCT(EXCLUSION), ARRAY_CONSTRUCT()),
       ORDERED_QTY, IFF(EXCLUSION IS NOT NULL, NULL, CAPPED), REQUESTED_SHIP_ON, NULL,
       CASE
         WHEN EXCLUSION IS NOT NULL OR CAPPED >= ORDERED_QTY THEN NULL
         WHEN CANCELLATION = 'COMPANY' THEN 'COMPANY_CANCELLED'
         WHEN SUBSTITUTE = 'SILENT' THEN 'SILENT_SUBSTITUTE'
         WHEN CAPPED > 0 THEN 'PARTIAL_SHIPMENT'
         ELSE 'NOT_SHIPPED' END
FROM x
$$;

-- ---------------------------------------------------------------- aggregates for line metrics
CREATE OR REPLACE FUNCTION CORE.COUNT_RESULT_M1(P_W VARCHAR, P_PS DATE, P_PE DATE, P_ASOF TIMESTAMP_TZ, P_ITEM VARCHAR, P_FACILITY VARCHAR,
                                                P_GEO VARCHAR, P_SUPPLIER VARCHAR, P_CUSTOMER VARCHAR)
RETURNS TABLE (STATUS VARCHAR, NUMERATOR VARCHAR, DENOMINATOR VARCHAR, DISPLAY VARCHAR, VALUE_NUM NUMBER(38,12), REASONS ARRAY, COVERAGE VARCHAR,
               DIAGNOSTIC_DISPLAY VARCHAR, EXCLUDED_COUNT NUMBER, AFFECTED_COMMITMENTS NUMBER, AFFECTED_UNITS VARCHAR, UNRESOLVED_RECORDS NUMBER,
               EVIDENCE_IDS ARRAY)
AS
$$
SELECT {{COUNT_AGG}}
FROM TABLE(CORE.M1_LINES(P_W, P_ASOF))
WHERE PERIOD_DATE BETWEEN P_PS AND P_PE
  AND (P_ITEM IS NULL OR ITEM_ID = P_ITEM) AND (P_FACILITY IS NULL OR FACILITY_ID = P_FACILITY)
  AND (P_GEO IS NULL OR GEOGRAPHY_ID = P_GEO) AND (P_SUPPLIER IS NULL OR SUPPLIER_ID = P_SUPPLIER) AND (P_CUSTOMER IS NULL OR CUSTOMER_ID = P_CUSTOMER)
$$;

CREATE OR REPLACE FUNCTION CORE.COUNT_RESULT_M2(P_W VARCHAR, P_PS DATE, P_PE DATE, P_ASOF TIMESTAMP_TZ, P_ITEM VARCHAR, P_FACILITY VARCHAR,
                                                P_GEO VARCHAR, P_SUPPLIER VARCHAR, P_CUSTOMER VARCHAR)
RETURNS TABLE (STATUS VARCHAR, NUMERATOR VARCHAR, DENOMINATOR VARCHAR, DISPLAY VARCHAR, VALUE_NUM NUMBER(38,12), REASONS ARRAY, COVERAGE VARCHAR,
               DIAGNOSTIC_DISPLAY VARCHAR, EXCLUDED_COUNT NUMBER, AFFECTED_COMMITMENTS NUMBER, AFFECTED_UNITS VARCHAR, UNRESOLVED_RECORDS NUMBER,
               EVIDENCE_IDS ARRAY)
AS
$$
SELECT {{COUNT_AGG}}
FROM TABLE(CORE.M2_LINES(P_W, P_ASOF))
WHERE PERIOD_DATE BETWEEN P_PS AND P_PE
  AND (P_ITEM IS NULL OR ITEM_ID = P_ITEM) AND (P_FACILITY IS NULL OR FACILITY_ID = P_FACILITY)
  AND (P_GEO IS NULL OR GEOGRAPHY_ID = P_GEO) AND (P_SUPPLIER IS NULL OR SUPPLIER_ID = P_SUPPLIER) AND (P_CUSTOMER IS NULL OR CUSTOMER_ID = P_CUSTOMER)
$$;

CREATE OR REPLACE FUNCTION CORE.FILL_RESULT_M3(P_W VARCHAR, P_PS DATE, P_PE DATE, P_ASOF TIMESTAMP_TZ, P_ITEM VARCHAR, P_FACILITY VARCHAR,
                                               P_GEO VARCHAR, P_SUPPLIER VARCHAR, P_CUSTOMER VARCHAR)
RETURNS TABLE (STATUS VARCHAR, NUMERATOR VARCHAR, DENOMINATOR VARCHAR, DISPLAY VARCHAR, VALUE_NUM NUMBER(38,12), REASONS ARRAY, COVERAGE VARCHAR,
               DIAGNOSTIC_DISPLAY VARCHAR, EXCLUDED_COUNT NUMBER, AFFECTED_COMMITMENTS NUMBER, AFFECTED_UNITS VARCHAR, UNRESOLVED_RECORDS NUMBER,
               EVIDENCE_IDS ARRAY)
AS
$$
SELECT {{FILL_AGG}}
FROM TABLE(CORE.M3_LINES(P_W, P_ASOF))
WHERE PERIOD_DATE BETWEEN P_PS AND P_PE
  AND (P_ITEM IS NULL OR ITEM_ID = P_ITEM) AND (P_FACILITY IS NULL OR FACILITY_ID = P_FACILITY)
  AND (P_GEO IS NULL OR GEOGRAPHY_ID = P_GEO) AND (P_SUPPLIER IS NULL OR SUPPLIER_ID = P_SUPPLIER) AND (P_CUSTOMER IS NULL OR CUSTOMER_ID = P_CUSTOMER)
$$;

-- ---------------------------------------------------------------- M4 days inventory
CREATE OR REPLACE FUNCTION CORE.M4_RESULT(P_W VARCHAR, P_ASOF TIMESTAMP_TZ, P_ITEM VARCHAR, P_FACILITY VARCHAR, P_CLASS VARCHAR, P_NETWORK BOOLEAN)
RETURNS TABLE (STATUS VARCHAR, NUMERATOR VARCHAR, DENOMINATOR VARCHAR, DISPLAY VARCHAR, VALUE_NUM NUMBER(38,12), REASONS ARRAY, COVERAGE VARCHAR,
               DIAGNOSTIC_DISPLAY VARCHAR, EXCLUDED_COUNT NUMBER, AFFECTED_COMMITMENTS NUMBER, AFFECTED_UNITS VARCHAR, UNRESOLVED_RECORDS NUMBER,
               EVIDENCE_IDS ARRAY)
AS
$$
WITH tz AS (
  SELECT COUNT(*) AS N FROM CORE.WORLD_FACILITY WHERE WORLD_ID = P_W AND TIMEZONE IS NOT NULL AND TIMEZONE <> ''
), latest AS (
  SELECT * FROM CORE.INVENTORY_SNAPSHOT
  WHERE WORLD_ID = P_W AND VISIBLE_AT IS NOT NULL AND VISIBLE_AT <= P_ASOF
    AND (P_ITEM IS NULL OR ITEM_ID = P_ITEM)
    AND (COALESCE(P_NETWORK, FALSE) OR P_FACILITY IS NULL OR FACILITY_ID = P_FACILITY)
    AND (P_CLASS IS NULL OR INVENTORY_CLASS = P_CLASS)
  QUALIFY ROW_NUMBER() OVER (PARTITION BY FACILITY_ID ORDER BY VISIBLE_AT DESC, SEQ) = 1
), avail AS (
  SELECT COUNT(*) AS N, SUM(ON_HAND - QUALITY_HOLD - ALLOCATED) AS AVAILABLE,
         COALESCE(BOOLOR_AGG(ON_HAND - QUALITY_HOLD - ALLOCATED < 0), FALSE) AS NEGATIVE,
         ARRAY_AGG(SNAPSHOT_ID) WITHIN GROUP (ORDER BY SNAPSHOT_ID) AS IDS
  FROM latest
), dem AS (
  SELECT COALESCE(BOOLOR_AGG(f.TIMEZONE IS NULL OR f.TIMEZONE = ''), FALSE) AS MISSING_TZ,
         COALESCE(SUM(IFF(f.TIMEZONE IS NOT NULL AND f.TIMEZONE <> ''
                          AND d.DEMAND_ON BETWEEN DATEADD(day, -28, CONVERT_TIMEZONE(f.TIMEZONE, P_ASOF)::DATE)
                                              AND DATEADD(day, -1, CONVERT_TIMEZONE(f.TIMEZONE, P_ASOF)::DATE), d.QTY, 0)), 0) AS DEMAND
  FROM CORE.DEMAND_EVENT d
  LEFT JOIN CORE.WORLD_FACILITY f ON f.WORLD_ID = d.WORLD_ID AND f.FACILITY_ID = d.FACILITY_ID
  WHERE d.WORLD_ID = P_W AND (d.VISIBLE_AT IS NULL OR d.VISIBLE_AT <= P_ASOF)
    AND (P_ITEM IS NULL OR d.ITEM_ID = P_ITEM)
    AND (COALESCE(P_NETWORK, FALSE) OR P_FACILITY IS NULL OR d.FACILITY_ID = P_FACILITY)
    AND (P_CLASS IS NULL OR d.INVENTORY_CLASS = P_CLASS)
), s AS (
  SELECT CASE
           WHEN P_CLASS IS NULL THEN 'CLARIFY:INVENTORY_CLASS_MISSING'
           WHEN NOT COALESCE(P_NETWORK, FALSE) AND P_FACILITY IS NULL THEN 'CLARIFY:FACILITY_SCOPE_MISSING'
           WHEN tz.N = 0 THEN 'ABSTAIN:TIMEZONE_MISSING'
           WHEN avail.N = 0 THEN 'ABSTAIN:SNAPSHOT_MISSING'
           WHEN avail.NEGATIVE THEN 'ABSTAIN:NEGATIVE_AVAILABLE'
           WHEN dem.MISSING_TZ THEN 'ABSTAIN:TIMEZONE_MISSING'
           WHEN dem.DEMAND = 0 THEN 'ZERO_DEMAND:ZERO_DEMAND'
           ELSE 'COMPLETE:' END AS K,
         avail.AVAILABLE, avail.IDS, dem.DEMAND
  FROM tz, avail, dem
)
SELECT SPLIT_PART(K, ':', 1),
       IFF(K = 'COMPLETE:', TO_VARCHAR((AVAILABLE * 28)::NUMBER(38,6)), NULL),
       IFF(K = 'COMPLETE:', TO_VARCHAR(DEMAND::NUMBER(38,6)), NULL),
       IFF(K = 'COMPLETE:', TO_VARCHAR(ROUND((AVAILABLE * 28)::NUMBER(38,12) / DEMAND, 4, 'HALF_TO_EVEN')::NUMBER(38,4)), NULL),
       IFF(K = 'COMPLETE:', ((AVAILABLE * 28)::NUMBER(38,12) / DEMAND)::NUMBER(38,12), NULL),
       IFF(SPLIT_PART(K, ':', 2) = '', ARRAY_CONSTRUCT(), ARRAY_CONSTRUCT(SPLIT_PART(K, ':', 2))),
       IFF(K = 'COMPLETE:', '1.000000', NULL),
       NULL, 0, 0, '0.000000', 0,
       IFF(K IN ('COMPLETE:', 'ZERO_DEMAND:ZERO_DEMAND'), IDS, ARRAY_CONSTRUCT())
FROM s
$$;

CREATE OR REPLACE FUNCTION CORE.M4_GRID(P_W VARCHAR, P_ASOF TIMESTAMP_TZ, P_CLASS VARCHAR)
RETURNS TABLE (
  ITEM_ID VARCHAR, FACILITY_ID VARCHAR, NETWORK BOOLEAN,
  STATUS VARCHAR, NUMERATOR VARCHAR, DENOMINATOR VARCHAR, DISPLAY VARCHAR, VALUE_NUM NUMBER(38,12), REASONS ARRAY, COVERAGE VARCHAR,
  DIAGNOSTIC_DISPLAY VARCHAR, EXCLUDED_COUNT NUMBER, AFFECTED_COMMITMENTS NUMBER, AFFECTED_UNITS VARCHAR, UNRESOLVED_RECORDS NUMBER,
  EVIDENCE_IDS ARRAY
)
AS
$$
WITH scopes AS (
  SELECT DISTINCT ITEM_ID, FACILITY_ID, FALSE AS NETWORK
  FROM CORE.INVENTORY_SNAPSHOT
  WHERE WORLD_ID = P_W AND INVENTORY_CLASS = P_CLASS
  UNION ALL
  SELECT DISTINCT ITEM_ID, NULL::VARCHAR, TRUE
  FROM CORE.INVENTORY_SNAPSHOT
  WHERE WORLD_ID = P_W AND INVENTORY_CLASS = P_CLASS
), latest AS (
  SELECT sc.ITEM_ID AS S_ITEM, sc.FACILITY_ID AS S_FACILITY, sc.NETWORK, s.*
  FROM scopes sc JOIN CORE.INVENTORY_SNAPSHOT s
    ON s.WORLD_ID = P_W AND s.ITEM_ID = sc.ITEM_ID
   AND (sc.NETWORK OR s.FACILITY_ID = sc.FACILITY_ID)
   AND s.INVENTORY_CLASS = P_CLASS AND s.VISIBLE_AT IS NOT NULL AND s.VISIBLE_AT <= P_ASOF
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY sc.ITEM_ID, sc.FACILITY_ID, sc.NETWORK, s.FACILITY_ID
    ORDER BY s.VISIBLE_AT DESC, s.SEQ DESC
  ) = 1
), avail AS (
  SELECT S_ITEM AS ITEM_ID, S_FACILITY AS FACILITY_ID, NETWORK, COUNT(*) AS N,
         SUM(ON_HAND - QUALITY_HOLD - ALLOCATED) AS AVAILABLE,
         COALESCE(BOOLOR_AGG(ON_HAND - QUALITY_HOLD - ALLOCATED < 0), FALSE) AS NEGATIVE,
         ARRAY_AGG(SNAPSHOT_ID) WITHIN GROUP (ORDER BY SNAPSHOT_ID) AS IDS
  FROM latest GROUP BY S_ITEM, S_FACILITY, NETWORK
), dem AS (
  SELECT sc.ITEM_ID, sc.FACILITY_ID, sc.NETWORK,
         COALESCE(BOOLOR_AGG(f.TIMEZONE IS NULL OR f.TIMEZONE = ''), FALSE) AS MISSING_TZ,
         COALESCE(SUM(IFF(f.TIMEZONE IS NOT NULL AND f.TIMEZONE <> ''
                          AND d.DEMAND_ON BETWEEN DATEADD(day, -28, CONVERT_TIMEZONE(f.TIMEZONE, P_ASOF)::DATE)
                                              AND DATEADD(day, -1, CONVERT_TIMEZONE(f.TIMEZONE, P_ASOF)::DATE), d.QTY, 0)), 0) AS DEMAND
  FROM scopes sc
  LEFT JOIN CORE.DEMAND_EVENT d
    ON d.WORLD_ID = P_W AND d.ITEM_ID = sc.ITEM_ID
   AND (sc.NETWORK OR d.FACILITY_ID = sc.FACILITY_ID)
   AND d.INVENTORY_CLASS = P_CLASS AND (d.VISIBLE_AT IS NULL OR d.VISIBLE_AT <= P_ASOF)
  LEFT JOIN CORE.WORLD_FACILITY f ON f.WORLD_ID = d.WORLD_ID AND f.FACILITY_ID = d.FACILITY_ID
  GROUP BY sc.ITEM_ID, sc.FACILITY_ID, sc.NETWORK
), evaluated AS (
  SELECT sc.ITEM_ID, sc.FACILITY_ID, sc.NETWORK, a.AVAILABLE, a.IDS, d.DEMAND,
         CASE
           WHEN a.N IS NULL OR a.N = 0 THEN 'ABSTAIN:SNAPSHOT_MISSING'
           WHEN a.NEGATIVE THEN 'ABSTAIN:NEGATIVE_AVAILABLE'
           WHEN d.MISSING_TZ THEN 'ABSTAIN:TIMEZONE_MISSING'
           WHEN d.DEMAND = 0 THEN 'ZERO_DEMAND:ZERO_DEMAND'
           ELSE 'COMPLETE:' END AS K
  FROM scopes sc
  LEFT JOIN avail a ON a.ITEM_ID = sc.ITEM_ID AND EQUAL_NULL(a.FACILITY_ID, sc.FACILITY_ID) AND a.NETWORK = sc.NETWORK
  LEFT JOIN dem d ON d.ITEM_ID = sc.ITEM_ID AND EQUAL_NULL(d.FACILITY_ID, sc.FACILITY_ID) AND d.NETWORK = sc.NETWORK
)
SELECT ITEM_ID, FACILITY_ID, NETWORK, SPLIT_PART(K, ':', 1),
       IFF(K = 'COMPLETE:', TO_VARCHAR((AVAILABLE * 28)::NUMBER(38,6)), NULL),
       IFF(K = 'COMPLETE:', TO_VARCHAR(DEMAND::NUMBER(38,6)), NULL),
       IFF(K = 'COMPLETE:', TO_VARCHAR(ROUND((AVAILABLE * 28)::NUMBER(38,12) / DEMAND, 4, 'HALF_TO_EVEN')::NUMBER(38,4)), NULL),
       IFF(K = 'COMPLETE:', ((AVAILABLE * 28)::NUMBER(38,12) / DEMAND)::NUMBER(38,12), NULL),
       IFF(SPLIT_PART(K, ':', 2) = '', ARRAY_CONSTRUCT(), ARRAY_CONSTRUCT(SPLIT_PART(K, ':', 2))),
       IFF(K = 'COMPLETE:', '1.000000', NULL),
       NULL, 0, 0, '0.000000', 0,
       IFF(K IN ('COMPLETE:', 'ZERO_DEMAND:ZERO_DEMAND'), IDS, ARRAY_CONSTRUCT())
FROM evaluated
$$;

-- ---------------------------------------------------------------- M5 landed cost per accepted unit
CREATE OR REPLACE FUNCTION CORE.M5_RECEIPTS(P_W VARCHAR, P_ASOF TIMESTAMP_TZ)
RETURNS TABLE (RECEIPT_ID VARCHAR, PERIOD_DATE DATE, ITEM_ID VARCHAR, FACILITY_ID VARCHAR, SUPPLIER_ID VARCHAR, ACCEPTED_QTY NUMBER(38,6),
               GAPS ARRAY, COVERED BOOLEAN, CENTS NUMBER(38,0), FREIGHT_SHARE NUMBER(38,0))
AS
$$
WITH rec AS (
  SELECT * FROM CORE.RECEIPT WHERE WORLD_ID = P_W AND (VISIBLE_AT IS NULL OR VISIBLE_AT <= P_ASOF)
), comp AS (
  SELECT c.*,
         c.AMOUNT_MINOR IS NOT NULL AND c.AMOUNT_VISIBLE_AT IS NOT NULL AND c.AMOUNT_VISIBLE_AT <= P_ASOF AS AV,
         ROW_NUMBER() OVER (PARTITION BY c.RECEIPT_ID, c.KIND ORDER BY c.SEQ) AS K_RANK
  FROM CORE.COST_COMPONENT c JOIN rec r ON r.RECEIPT_ID = c.RECEIPT_ID
  WHERE c.WORLD_ID = P_W AND c.OBLIGATION_VISIBLE_AT IS NOT NULL AND c.OBLIGATION_VISIBLE_AT <= P_ASOF
), conv AS (
  SELECT comp.*,
         CASE
           WHEN NOT AV THEN 'AMOUNT_MISSING'
           WHEN KIND = 'MERCHANDISE' AND INVOICE_DATE IS NULL THEN 'INVOICE_DATE_MISSING'
           WHEN KIND <> 'MERCHANDISE' AND ECONOMIC_DATE IS NULL THEN 'ECONOMIC_DATE_MISSING'
           WHEN CURRENCY IS NULL OR CURRENCY = '' THEN 'CURRENCY_MISSING'
           WHEN FX_VISIBLE_AT IS NULL OR FX_VISIBLE_AT > P_ASOF OR FX_RATE IS NULL THEN 'FX_MISSING' END AS CONV_REASON
  FROM comp
), conv2 AS (
  SELECT conv.*, IFF(CONV_REASON IS NULL, ROUND(AMOUNT_MINOR * FX_RATE, 0, 'HALF_TO_EVEN'), NULL)::NUMBER(38,0) AS USD
  FROM conv
), first AS (
  SELECT * FROM conv2 WHERE K_RANK = 1
), pool_rows AS (
  SELECT COALESCE(c.ALLOCATION_POOL_ID, c.RECEIPT_ID) AS POOL_ID, c.RECEIPT_ID, c.AMOUNT_MINOR
  FROM conv2 c WHERE c.KIND = 'FREIGHT' AND c.AV
), members AS (
  SELECT p.POOL_ID, p.RECEIPT_ID, r.SEQ AS RSEQ,
         ROW_NUMBER() OVER (PARTITION BY p.POOL_ID ORDER BY r.SEQ) - 1 AS IDX,
         fw.CHARGEABLE_WEIGHT AS W, fw.VOLUME AS V, fm.USD AS MV, fw.FX_RATE AS FREIGHT_FX
  FROM (SELECT DISTINCT POOL_ID, RECEIPT_ID FROM pool_rows) p
  JOIN rec r ON r.RECEIPT_ID = p.RECEIPT_ID
  LEFT JOIN first fw ON fw.RECEIPT_ID = p.RECEIPT_ID AND fw.KIND = 'FREIGHT'
  LEFT JOIN first fm ON fm.RECEIPT_ID = p.RECEIPT_ID AND fm.KIND = 'MERCHANDISE'
), amounts AS (
  SELECT POOL_ID, COUNT(DISTINCT AMOUNT_MINOR) AS N_AMOUNTS, MAX(AMOUNT_MINOR) AS TOTAL_MINOR FROM pool_rows GROUP BY POOL_ID
), pools AS (
  SELECT m.POOL_ID, MAX(a.N_AMOUNTS) AS N_AMOUNTS, MAX(a.TOTAL_MINOR) AS TOTAL_MINOR,
         MAX(IFF(m.IDX = 0, m.FREIGHT_FX, NULL)) AS FX0,
         COUNT(*) AS N, COUNT(m.W) AS NW, SUM(m.W) AS SW, COUNT(m.V) AS NV, SUM(m.V) AS SV, COUNT(m.MV) AS NM, SUM(m.MV) AS SM
  FROM members m JOIN amounts a ON a.POOL_ID = m.POOL_ID GROUP BY m.POOL_ID
), basis AS (
  SELECT m.POOL_ID, m.RECEIPT_ID, m.IDX,
         CASE WHEN p.NW = p.N AND p.SW > 0 THEN m.W WHEN p.NV = p.N AND p.SV > 0 THEN m.V WHEN p.NM = p.N AND p.SM > 0 THEN m.MV END AS WT,
         CASE WHEN p.NW = p.N AND p.SW > 0 THEN p.SW WHEN p.NV = p.N AND p.SV > 0 THEN p.SV WHEN p.NM = p.N AND p.SM > 0 THEN p.SM END AS WSUM,
         IFF(p.N_AMOUNTS = 1 AND p.FX0 IS NOT NULL, ROUND(p.TOTAL_MINOR * p.FX0, 0, 'HALF_TO_EVEN'), NULL)::NUMBER(38,0) AS TOTAL_USD
  FROM members m JOIN pools p ON p.POOL_ID = m.POOL_ID
), raw AS (
  SELECT basis.*, (TOTAL_USD::NUMBER(38,12) * WT) / WSUM AS RAW_SHARE
  FROM basis WHERE WT IS NOT NULL AND TOTAL_USD IS NOT NULL
), rounded AS (
  SELECT raw.*, ROUND(RAW_SHARE, 0, 'HALF_TO_EVEN') AS R0,
         TOTAL_USD - SUM(ROUND(RAW_SHARE, 0, 'HALF_TO_EVEN')) OVER (PARTITION BY POOL_ID) AS DRIFT
  FROM raw
), ranked AS (
  SELECT rounded.*,
         IFF(DRIFT > 0,
             ROW_NUMBER() OVER (PARTITION BY POOL_ID ORDER BY (RAW_SHARE - R0) DESC, IDX ASC),
             ROW_NUMBER() OVER (PARTITION BY POOL_ID ORDER BY (RAW_SHARE - R0) ASC, IDX DESC)) AS RK
  FROM rounded
), shares AS (
  SELECT b.RECEIPT_ID,
         IFF(COUNT(*) = COUNT(rk.R0), SUM(rk.R0 + IFF(rk.RK <= ABS(rk.DRIFT), SIGN(rk.DRIFT), 0)), NULL)::NUMBER(38,0) AS SHARE
  FROM basis b LEFT JOIN ranked rk ON rk.POOL_ID = b.POOL_ID AND rk.RECEIPT_ID = b.RECEIPT_ID
  GROUP BY b.RECEIPT_ID
), per AS (
  SELECT r.RECEIPT_ID, r.ACCEPTED_ON, r.ITEM_ID, r.FACILITY_ID, r.SUPPLIER_ID, r.ACCEPTED_QTY, r.INCOTERM, r.CALENDAR_ID,
         r.ORIGIN_COUNTRY, r.DEST_COUNTRY,
         r.INCOTERM IN ('EXW', 'FCA', 'DAP', 'DDP') AS SUPPORTED,
         NULLIF(r.ORIGIN_COUNTRY, '') IS NOT NULL AND NULLIF(r.DEST_COUNTRY, '') IS NOT NULL AS HAS_COUNTRIES,
         fm.RECEIPT_ID IS NOT NULL AS HAS_M, fm.AV AS M_AV, fm.CONV_REASON AS M_R,
         ff.RECEIPT_ID IS NOT NULL AS HAS_F, ff.AV AS F_AV, ff.CONV_REASON AS F_R,
         fd.RECEIPT_ID IS NOT NULL AS HAS_D, fd.AV AS D_AV, fd.CONV_REASON AS D_R, fd.CUSTOMS_VALUE_MINOR AS D_CV,
         fb.RECEIPT_ID IS NOT NULL AS HAS_B, fb.AV AS B_AV, fb.CONV_REASON AS B_R, fb.CUSTOMS_VALUE_MINOR AS B_CV,
         fi.RECEIPT_ID IS NOT NULL AS HAS_I, fi.AV AS I_AV, fi.CONV_REASON AS I_R, fi.MERCHANDISE_VALUE_MINOR AS I_MV,
         fa.RECEIPT_ID IS NOT NULL AS HAS_A, fa.AV AS A_AV, fa.CONV_REASON AS A_R,
         fc.RECEIPT_ID IS NOT NULL AS HAS_C, fc.AV AS C_AV, fc.CONV_REASON AS C_R,
         COALESCE(dbc.CHARGED, FALSE) AS DUTY_BUYER_CHARGED,
         s.SHARE
  FROM rec r
  LEFT JOIN (SELECT RECEIPT_ID, BOOLOR_AGG(COALESCE(BUYER_CHARGED, FALSE)) AS CHARGED FROM conv2 WHERE KIND = 'DUTY' GROUP BY RECEIPT_ID) dbc
    ON dbc.RECEIPT_ID = r.RECEIPT_ID
  LEFT JOIN first fm ON fm.RECEIPT_ID = r.RECEIPT_ID AND fm.KIND = 'MERCHANDISE'
  LEFT JOIN first ff ON ff.RECEIPT_ID = r.RECEIPT_ID AND ff.KIND = 'FREIGHT'
  LEFT JOIN first fd ON fd.RECEIPT_ID = r.RECEIPT_ID AND fd.KIND = 'DUTY'
  LEFT JOIN first fb ON fb.RECEIPT_ID = r.RECEIPT_ID AND fb.KIND = 'BROKERAGE'
  LEFT JOIN first fi ON fi.RECEIPT_ID = r.RECEIPT_ID AND fi.KIND = 'INSURANCE'
  LEFT JOIN first fa ON fa.RECEIPT_ID = r.RECEIPT_ID AND fa.KIND = 'ACCESSORIAL'
  LEFT JOIN first fc ON fc.RECEIPT_ID = r.RECEIPT_ID AND fc.KIND = 'CREDIT'
  LEFT JOIN shares s ON s.RECEIPT_ID = r.RECEIPT_ID
), req AS (
  SELECT per.*,
         INCOTERM IN ('EXW', 'FCA') OR (INCOTERM IN ('DAP', 'DDP') AND HAS_F) AS FREIGHT_REQUIRED,
         SUPPORTED AND HAS_COUNTRIES AND ORIGIN_COUNTRY <> DEST_COUNTRY
           AND (INCOTERM IN ('EXW', 'FCA', 'DAP') OR (INCOTERM = 'DDP' AND DUTY_BUYER_CHARGED)) AS DUTY_REQUIRED
  FROM per
), g AS (
  SELECT req.*,
         ARRAY_CONSTRUCT_COMPACT(
           IFF(NULLIF(CALENDAR_ID, '') IS NULL, 'CALENDAR_MISSING', NULL),
           IFF(NULLIF(INCOTERM, '') IS NULL, 'INCOTERM_MISSING', IFF(NOT SUPPORTED, 'INCOTERM_UNSUPPORTED', NULL)),
           IFF(NOT HAS_COUNTRIES, 'COUNTRY_MISSING', NULL),
           IFF(NOT HAS_M OR NOT M_AV, 'MERCHANDISE_AMOUNT_MISSING',
               CASE M_R WHEN 'INVOICE_DATE_MISSING' THEN 'MERCHANDISE_INVOICE_DATE_MISSING' WHEN 'ECONOMIC_DATE_MISSING' THEN 'MERCHANDISE_ECONOMIC_DATE_MISSING'
                        WHEN 'CURRENCY_MISSING' THEN 'CURRENCY_MISSING' WHEN 'FX_MISSING' THEN 'MERCHANDISE_FX_MISSING' END),
           IFF(FREIGHT_REQUIRED,
               IFF(NOT HAS_F OR NOT F_AV, 'FREIGHT_AMOUNT_MISSING',
                   CASE F_R WHEN 'ECONOMIC_DATE_MISSING' THEN 'FREIGHT_ECONOMIC_DATE_MISSING' WHEN 'CURRENCY_MISSING' THEN 'CURRENCY_MISSING'
                            WHEN 'FX_MISSING' THEN 'FREIGHT_FX_MISSING' END), NULL),
           IFF(FREIGHT_REQUIRED AND HAS_F AND F_AV AND SHARE IS NULL, 'FREIGHT_ALLOCATION_BASIS_MISSING', NULL),
           IFF(DUTY_REQUIRED,
               IFF(NOT HAS_D OR NOT D_AV, 'DUTY_AMOUNT_MISSING',
                   CASE D_R WHEN 'ECONOMIC_DATE_MISSING' THEN 'DUTY_ECONOMIC_DATE_MISSING' WHEN 'CURRENCY_MISSING' THEN 'CURRENCY_MISSING'
                            WHEN 'FX_MISSING' THEN 'DUTY_FX_MISSING' END), NULL),
           IFF(DUTY_REQUIRED AND HAS_D AND D_AV AND D_CV IS NULL, 'DUTY_ALLOCATION_BASIS_MISSING', NULL),
           IFF(HAS_B,
               IFF(NOT B_AV, 'BROKERAGE_AMOUNT_MISSING',
                   CASE B_R WHEN 'ECONOMIC_DATE_MISSING' THEN 'BROKERAGE_ECONOMIC_DATE_MISSING' WHEN 'CURRENCY_MISSING' THEN 'CURRENCY_MISSING'
                            WHEN 'FX_MISSING' THEN 'BROKERAGE_FX_MISSING' END), NULL),
           IFF(HAS_B AND B_AV AND B_CV IS NULL, 'BROKERAGE_ALLOCATION_BASIS_MISSING', NULL),
           IFF(HAS_I,
               IFF(NOT I_AV, 'INSURANCE_AMOUNT_MISSING',
                   CASE I_R WHEN 'ECONOMIC_DATE_MISSING' THEN 'INSURANCE_ECONOMIC_DATE_MISSING' WHEN 'CURRENCY_MISSING' THEN 'CURRENCY_MISSING'
                            WHEN 'FX_MISSING' THEN 'INSURANCE_FX_MISSING' END), NULL),
           IFF(HAS_I AND I_AV AND I_MV IS NULL AND NOT HAS_M, 'INSURANCE_ALLOCATION_BASIS_MISSING', NULL),
           IFF(HAS_A,
               IFF(NOT A_AV, 'ACCESSORIAL_AMOUNT_MISSING',
                   CASE A_R WHEN 'ECONOMIC_DATE_MISSING' THEN 'ACCESSORIAL_ECONOMIC_DATE_MISSING' WHEN 'CURRENCY_MISSING' THEN 'CURRENCY_MISSING'
                            WHEN 'FX_MISSING' THEN 'ACCESSORIAL_FX_MISSING' END), NULL),
           IFF(HAS_C,
               IFF(NOT C_AV, 'CREDIT_AMOUNT_MISSING',
                   CASE C_R WHEN 'ECONOMIC_DATE_MISSING' THEN 'CREDIT_ECONOMIC_DATE_MISSING' WHEN 'CURRENCY_MISSING' THEN 'CURRENCY_MISSING'
                            WHEN 'FX_MISSING' THEN 'CREDIT_FX_MISSING' END), NULL)
         ) AS GAPS
  FROM req
), sums AS (
  SELECT RECEIPT_ID,
         SUM(IFF(KIND IN ('MERCHANDISE', 'INSURANCE', 'BROKERAGE', 'ACCESSORIAL'), USD, 0)) AS BASE_USD,
         SUM(IFF(KIND = 'DUTY', USD, 0)) AS DUTY_USD,
         SUM(IFF(KIND = 'CREDIT', USD, 0)) AS CREDIT_USD
  FROM conv2 WHERE USD IS NOT NULL GROUP BY RECEIPT_ID
), cents AS (
  SELECT g.RECEIPT_ID,
         COALESCE(sums.BASE_USD, 0) + IFF(g.DUTY_REQUIRED, COALESCE(sums.DUTY_USD, 0), 0)
         + IFF(g.SHARE IS NOT NULL AND g.HAS_F, g.SHARE, 0) - COALESCE(sums.CREDIT_USD, 0) AS CENTS
  FROM g LEFT JOIN sums ON sums.RECEIPT_ID = g.RECEIPT_ID
)
SELECT g.RECEIPT_ID, g.ACCEPTED_ON, g.ITEM_ID, g.FACILITY_ID, g.SUPPLIER_ID, g.ACCEPTED_QTY, g.GAPS, ARRAY_SIZE(g.GAPS) = 0,
       cents.CENTS::NUMBER(38,0), g.SHARE
FROM g JOIN cents ON cents.RECEIPT_ID = g.RECEIPT_ID
$$;

CREATE OR REPLACE FUNCTION CORE.LANDED_RESULT_M5(P_W VARCHAR, P_PS DATE, P_PE DATE, P_ASOF TIMESTAMP_TZ, P_ITEM VARCHAR, P_FACILITY VARCHAR,
                                                 P_SUPPLIER VARCHAR)
RETURNS TABLE (STATUS VARCHAR, NUMERATOR VARCHAR, DENOMINATOR VARCHAR, DISPLAY VARCHAR, VALUE_NUM NUMBER(38,12), REASONS ARRAY, COVERAGE VARCHAR,
               DIAGNOSTIC_DISPLAY VARCHAR, EXCLUDED_COUNT NUMBER, AFFECTED_COMMITMENTS NUMBER, AFFECTED_UNITS VARCHAR, UNRESOLVED_RECORDS NUMBER,
               EVIDENCE_IDS ARRAY)
AS
$$
SELECT {{LANDED_AGG}}
FROM TABLE(CORE.M5_RECEIPTS(P_W, P_ASOF))
WHERE PERIOD_DATE BETWEEN P_PS AND P_PE
  AND (P_ITEM IS NULL OR ITEM_ID = P_ITEM) AND (P_FACILITY IS NULL OR FACILITY_ID = P_FACILITY) AND (P_SUPPLIER IS NULL OR SUPPLIER_ID = P_SUPPLIER)
$$;
