-- Persona roles. Run by ACCOUNTADMIN through `deploy.py personas`; account-level changes are limited to five
-- CONCORDIA_* roles, their grants to SYSADMIN and the deploying user, warehouse usage and CORTEX_USER.
-- Object grants and the cost masking policy live in 06_semantic.sql, owned by CONCORDIA_ADMIN.

CREATE ROLE IF NOT EXISTS CONCORDIA_PLANNER COMMENT = 'Supply planning persona. No cost visibility.';
CREATE ROLE IF NOT EXISTS CONCORDIA_PROCUREMENT COMMENT = 'Procurement persona. Cost visible.';
CREATE ROLE IF NOT EXISTS CONCORDIA_LOGISTICS COMMENT = 'Logistics persona. No cost visibility.';
CREATE ROLE IF NOT EXISTS CONCORDIA_EXECUTIVE COMMENT = 'Executive persona. Cost visible.';
CREATE ROLE IF NOT EXISTS CONCORDIA_COST_READER COMMENT = 'Holders see landed cost values through the cost masking policy.';

GRANT ROLE CONCORDIA_COST_READER TO ROLE CONCORDIA_PROCUREMENT;
GRANT ROLE CONCORDIA_COST_READER TO ROLE CONCORDIA_EXECUTIVE;
GRANT ROLE CONCORDIA_COST_READER TO ROLE CONCORDIA_AUDITOR;
GRANT ROLE CONCORDIA_COST_READER TO ROLE CONCORDIA_ADMIN;

GRANT ROLE CONCORDIA_PLANNER TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_PROCUREMENT TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_LOGISTICS TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_EXECUTIVE TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_COST_READER TO ROLE SYSADMIN;
GRANT ROLE CONCORDIA_PLANNER TO USER IDENTIFIER($CONCORDIA_USER);
GRANT ROLE CONCORDIA_PROCUREMENT TO USER IDENTIFIER($CONCORDIA_USER);
GRANT ROLE CONCORDIA_LOGISTICS TO USER IDENTIFIER($CONCORDIA_USER);
GRANT ROLE CONCORDIA_EXECUTIVE TO USER IDENTIFIER($CONCORDIA_USER);

GRANT USAGE ON WAREHOUSE CONCORDIA_APP_WH TO ROLE CONCORDIA_PLANNER;
GRANT USAGE ON WAREHOUSE CONCORDIA_APP_WH TO ROLE CONCORDIA_PROCUREMENT;
GRANT USAGE ON WAREHOUSE CONCORDIA_APP_WH TO ROLE CONCORDIA_LOGISTICS;
GRANT USAGE ON WAREHOUSE CONCORDIA_APP_WH TO ROLE CONCORDIA_EXECUTIVE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONCORDIA_PLANNER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONCORDIA_PROCUREMENT;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONCORDIA_LOGISTICS;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONCORDIA_EXECUTIVE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONCORDIA_AUDITOR;
