-- Patient 360 raw tables for the 18 Synthea CSVs plus parsed document sections.
-- Idempotent: dependent analyst objects are dropped, then each table is replaced.
-- Re-run 30_core_views.sql, 40_semantic_view.sql, and 90_roles_grants.sql after this file.
-- Re-run 20_load.sql after this file. CREATE OR REPLACE leaves the tables empty.
-- Column order matches the inspected headers. A newly inserted source column will shift fields.
-- Codes, ZIP, NPI, SSN, DRIVERS, and PASSPORT are text. Blank CSV fields become NULL.
-- Primary keys are declared NOT ENFORCED. tests/expected_checks.sql proves uniqueness.
-- Tables without a surrogate id do not get a primary key. Load row number is the grain there.

USE DATABASE PATIENT_360;
USE SCHEMA RAW;
USE WAREHOUSE PATIENT_360_WH;

DROP SEMANTIC VIEW IF EXISTS PATIENT_360.CORE.SEM_MEMBER;
DROP VIEW IF EXISTS PATIENT_360.CORE.RISK_SCORE;
DROP VIEW IF EXISTS PATIENT_360.CORE.RISK_COHORT;
DROP VIEW IF EXISTS PATIENT_360.CORE.RISK_FEATURE;
DROP VIEW IF EXISTS PATIENT_360.CORE.MEMBER_ENCOUNTER_CLAIM;
DROP VIEW IF EXISTS PATIENT_360.CORE.MEMBER_COVERAGE;
DROP VIEW IF EXISTS PATIENT_360.CORE.MEMBER_SUMMARY;
DROP VIEW IF EXISTS PATIENT_360.CORE.DOCUMENT_SECTION;
DROP VIEW IF EXISTS PATIENT_360.CORE.CLAIM_LINE;
DROP VIEW IF EXISTS PATIENT_360.CORE.CLAIM;
DROP VIEW IF EXISTS PATIENT_360.CORE.PROVIDER;
DROP VIEW IF EXISTS PATIENT_360.CORE.ORGANIZATION;
DROP VIEW IF EXISTS PATIENT_360.CORE.PAYER;
DROP VIEW IF EXISTS PATIENT_360.CORE.PAYER_TRANSITION;
DROP VIEW IF EXISTS PATIENT_360.CORE.SUPPLY;
DROP VIEW IF EXISTS PATIENT_360.CORE.DEVICE;
DROP VIEW IF EXISTS PATIENT_360.CORE.IMAGING_STUDY;
DROP VIEW IF EXISTS PATIENT_360.CORE.IMMUNIZATION;
DROP VIEW IF EXISTS PATIENT_360.CORE.CAREPLAN;
DROP VIEW IF EXISTS PATIENT_360.CORE.ALLERGY;
DROP VIEW IF EXISTS PATIENT_360.CORE.PROCEDURE;
DROP VIEW IF EXISTS PATIENT_360.CORE.OBSERVATION;
DROP VIEW IF EXISTS PATIENT_360.CORE.MEDICATION;
DROP VIEW IF EXISTS PATIENT_360.CORE.CONDITION;
DROP VIEW IF EXISTS PATIENT_360.CORE.ENCOUNTER;
DROP VIEW IF EXISTS PATIENT_360.CORE.PATIENT;

CREATE OR REPLACE TABLE PATIENT_360.RAW.PATIENTS (
    ID VARCHAR(36) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    DEATHDATE DATE,
    SSN VARCHAR(11) NOT NULL,
    DRIVERS VARCHAR(16),
    PASSPORT VARCHAR(16),
    PREFIX VARCHAR(16),
    FIRST VARCHAR(64) NOT NULL,
    MIDDLE VARCHAR(64),
    LAST VARCHAR(64) NOT NULL,
    SUFFIX VARCHAR(16),
    MAIDEN VARCHAR(64),
    MARITAL VARCHAR(16),
    RACE VARCHAR(32) NOT NULL,
    ETHNICITY VARCHAR(32) NOT NULL,
    GENDER VARCHAR(16) NOT NULL,
    BIRTHPLACE VARCHAR(256) NOT NULL,
    ADDRESS VARCHAR(256) NOT NULL,
    CITY VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    COUNTY VARCHAR(64) NOT NULL,
    FIPS VARCHAR(8),
    ZIP VARCHAR(16) NOT NULL,
    LAT NUMBER(20,15) NOT NULL,
    LON NUMBER(20,15) NOT NULL,
    HEALTHCARE_EXPENSES NUMBER(18,2) NOT NULL,
    HEALTHCARE_COVERAGE NUMBER(18,2) NOT NULL,
    INCOME NUMBER(38,0) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_PATIENTS PRIMARY KEY (ID) NOT ENFORCED
)
COMMENT = 'Patient demographics. SSN, DRIVERS, and PASSPORT remain in RAW and are omitted from CORE. Expected rows in this extract: 108. Source file patients.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.ENCOUNTERS (
    ID VARCHAR(36) NOT NULL,
    "START" TIMESTAMP_NTZ NOT NULL,
    "STOP" TIMESTAMP_NTZ NOT NULL,
    PATIENT VARCHAR(36) NOT NULL,
    ORGANIZATION VARCHAR(36) NOT NULL,
    PROVIDER VARCHAR(36) NOT NULL,
    PAYER VARCHAR(36) NOT NULL,
    ENCOUNTERCLASS VARCHAR(32) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    BASE_ENCOUNTER_COST NUMBER(18,2) NOT NULL,
    TOTAL_CLAIM_COST NUMBER(18,2) NOT NULL,
    PAYER_COVERAGE NUMBER(18,2) NOT NULL,
    REASONCODE VARCHAR(32),
    REASONDESCRIPTION VARCHAR(512),
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_ENCOUNTERS PRIMARY KEY (ID) NOT ENFORCED
)
COMMENT = 'Encounter header. Id is unique. PATIENT, ORGANIZATION, PROVIDER, and PAYER are foreign keys on this extract. Expected rows in this extract: 5571. Source file encounters.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.CONDITIONS (
    "START" DATE NOT NULL,
    "STOP" DATE,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    SYSTEM VARCHAR(64) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Conditions. No surrogate id. SYSTEM is http://snomed.info/sct on every row of this extract. Business key PATIENT, ENCOUNTER, CODE, START is unique here. Expected rows in this extract: 3517. Source file conditions.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.MEDICATIONS (
    "START" TIMESTAMP_NTZ NOT NULL,
    "STOP" TIMESTAMP_NTZ,
    PATIENT VARCHAR(36) NOT NULL,
    PAYER VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(1024) NOT NULL,
    BASE_COST NUMBER(18,2) NOT NULL,
    PAYER_COVERAGE NUMBER(18,2) NOT NULL,
    DISPENSES NUMBER(38,0) NOT NULL,
    TOTALCOST NUMBER(18,2) NOT NULL,
    REASONCODE VARCHAR(32),
    REASONDESCRIPTION VARCHAR(512),
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Medications. CODE is RxNorm. PATIENT, ENCOUNTER, CODE, START is not unique: 9 pairs differ by STOP and DISPENSES. Expected rows in this extract: 3850. Source file medications.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.OBSERVATIONS (
    DATE TIMESTAMP_NTZ NOT NULL,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36),
    CATEGORY VARCHAR(32),
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    VALUE VARCHAR(512) NOT NULL,
    UNITS VARCHAR(64),
    TYPE VARCHAR(16) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Observations. CODE is LOINC-style text. VALUE is mixed numeric and text. 3060 rows have a blank ENCOUNTER and a blank CATEGORY, and those are the same rows. Expected rows in this extract: 68648. Source file observations.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.PROCEDURES (
    "START" TIMESTAMP_NTZ NOT NULL,
    "STOP" TIMESTAMP_NTZ NOT NULL,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    SYSTEM VARCHAR(64) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(1024) NOT NULL,
    BASE_COST NUMBER(18,2) NOT NULL,
    REASONCODE VARCHAR(32),
    REASONDESCRIPTION VARCHAR(512),
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Procedures. No surrogate id. SYSTEM is http://snomed.info/sct on this extract. Business key PATIENT, ENCOUNTER, CODE, START is unique here. Expected rows in this extract: 15884. Source file procedures.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.ALLERGIES (
    "START" DATE NOT NULL,
    "STOP" DATE,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    SYSTEM VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    CATEGORY VARCHAR(32) NOT NULL,
    REACTION1 VARCHAR(32),
    DESCRIPTION1 VARCHAR(512),
    SEVERITY1 VARCHAR(16),
    REACTION2 VARCHAR(32),
    DESCRIPTION2 VARCHAR(512),
    SEVERITY2 VARCHAR(16),
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Allergies. CODE is SNOMED. STOP is empty on this extract. Business key PATIENT, ENCOUNTER, CODE, START is unique here. Expected rows in this extract: 105. Source file allergies.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.CAREPLANS (
    ID VARCHAR(36) NOT NULL,
    "START" DATE NOT NULL,
    "STOP" DATE,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    REASONCODE VARCHAR(32),
    REASONDESCRIPTION VARCHAR(512),
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_CAREPLANS PRIMARY KEY (ID) NOT ENFORCED
)
COMMENT = 'Care plans. Id is unique. Expected rows in this extract: 349. Source file careplans.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.IMMUNIZATIONS (
    DATE TIMESTAMP_NTZ NOT NULL,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    BASE_COST NUMBER(18,2) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Immunizations. No surrogate id. Business key PATIENT, ENCOUNTER, CODE, DATE is unique here. Expected rows in this extract: 1549. Source file immunizations.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.IMAGING_STUDIES (
    ID VARCHAR(36) NOT NULL,
    DATE TIMESTAMP_NTZ NOT NULL,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    SERIES_UID VARCHAR(128) NOT NULL,
    BODYSITE_CODE VARCHAR(32) NOT NULL,
    BODYSITE_DESCRIPTION VARCHAR(512) NOT NULL,
    MODALITY_CODE VARCHAR(16) NOT NULL,
    MODALITY_DESCRIPTION VARCHAR(128) NOT NULL,
    INSTANCE_UID VARCHAR(128) NOT NULL,
    SOP_CODE VARCHAR(64) NOT NULL,
    SOP_DESCRIPTION VARCHAR(256) NOT NULL,
    PROCEDURE_CODE VARCHAR(32) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_IMAGING_STUDIES PRIMARY KEY (ID, SERIES_UID, INSTANCE_UID) NOT ENFORCED
)
COMMENT = 'Imaging study metadata. Id is unique. No image pixels are loaded. Expected rows in this extract: 478. Source file imaging_studies.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.DEVICES (
    "START" TIMESTAMP_NTZ NOT NULL,
    "STOP" TIMESTAMP_NTZ,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    UDI VARCHAR(256) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Devices. No surrogate id. UDI is present on every row of this extract. Expected rows in this extract: 524. Source file devices.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.SUPPLIES (
    DATE DATE NOT NULL,
    PATIENT VARCHAR(36) NOT NULL,
    ENCOUNTER VARCHAR(36) NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    QUANTITY NUMBER(38,0) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Supplies. No surrogate id. PATIENT, ENCOUNTER, CODE, DATE is not unique: 11 pairs on this extract. Expected rows in this extract: 2225. Source file supplies.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.PAYER_TRANSITIONS (
    PATIENT VARCHAR(36) NOT NULL,
    MEMBERID VARCHAR(36),
    START_DATE TIMESTAMP_NTZ NOT NULL,
    END_DATE TIMESTAMP_NTZ NOT NULL,
    PAYER VARCHAR(36) NOT NULL,
    SECONDARY_PAYER VARCHAR(36),
    PLAN_OWNERSHIP VARCHAR(32),
    OWNER_NAME VARCHAR(256),
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Coverage spans. MEMBERID is a span id, empty on 1082 rows, and is not patients.Id. The patient UUID is the member key. Expected rows in this extract: 3815. Source file payer_transitions.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.PAYERS (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    OWNERSHIP VARCHAR(32) NOT NULL,
    ADDRESS VARCHAR(256),
    CITY VARCHAR(64),
    STATE_HEADQUARTERED VARCHAR(32),
    ZIP VARCHAR(16),
    PHONE VARCHAR(64),
    AMOUNT_COVERED NUMBER(18,2) NOT NULL,
    AMOUNT_UNCOVERED NUMBER(18,2) NOT NULL,
    REVENUE NUMBER(18,2) NOT NULL,
    COVERED_ENCOUNTERS NUMBER(38,0) NOT NULL,
    UNCOVERED_ENCOUNTERS NUMBER(38,0) NOT NULL,
    COVERED_MEDICATIONS NUMBER(38,0) NOT NULL,
    UNCOVERED_MEDICATIONS NUMBER(38,0) NOT NULL,
    COVERED_PROCEDURES NUMBER(38,0) NOT NULL,
    UNCOVERED_PROCEDURES NUMBER(38,0) NOT NULL,
    COVERED_IMMUNIZATIONS NUMBER(38,0) NOT NULL,
    UNCOVERED_IMMUNIZATIONS NUMBER(38,0) NOT NULL,
    UNIQUE_CUSTOMERS NUMBER(38,0) NOT NULL,
    QOLS_AVG NUMBER(18,16) NOT NULL,
    MEMBER_MONTHS NUMBER(38,0) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_PAYERS PRIMARY KEY (ID) NOT ENFORCED
)
COMMENT = 'Payers. Address, city, state, ZIP, and phone are empty on every row of this extract. Expected rows in this extract: 10. Source file payers.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.ORGANIZATIONS (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    ADDRESS VARCHAR(256) NOT NULL,
    CITY VARCHAR(64) NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    ZIP VARCHAR(16) NOT NULL,
    LAT NUMBER(20,15) NOT NULL,
    LON NUMBER(20,15) NOT NULL,
    PHONE VARCHAR(64) NOT NULL,
    REVENUE NUMBER(18,2) NOT NULL,
    UTILIZATION NUMBER(38,0) NOT NULL,
    NPI VARCHAR(16) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_ORGANIZATIONS PRIMARY KEY (ID) NOT ENFORCED
)
COMMENT = 'Organizations. Id is unique. ZIP is text so leading zeros are kept. NPI is text. Expected rows in this extract: 278. Source file organizations.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.PROVIDERS (
    ID VARCHAR(36) NOT NULL,
    ORGANIZATION VARCHAR(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    GENDER VARCHAR(16) NOT NULL,
    SPECIALITY VARCHAR(64) NOT NULL,
    ADDRESS VARCHAR(256) NOT NULL,
    CITY VARCHAR(64) NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    ZIP VARCHAR(16) NOT NULL,
    LAT NUMBER(20,15) NOT NULL,
    LON NUMBER(20,15) NOT NULL,
    ENCOUNTERS NUMBER(38,0) NOT NULL,
    PROCEDURES NUMBER(38,0) NOT NULL,
    NPI VARCHAR(16) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_PROVIDERS PRIMARY KEY (ID) NOT ENFORCED
)
COMMENT = 'Providers. Id is unique. The source header SPECIALITY is preserved. ENCOUNTERS and PROCEDURES are counts on the provider row, not child keys. Expected rows in this extract: 278. Source file providers.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.CLAIMS (
    ID VARCHAR(36) NOT NULL,
    PATIENTID VARCHAR(36) NOT NULL,
    PROVIDERID VARCHAR(36) NOT NULL,
    PRIMARYPATIENTINSURANCEID VARCHAR(36),
    SECONDARYPATIENTINSURANCEID VARCHAR(36),
    DEPARTMENTID NUMBER(38,0) NOT NULL,
    PATIENTDEPARTMENTID NUMBER(38,0) NOT NULL,
    DIAGNOSIS1 VARCHAR(32) NOT NULL,
    DIAGNOSIS2 VARCHAR(32),
    DIAGNOSIS3 VARCHAR(32),
    DIAGNOSIS4 VARCHAR(32),
    DIAGNOSIS5 VARCHAR(32),
    DIAGNOSIS6 VARCHAR(32),
    DIAGNOSIS7 VARCHAR(32),
    DIAGNOSIS8 VARCHAR(32),
    REFERRINGPROVIDERID VARCHAR(36),
    APPOINTMENTID VARCHAR(36) NOT NULL,
    CURRENTILLNESSDATE TIMESTAMP_NTZ NOT NULL,
    SERVICEDATE TIMESTAMP_NTZ NOT NULL,
    SUPERVISINGPROVIDERID VARCHAR(36) NOT NULL,
    STATUS1 VARCHAR(16) NOT NULL,
    STATUS2 VARCHAR(16),
    STATUSP VARCHAR(16) NOT NULL,
    OUTSTANDING1 NUMBER(18,2) NOT NULL,
    OUTSTANDING2 NUMBER(18,2),
    OUTSTANDINGP NUMBER(18,2) NOT NULL,
    LASTBILLEDDATE1 TIMESTAMP_NTZ NOT NULL,
    LASTBILLEDDATE2 TIMESTAMP_NTZ,
    LASTBILLEDDATEP TIMESTAMP_NTZ NOT NULL,
    HEALTHCARECLAIMTYPEID1 NUMBER(38,0) NOT NULL,
    HEALTHCARECLAIMTYPEID2 NUMBER(38,0) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_CLAIMS PRIMARY KEY (ID) NOT ENFORCED
)
COMMENT = 'Claims. APPOINTMENTID is encounters.Id on every row. PRIMARYPATIENTINSURANCEID and SECONDARYPATIENTINSURANCEID are payer ids when filled, not member ids. REFERRINGPROVIDERID is empty on every row. DEPARTMENTID is not organizations.Id. Expected rows in this extract: 9421. Source file claims.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.CLAIMS_TRANSACTIONS (
    ID VARCHAR(36) NOT NULL,
    CLAIMID VARCHAR(36) NOT NULL,
    CHARGEID NUMBER(38,0) NOT NULL,
    PATIENTID VARCHAR(36) NOT NULL,
    TYPE VARCHAR(16) NOT NULL,
    AMOUNT NUMBER(18,2),
    METHOD VARCHAR(16),
    FROMDATE TIMESTAMP_NTZ NOT NULL,
    TODATE TIMESTAMP_NTZ NOT NULL,
    PLACEOFSERVICE VARCHAR(36) NOT NULL,
    PROCEDURECODE VARCHAR(32) NOT NULL,
    MODIFIER1 VARCHAR(16),
    MODIFIER2 VARCHAR(16),
    DIAGNOSISREF1 NUMBER(38,0) NOT NULL,
    DIAGNOSISREF2 NUMBER(38,0),
    DIAGNOSISREF3 NUMBER(38,0),
    DIAGNOSISREF4 NUMBER(38,0),
    UNITS NUMBER(38,0) NOT NULL,
    DEPARTMENTID NUMBER(38,0) NOT NULL,
    NOTES VARCHAR(1024) NOT NULL,
    UNITAMOUNT NUMBER(18,2) NOT NULL,
    TRANSFEROUTID NUMBER(38,0),
    TRANSFERTYPE VARCHAR(16),
    PAYMENTS NUMBER(18,2) NOT NULL,
    ADJUSTMENTS NUMBER(18,2) NOT NULL,
    TRANSFERS NUMBER(18,2),
    OUTSTANDING NUMBER(18,2) NOT NULL,
    APPOINTMENTID VARCHAR(36) NOT NULL,
    LINENOTE VARCHAR(1024),
    PATIENTINSURANCEID VARCHAR(36),
    FEESCHEDULEID NUMBER(38,0) NOT NULL,
    PROVIDERID VARCHAR(36) NOT NULL,
    SUPERVISINGPROVIDERID VARCHAR(36) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_CLAIMS_TRANSACTIONS PRIMARY KEY (ID) NOT ENFORCED
)
COMMENT = 'Claim lines. ID is unique. NOTES is the charge description on every row, not a clinical document. LINENOTE is empty on every row. TRANSFERTYPE mixes letters and digits and stays text. Expected rows in this extract: 85047. Source file claims_transactions.csv.';

CREATE OR REPLACE TABLE PATIENT_360.RAW.DOCUMENT_SECTION (
    DOCUMENT_ID VARCHAR(36) NOT NULL,
    PATIENT_ID VARCHAR(36) NOT NULL,
    EFFECTIVE_TIME VARCHAR(32),
    SECTION_LOINC VARCHAR(16) NOT NULL,
    SECTION_TITLE VARCHAR(256) NOT NULL,
    ELEMENT_ID VARCHAR(128) NOT NULL,
    TEXT VARCHAR(16777216) NOT NULL,
    CODE VARCHAR(64),
    CODE_SYSTEM VARCHAR(128),
    CCDA_SOURCE_FILE VARCHAR(1024) NOT NULL,
    ELEMENT_ROLE VARCHAR(32) NOT NULL,
    ROW_START VARCHAR(64),
    ROW_STOP VARCHAR(64),
    ROW_VALUE VARCHAR(16777216),
    NARRATIVE_CODE VARCHAR(64),
    NARRATIVE_SYSTEM_URI VARCHAR(256),
    CODE_SYSTEM_NAME VARCHAR(64),
    STRUCTURED_CODE VARCHAR(64),
    STRUCTURED_CODE_SYSTEM VARCHAR(128),
    REJECTED_CODES VARCHAR(1024),
    QUOTE_SAFE VARCHAR(1) NOT NULL,
    CSV_TABLE VARCHAR(64),
    CSV_MATCH VARCHAR(1),
    CSV_ENCOUNTER VARCHAR(36),
    CSV_START VARCHAR(64),
    ORDINAL NUMBER(38,0) NOT NULL,
    SOURCE_FILENAME VARCHAR(1024) NOT NULL,
    SOURCE_FILE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL,
    LOAD_BATCH_ID VARCHAR(64) NOT NULL
)
COMMENT = 'Parsed C-CDA cells. document_id equals patient_id on this paired export. Element ids restart across files, so the key is (DOCUMENT_ID, ELEMENT_ID). CODE is the narrative code; REJECTED_CODES records non-quotable wrapper/assertion codes. Expected rows: 96806. Source file patient-360/generated/document_section.csv.';

ALTER TABLE PATIENT_360.RAW.DOCUMENT_SECTION
    ADD CONSTRAINT UQ_DOCUMENT_SECTION_ELEMENT UNIQUE (DOCUMENT_ID, ELEMENT_ID) NOT ENFORCED;

