-- PII-safe CORE views and patient-centric aggregates.
-- Run after 20_load.sql. Re-runnable. COPY GRANTS keeps analyst SELECT after 90_roles_grants.sql has run once.
-- SSN, DRIVERS, and PASSPORT are not projected. City, state, and the patient UUID remain.
-- Street address remains because the plan drops only those three identifiers.
-- Index date 2023-01-01. Horizon end 2024-01-01. Parsed clinical-document text is not in the risk views.
-- The point count is frozen. It is not a probability and not a care recommendation.

USE DATABASE PATIENT_360;
USE SCHEMA CORE;
USE WAREHOUSE PATIENT_360_WH;

CREATE OR REPLACE VIEW PATIENT_360.CORE.PATIENT
COPY GRANTS
COMMENT = 'Minimum simulated member profile for the analyst app. Direct identifiers, precise address/geolocation, and financial fields are omitted. Not for care.'
AS
SELECT
    ID AS PATIENT_ID,
    BIRTHDATE,
    DEATHDATE,
    FIRST AS FIRST_NAME,
    LAST AS LAST_NAME,
    GENDER,
    CITY,
    STATE,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.PATIENTS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.ENCOUNTER
COPY GRANTS
COMMENT = 'Encounter. PATIENT, ORGANIZATION, PROVIDER, and PAYER match parent ids on this extract.'
AS
SELECT
    ID AS ENCOUNTER_ID,
    "START" AS START_TS,
    "STOP" AS STOP_TS,
    PATIENT AS PATIENT_ID,
    ORGANIZATION AS ORGANIZATION_ID,
    PROVIDER AS PROVIDER_ID,
    PAYER AS PAYER_ID,
    ENCOUNTERCLASS AS ENCOUNTER_CLASS,
    CODE,
    DESCRIPTION,
    BASE_ENCOUNTER_COST,
    TOTAL_CLAIM_COST,
    PAYER_COVERAGE,
    REASONCODE AS REASON_CODE,
    REASONDESCRIPTION AS REASON_DESCRIPTION,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.ENCOUNTERS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.CONDITION
COPY GRANTS
COMMENT = 'Condition. No surrogate id. PATIENT, ENCOUNTER, CODE, and START are unique on this extract. CODE_SYSTEM is SNOMED CT.'
AS
SELECT
    "START" AS START_DATE,
    "STOP" AS STOP_DATE,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    SYSTEM AS CODE_SYSTEM,
    CODE,
    DESCRIPTION,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.CONDITIONS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.MEDICATION
COPY GRANTS
COMMENT = 'Medication. CODE is RxNorm. PATIENT, ENCOUNTER, CODE, and START are not unique: 9 pairs differ by STOP and DISPENSES. Not a dose order.'
AS
SELECT
    "START" AS START_TS,
    "STOP" AS STOP_TS,
    PATIENT AS PATIENT_ID,
    PAYER AS PAYER_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    BASE_COST,
    PAYER_COVERAGE,
    DISPENSES,
    TOTALCOST AS TOTAL_COST,
    REASONCODE AS REASON_CODE,
    REASONDESCRIPTION AS REASON_DESCRIPTION,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.MEDICATIONS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.OBSERVATION
COPY GRANTS
COMMENT = 'Observation. CODE is text. VALUE_TEXT keeps the source value. 3060 rows have no encounter and no category, and those are the same rows.'
AS
SELECT
    DATE AS OBSERVATION_TS,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    CATEGORY,
    CODE,
    DESCRIPTION,
    VALUE AS VALUE_TEXT,
    TRY_TO_NUMBER(VALUE) AS VALUE_NUMERIC,
    UNITS,
    TYPE AS VALUE_TYPE,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.OBSERVATIONS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.PROCEDURE
COPY GRANTS
COMMENT = 'Procedure. No surrogate id. PATIENT, ENCOUNTER, CODE, and START are unique on this extract.'
AS
SELECT
    "START" AS START_TS,
    "STOP" AS STOP_TS,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    SYSTEM AS CODE_SYSTEM,
    CODE,
    DESCRIPTION,
    BASE_COST,
    REASONCODE AS REASON_CODE,
    REASONDESCRIPTION AS REASON_DESCRIPTION,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.PROCEDURES;

CREATE OR REPLACE VIEW PATIENT_360.CORE.ALLERGY
COPY GRANTS
COMMENT = 'Allergy. Quote this CODE. It is the CSV match. A C-CDA assertion value in the same entry is a different concept.'
AS
SELECT
    "START" AS START_DATE,
    "STOP" AS STOP_DATE,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    CODE,
    SYSTEM AS CODE_SYSTEM,
    DESCRIPTION,
    TYPE AS ALLERGY_TYPE,
    CATEGORY,
    REACTION1 AS REACTION_1_CODE,
    DESCRIPTION1 AS REACTION_1_DESCRIPTION,
    SEVERITY1 AS REACTION_1_SEVERITY,
    REACTION2 AS REACTION_2_CODE,
    DESCRIPTION2 AS REACTION_2_DESCRIPTION,
    SEVERITY2 AS REACTION_2_SEVERITY,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.ALLERGIES;

CREATE OR REPLACE VIEW PATIENT_360.CORE.CAREPLAN
COPY GRANTS
COMMENT = 'Care plan. Id is unique.'
AS
SELECT
    ID AS CAREPLAN_ID,
    "START" AS START_DATE,
    "STOP" AS STOP_DATE,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    REASONCODE AS REASON_CODE,
    REASONDESCRIPTION AS REASON_DESCRIPTION,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.CAREPLANS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.IMMUNIZATION
COPY GRANTS
COMMENT = 'Immunization. No surrogate id. PATIENT, ENCOUNTER, CODE, and the event time are unique on this extract.'
AS
SELECT
    DATE AS IMMUNIZATION_TS,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    BASE_COST,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.IMMUNIZATIONS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.IMAGING_STUDY
COPY GRANTS
COMMENT = 'Imaging metadata. No pixels. Id is unique.'
AS
SELECT
    ID AS IMAGING_STUDY_ID,
    DATE AS IMAGING_TS,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    SERIES_UID,
    BODYSITE_CODE AS BODY_SITE_CODE,
    BODYSITE_DESCRIPTION AS BODY_SITE_DESCRIPTION,
    MODALITY_CODE,
    MODALITY_DESCRIPTION,
    INSTANCE_UID,
    SOP_CODE,
    SOP_DESCRIPTION,
    PROCEDURE_CODE,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.IMAGING_STUDIES;

CREATE OR REPLACE VIEW PATIENT_360.CORE.DEVICE
COPY GRANTS
COMMENT = 'Device. No surrogate id.'
AS
SELECT
    "START" AS START_TS,
    "STOP" AS STOP_TS,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    UDI,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.DEVICES;

CREATE OR REPLACE VIEW PATIENT_360.CORE.SUPPLY
COPY GRANTS
COMMENT = 'Supply. PATIENT, ENCOUNTER, CODE, and SUPPLY_DATE are not unique: 11 pairs on this extract.'
AS
SELECT
    DATE AS SUPPLY_DATE,
    PATIENT AS PATIENT_ID,
    ENCOUNTER AS ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    QUANTITY,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.SUPPLIES;

CREATE OR REPLACE VIEW PATIENT_360.CORE.PAYER_TRANSITION
COPY GRANTS
COMMENT = 'Coverage span. MEMBER_ID is a span id, empty on 1082 rows, and is not the patient key.'
AS
SELECT
    PATIENT AS PATIENT_ID,
    MEMBERID AS MEMBER_ID,
    START_DATE AS START_TS,
    END_DATE AS END_TS,
    PAYER AS PAYER_ID,
    SECONDARY_PAYER AS SECONDARY_PAYER_ID,
    PLAN_OWNERSHIP,
    OWNER_NAME,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.PAYER_TRANSITIONS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.PAYER
COPY GRANTS
COMMENT = 'Payer. Address fields are empty on this extract. Claims reference this id, not a member id.'
AS
SELECT
    ID AS PAYER_ID,
    NAME AS PAYER_NAME,
    OWNERSHIP,
    ADDRESS,
    CITY,
    STATE_HEADQUARTERED,
    ZIP,
    PHONE,
    AMOUNT_COVERED,
    AMOUNT_UNCOVERED,
    REVENUE,
    COVERED_ENCOUNTERS,
    UNCOVERED_ENCOUNTERS,
    COVERED_MEDICATIONS,
    UNCOVERED_MEDICATIONS,
    COVERED_PROCEDURES,
    UNCOVERED_PROCEDURES,
    COVERED_IMMUNIZATIONS,
    UNCOVERED_IMMUNIZATIONS,
    UNIQUE_CUSTOMERS,
    QOLS_AVG,
    MEMBER_MONTHS,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.PAYERS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.ORGANIZATION
COPY GRANTS
COMMENT = 'Organization. ZIP and NPI stay text.'
AS
SELECT
    ID AS ORGANIZATION_ID,
    NAME AS ORGANIZATION_NAME,
    ADDRESS,
    CITY,
    STATE,
    ZIP,
    LAT AS LATITUDE,
    LON AS LONGITUDE,
    PHONE,
    REVENUE,
    UTILIZATION,
    NPI,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.ORGANIZATIONS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.PROVIDER
COPY GRANTS
COMMENT = 'Provider. SPECIALITY keeps the source spelling. RECORDED_ENCOUNTER_COUNT is a column on the provider file, not a child row count.'
AS
SELECT
    ID AS PROVIDER_ID,
    ORGANIZATION AS ORGANIZATION_ID,
    NAME AS PROVIDER_NAME,
    GENDER,
    SPECIALITY,
    ADDRESS,
    CITY,
    STATE,
    ZIP,
    LAT AS LATITUDE,
    LON AS LONGITUDE,
    ENCOUNTERS AS RECORDED_ENCOUNTER_COUNT,
    PROCEDURES AS RECORDED_PROCEDURE_COUNT,
    NPI,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.PROVIDERS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.CLAIM
COPY GRANTS
COMMENT = 'Claim. APPOINTMENT_ID is the encounter id. PRIMARY_PAYER_ID is payers.Id when filled, not a member id. REFERRING_PROVIDER_ID is empty on this extract. DEPARTMENT_ID is not an organization id.'
AS
SELECT
    ID AS CLAIM_ID,
    PATIENTID AS PATIENT_ID,
    PROVIDERID AS PROVIDER_ID,
    PRIMARYPATIENTINSURANCEID AS PRIMARY_PAYER_ID,
    SECONDARYPATIENTINSURANCEID AS SECONDARY_PAYER_ID,
    DEPARTMENTID AS DEPARTMENT_ID,
    PATIENTDEPARTMENTID AS PATIENT_DEPARTMENT_ID,
    DIAGNOSIS1 AS DIAGNOSIS_1,
    DIAGNOSIS2 AS DIAGNOSIS_2,
    DIAGNOSIS3 AS DIAGNOSIS_3,
    DIAGNOSIS4 AS DIAGNOSIS_4,
    DIAGNOSIS5 AS DIAGNOSIS_5,
    DIAGNOSIS6 AS DIAGNOSIS_6,
    DIAGNOSIS7 AS DIAGNOSIS_7,
    DIAGNOSIS8 AS DIAGNOSIS_8,
    REFERRINGPROVIDERID AS REFERRING_PROVIDER_ID,
    APPOINTMENTID AS APPOINTMENT_ID,
    CURRENTILLNESSDATE AS CURRENT_ILLNESS_TS,
    SERVICEDATE AS SERVICE_TS,
    SUPERVISINGPROVIDERID AS SUPERVISING_PROVIDER_ID,
    STATUS1 AS STATUS_1,
    STATUS2 AS STATUS_2,
    STATUSP AS STATUS_PATIENT,
    OUTSTANDING1 AS OUTSTANDING_1,
    OUTSTANDING2 AS OUTSTANDING_2,
    OUTSTANDINGP AS OUTSTANDING_PATIENT,
    LASTBILLEDDATE1 AS LAST_BILLED_TS_1,
    LASTBILLEDDATE2 AS LAST_BILLED_TS_2,
    LASTBILLEDDATEP AS LAST_BILLED_TS_PATIENT,
    HEALTHCARECLAIMTYPEID1 AS CLAIM_TYPE_ID_1,
    HEALTHCARECLAIMTYPEID2 AS CLAIM_TYPE_ID_2,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.CLAIMS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.CLAIM_LINE
COPY GRANTS
COMMENT = 'Claim line. NOTES is the charge description, not a clinical document. LINE_NOTE is empty on this extract. AMOUNT is not a patient balance. PATIENT_INSURANCE_ID is not patients.Id.'
AS
SELECT
    ID AS CLAIM_LINE_ID,
    CLAIMID AS CLAIM_ID,
    CHARGEID AS CHARGE_ID,
    PATIENTID AS PATIENT_ID,
    TYPE AS LINE_TYPE,
    AMOUNT,
    METHOD AS PAYMENT_METHOD,
    FROMDATE AS FROM_TS,
    TODATE AS TO_TS,
    PLACEOFSERVICE AS PLACE_OF_SERVICE_ID,
    PROCEDURECODE AS PROCEDURE_CODE,
    MODIFIER1 AS MODIFIER_1,
    MODIFIER2 AS MODIFIER_2,
    DIAGNOSISREF1 AS DIAGNOSIS_REF_1,
    DIAGNOSISREF2 AS DIAGNOSIS_REF_2,
    DIAGNOSISREF3 AS DIAGNOSIS_REF_3,
    DIAGNOSISREF4 AS DIAGNOSIS_REF_4,
    UNITS,
    DEPARTMENTID AS DEPARTMENT_ID,
    NOTES,
    UNITAMOUNT AS UNIT_AMOUNT,
    TRANSFEROUTID AS TRANSFER_OUT_ID,
    TRANSFERTYPE AS TRANSFER_TYPE,
    PAYMENTS,
    ADJUSTMENTS,
    TRANSFERS,
    OUTSTANDING,
    APPOINTMENTID AS APPOINTMENT_ID,
    LINENOTE AS LINE_NOTE,
    PATIENTINSURANCEID AS PATIENT_INSURANCE_ID,
    FEESCHEDULEID AS FEE_SCHEDULE_ID,
    PROVIDERID AS PROVIDER_ID,
    SUPERVISINGPROVIDERID AS SUPERVISING_PROVIDER_ID,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.CLAIMS_TRANSACTIONS;

CREATE OR REPLACE VIEW PATIENT_360.CORE.DOCUMENT_SECTION
COPY GRANTS
COMMENT = 'Parsed C-CDA cell. DOCUMENT_ID equals PATIENT_ID on this export. Cite DOCUMENT_ID with ELEMENT_ID. Element ids restart across documents.'
AS
SELECT
    DOCUMENT_ID,
    PATIENT_ID,
    EFFECTIVE_TIME,
    SECTION_LOINC,
    SECTION_TITLE,
    ELEMENT_ID,
    TEXT,
    CODE,
    CODE_SYSTEM,
    CCDA_SOURCE_FILE,
    ELEMENT_ROLE,
    ROW_START,
    ROW_STOP,
    ROW_VALUE,
    NARRATIVE_CODE,
    NARRATIVE_SYSTEM_URI,
    CODE_SYSTEM_NAME,
    STRUCTURED_CODE,
    STRUCTURED_CODE_SYSTEM,
    REJECTED_CODES,
    QUOTE_SAFE,
    CSV_TABLE,
    CSV_MATCH,
    CSV_ENCOUNTER,
    CSV_START,
    ORDINAL,
    SOURCE_FILENAME,
    SOURCE_FILE_ROW_NUMBER,
    LOADED_AT,
    LOAD_BATCH_ID
FROM PATIENT_360.RAW.DOCUMENT_SECTION;

CREATE OR REPLACE VIEW PATIENT_360.CORE.MEMBER_SUMMARY
COPY GRANTS
COMMENT = 'One row per simulated patient. Counts are chart, claim, coverage, and document facts. Not a risk score.'
AS
SELECT
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.BIRTHDATE,
    p.DEATHDATE,
    p.GENDER,
    p.CITY,
    p.STATE,
    COALESCE(e.ENCOUNTER_COUNT, 0) AS ENCOUNTER_COUNT,
    e.LAST_ENCOUNTER_TS,
    COALESCE(c.CLAIM_COUNT, 0) AS CLAIM_COUNT,
    COALESCE(m.MEDICATION_COUNT, 0) AS MEDICATION_COUNT,
    COALESCE(k.CONDITION_COUNT, 0) AS CONDITION_COUNT,
    COALESCE(o.OBSERVATION_COUNT, 0) AS OBSERVATION_COUNT,
    COALESCE(a.ALLERGY_COUNT, 0) AS ALLERGY_COUNT,
    COALESCE(s.COVERAGE_SPAN_COUNT, 0) AS COVERAGE_SPAN_COUNT,
    COALESCE(s.COVERAGE_SPAN_WITH_MEMBER_ID_COUNT, 0) AS COVERAGE_SPAN_WITH_MEMBER_ID_COUNT,
    COALESCE(d.DOCUMENT_COUNT, 0) AS DOCUMENT_COUNT
FROM PATIENT_360.CORE.PATIENT AS p
LEFT JOIN (
    SELECT
        PATIENT_ID,
        COUNT(*) AS ENCOUNTER_COUNT,
        MAX(START_TS) AS LAST_ENCOUNTER_TS
    FROM PATIENT_360.CORE.ENCOUNTER
    GROUP BY PATIENT_ID
) AS e
    ON e.PATIENT_ID = p.PATIENT_ID
LEFT JOIN (
    SELECT PATIENT_ID, COUNT(*) AS CLAIM_COUNT
    FROM PATIENT_360.CORE.CLAIM
    GROUP BY PATIENT_ID
) AS c
    ON c.PATIENT_ID = p.PATIENT_ID
LEFT JOIN (
    SELECT PATIENT_ID, COUNT(*) AS MEDICATION_COUNT
    FROM PATIENT_360.CORE.MEDICATION
    GROUP BY PATIENT_ID
) AS m
    ON m.PATIENT_ID = p.PATIENT_ID
LEFT JOIN (
    SELECT PATIENT_ID, COUNT(*) AS CONDITION_COUNT
    FROM PATIENT_360.CORE.CONDITION
    GROUP BY PATIENT_ID
) AS k
    ON k.PATIENT_ID = p.PATIENT_ID
LEFT JOIN (
    SELECT PATIENT_ID, COUNT(*) AS OBSERVATION_COUNT
    FROM PATIENT_360.CORE.OBSERVATION
    GROUP BY PATIENT_ID
) AS o
    ON o.PATIENT_ID = p.PATIENT_ID
LEFT JOIN (
    SELECT PATIENT_ID, COUNT(*) AS ALLERGY_COUNT
    FROM PATIENT_360.CORE.ALLERGY
    GROUP BY PATIENT_ID
) AS a
    ON a.PATIENT_ID = p.PATIENT_ID
LEFT JOIN (
    SELECT
        PATIENT_ID,
        COUNT(*) AS COVERAGE_SPAN_COUNT,
        COUNT(MEMBER_ID) AS COVERAGE_SPAN_WITH_MEMBER_ID_COUNT
    FROM PATIENT_360.CORE.PAYER_TRANSITION
    GROUP BY PATIENT_ID
) AS s
    ON s.PATIENT_ID = p.PATIENT_ID
LEFT JOIN (
    SELECT PATIENT_ID, COUNT(DISTINCT DOCUMENT_ID) AS DOCUMENT_COUNT
    FROM PATIENT_360.CORE.DOCUMENT_SECTION
    GROUP BY PATIENT_ID
) AS d
    ON d.PATIENT_ID = p.PATIENT_ID;

CREATE OR REPLACE VIEW PATIENT_360.CORE.MEMBER_COVERAGE
COPY GRANTS
COMMENT = 'Coverage span with payer name. MEMBER_ID is not the patient key.'
AS
SELECT
    t.PATIENT_ID,
    t.MEMBER_ID,
    t.START_TS,
    t.END_TS,
    t.PAYER_ID,
    p.PAYER_NAME,
    t.SECONDARY_PAYER_ID,
    t.PLAN_OWNERSHIP,
    t.OWNER_NAME
FROM PATIENT_360.CORE.PAYER_TRANSITION AS t
INNER JOIN PATIENT_360.CORE.PAYER AS p
    ON p.PAYER_ID = t.PAYER_ID;

CREATE OR REPLACE VIEW PATIENT_360.CORE.MEMBER_ENCOUNTER_CLAIM
COPY GRANTS
COMMENT = 'Claim joined to the encounter whose id is the claim appointment id. Same patient on both sides.'
AS
SELECT
    e.PATIENT_ID,
    e.ENCOUNTER_ID,
    e.ENCOUNTER_CLASS,
    e.START_TS AS ENCOUNTER_START_TS,
    c.CLAIM_ID,
    c.APPOINTMENT_ID,
    c.DIAGNOSIS_1,
    c.PRIMARY_PAYER_ID
FROM PATIENT_360.CORE.ENCOUNTER AS e
INNER JOIN PATIENT_360.CORE.CLAIM AS c
    ON c.APPOINTMENT_ID = e.ENCOUNTER_ID
    AND c.PATIENT_ID = e.PATIENT_ID;

CREATE OR REPLACE VIEW PATIENT_360.CORE.RISK_FEATURE
COPY GRANTS
COMMENT = 'CSV facts whose START or DATE is before 2023-01-01. Parsed clinical-document text is excluded. Horizon facts are excluded. Not a probability.'
AS
SELECT
    'ENCOUNTER' AS SOURCE_TABLE,
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    START_TS AS EVENT_TS,
    ENCOUNTER_CLASS AS EVENT_CLASS,
    CAST(NULL AS BOOLEAN) AS ACTIVE_AT_INDEX,
    CAST(NULL AS VARCHAR) AS VALUE_TEXT,
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.ENCOUNTER
WHERE START_TS < TIMESTAMP '2023-01-01 00:00:00'
UNION ALL
SELECT
    'CONDITION',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    TO_TIMESTAMP_NTZ(START_DATE),
    CAST(NULL AS VARCHAR),
    (STOP_DATE IS NULL OR STOP_DATE >= DATE '2023-01-01'),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.CONDITION
WHERE START_DATE < DATE '2023-01-01'
UNION ALL
SELECT
    'MEDICATION',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    START_TS,
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.MEDICATION
WHERE START_TS < TIMESTAMP '2023-01-01 00:00:00'
UNION ALL
SELECT
    'OBSERVATION',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    OBSERVATION_TS,
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    VALUE_TEXT,
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.OBSERVATION
WHERE OBSERVATION_TS < TIMESTAMP '2023-01-01 00:00:00'
UNION ALL
SELECT
    'PROCEDURE',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    START_TS,
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.PROCEDURE
WHERE START_TS < TIMESTAMP '2023-01-01 00:00:00'
UNION ALL
SELECT
    'ALLERGY',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    TO_TIMESTAMP_NTZ(START_DATE),
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.ALLERGY
WHERE START_DATE < DATE '2023-01-01'
UNION ALL
SELECT
    'CAREPLAN',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    TO_TIMESTAMP_NTZ(START_DATE),
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.CAREPLAN
WHERE START_DATE < DATE '2023-01-01'
UNION ALL
SELECT
    'IMMUNIZATION',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    IMMUNIZATION_TS,
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.IMMUNIZATION
WHERE IMMUNIZATION_TS < TIMESTAMP '2023-01-01 00:00:00'
UNION ALL
SELECT
    'DEVICE',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    START_TS,
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.DEVICE
WHERE START_TS < TIMESTAMP '2023-01-01 00:00:00'
UNION ALL
SELECT
    'IMAGING_STUDY',
    PATIENT_ID,
    ENCOUNTER_ID,
    PROCEDURE_CODE,
    MODALITY_DESCRIPTION,
    IMAGING_TS,
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.IMAGING_STUDY
WHERE IMAGING_TS < TIMESTAMP '2023-01-01 00:00:00'
UNION ALL
SELECT
    'SUPPLY',
    PATIENT_ID,
    ENCOUNTER_ID,
    CODE,
    DESCRIPTION,
    TO_TIMESTAMP_NTZ(SUPPLY_DATE),
    CAST(NULL AS VARCHAR),
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS VARCHAR),
    SOURCE_FILE_ROW_NUMBER
FROM PATIENT_360.CORE.SUPPLY
WHERE SUPPLY_DATE < DATE '2023-01-01';

CREATE OR REPLACE VIEW PATIENT_360.CORE.RISK_COHORT
COPY GRANTS
COMMENT = 'Frozen point count for patients born before 2023-01-01, alive at that date, with an encounter before that date. Points: age >= 65; prior emergency or inpatient encounter; at least 8 conditions still active; last prior Hemoglobin A1c code 4548-4 >= 6.5. EVENT_FLAG is an emergency or inpatient encounter in 2023. Point count, not a probability and not a care recommendation. Points are not retuned.'
AS
WITH eligible AS (
    SELECT
        p.PATIENT_ID,
        p.BIRTHDATE,
        DATEDIFF('year', p.BIRTHDATE, DATE '2023-01-01')
            - IFF(
                DATEADD(
                    'year',
                    DATEDIFF('year', p.BIRTHDATE, DATE '2023-01-01'),
                    p.BIRTHDATE
                ) > DATE '2023-01-01',
                1,
                0
            ) AS AGE_YEARS_AT_INDEX
    FROM PATIENT_360.CORE.PATIENT AS p
    WHERE p.BIRTHDATE < DATE '2023-01-01'
        AND (p.DEATHDATE IS NULL OR p.DEATHDATE > DATE '2023-01-01')
        AND EXISTS (
            SELECT 1
            FROM PATIENT_360.CORE.RISK_FEATURE AS f
            WHERE f.SOURCE_TABLE = 'ENCOUNTER'
                AND f.PATIENT_ID = p.PATIENT_ID
        )
),
prior_acute AS (
    SELECT DISTINCT PATIENT_ID
    FROM PATIENT_360.CORE.RISK_FEATURE
    WHERE SOURCE_TABLE = 'ENCOUNTER'
        AND EVENT_CLASS IN ('emergency', 'inpatient')
),
active_conditions AS (
    SELECT
        PATIENT_ID,
        COUNT(*) AS ACTIVE_CONDITION_COUNT
    FROM PATIENT_360.CORE.RISK_FEATURE
    WHERE SOURCE_TABLE = 'CONDITION'
        AND ACTIVE_AT_INDEX = TRUE
    GROUP BY PATIENT_ID
),
last_a1c AS (
    SELECT
        PATIENT_ID,
        TRY_TO_NUMBER(VALUE_TEXT, 18, 4) AS LAST_A1C_VALUE
    FROM PATIENT_360.CORE.RISK_FEATURE
    WHERE SOURCE_TABLE = 'OBSERVATION'
        AND CODE = '4548-4'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY PATIENT_ID
        ORDER BY EVENT_TS DESC, SOURCE_FILE_ROW_NUMBER DESC
    ) = 1
),
scored AS (
    SELECT
        e.PATIENT_ID,
        e.BIRTHDATE,
        e.AGE_YEARS_AT_INDEX,
        IFF(e.AGE_YEARS_AT_INDEX >= 65, 1, 0) AS POINT_AGE_GE_65,
        IFF(a.PATIENT_ID IS NOT NULL, 1, 0) AS POINT_PRIOR_ACUTE_ENCOUNTER,
        COALESCE(c.ACTIVE_CONDITION_COUNT, 0) AS ACTIVE_CONDITION_COUNT,
        IFF(COALESCE(c.ACTIVE_CONDITION_COUNT, 0) >= 8, 1, 0) AS POINT_ACTIVE_CONDITIONS_GE_8,
        h.LAST_A1C_VALUE,
        IFF(COALESCE(h.LAST_A1C_VALUE >= 6.5, FALSE), 1, 0) AS POINT_LAST_A1C_GE_6_5,
        IFF(
            EXISTS (
                SELECT 1
                FROM PATIENT_360.CORE.ENCOUNTER AS enc
                WHERE enc.PATIENT_ID = e.PATIENT_ID
                    AND enc.ENCOUNTER_CLASS IN ('emergency', 'inpatient')
                    AND enc.START_TS >= TIMESTAMP '2023-01-01 00:00:00'
                    AND enc.START_TS < TIMESTAMP '2024-01-01 00:00:00'
            ),
            1,
            0
        ) AS EVENT_FLAG
    FROM eligible AS e
    LEFT JOIN prior_acute AS a
        ON a.PATIENT_ID = e.PATIENT_ID
    LEFT JOIN active_conditions AS c
        ON c.PATIENT_ID = e.PATIENT_ID
    LEFT JOIN last_a1c AS h
        ON h.PATIENT_ID = e.PATIENT_ID
)
SELECT
    PATIENT_ID,
    BIRTHDATE,
    AGE_YEARS_AT_INDEX,
    POINT_AGE_GE_65,
    POINT_PRIOR_ACUTE_ENCOUNTER,
    ACTIVE_CONDITION_COUNT,
    POINT_ACTIVE_CONDITIONS_GE_8,
    LAST_A1C_VALUE,
    POINT_LAST_A1C_GE_6_5,
    POINT_AGE_GE_65
        + POINT_PRIOR_ACUTE_ENCOUNTER
        + POINT_ACTIVE_CONDITIONS_GE_8
        + POINT_LAST_A1C_GE_6_5 AS POINT_TOTAL,
    EVENT_FLAG,
    DATE '2023-01-01' AS INDEX_DATE,
    DATE '2024-01-01' AS HORIZON_END
FROM scored;

CREATE OR REPLACE VIEW PATIENT_360.CORE.RISK_SCORE
COPY GRANTS
COMMENT = 'Bucket table for the frozen point count. Cohort 97 and 14 horizon events are measured, not targets to fit. Score 2 sits below score 1. Point count, not a validated stratifier and not a care recommendation. Condition counts include findings, disorders, and situations.'
AS
WITH scores AS (
    SELECT 0 AS SCORE_VALUE
    UNION ALL SELECT 1
    UNION ALL SELECT 2
    UNION ALL SELECT 3
    UNION ALL SELECT 4
),
totals AS (
    SELECT
        COUNT(*) AS COHORT_PATIENT_COUNT,
        COALESCE(SUM(EVENT_FLAG), 0) AS COHORT_EVENT_COUNT
    FROM PATIENT_360.CORE.RISK_COHORT
),
exclusions AS (
    SELECT
        (
            SELECT COUNT(*)
            FROM PATIENT_360.CORE.PATIENT
            WHERE BIRTHDATE >= DATE '2023-01-01'
        ) AS EXCLUDED_BORN_ON_OR_AFTER_INDEX,
        (
            SELECT COUNT(*)
            FROM PATIENT_360.CORE.PATIENT
            WHERE BIRTHDATE < DATE '2023-01-01'
                AND DEATHDATE IS NOT NULL
                AND DEATHDATE <= DATE '2023-01-01'
        ) AS EXCLUDED_DEAD_ON_OR_BEFORE_INDEX,
        (
            SELECT COUNT(*)
            FROM PATIENT_360.CORE.PATIENT AS p
            WHERE p.BIRTHDATE < DATE '2023-01-01'
                AND (p.DEATHDATE IS NULL OR p.DEATHDATE > DATE '2023-01-01')
                AND NOT EXISTS (
                    SELECT 1
                    FROM PATIENT_360.CORE.ENCOUNTER AS e
                    WHERE e.PATIENT_ID = p.PATIENT_ID
                        AND e.START_TS < TIMESTAMP '2023-01-01 00:00:00'
                )
        ) AS EXCLUDED_NO_PRIOR_ENCOUNTER
),
buckets AS (
    SELECT
        TO_VARCHAR(s.SCORE_VALUE) AS SCORE_BUCKET,
        s.SCORE_VALUE AS SORT_ORDER,
        COUNT(c.PATIENT_ID) AS PATIENT_COUNT,
        COALESCE(SUM(c.EVENT_FLAG), 0) AS EVENT_COUNT
    FROM scores AS s
    LEFT JOIN PATIENT_360.CORE.RISK_COHORT AS c
        ON c.POINT_TOTAL = s.SCORE_VALUE
    GROUP BY s.SCORE_VALUE
),
ge2 AS (
    SELECT
        'GE_2' AS SCORE_BUCKET,
        5 AS SORT_ORDER,
        COUNT(*) AS PATIENT_COUNT,
        COALESCE(SUM(EVENT_FLAG), 0) AS EVENT_COUNT
    FROM PATIENT_360.CORE.RISK_COHORT
    WHERE POINT_TOTAL >= 2
)
SELECT
    b.SCORE_BUCKET,
    b.SORT_ORDER,
    b.PATIENT_COUNT,
    b.EVENT_COUNT,
    ROUND(100.0 * b.EVENT_COUNT / NULLIF(b.PATIENT_COUNT, 0), 2) AS EVENT_RATE_PCT,
    t.COHORT_PATIENT_COUNT,
    t.COHORT_EVENT_COUNT,
    ROUND(100.0 * t.COHORT_EVENT_COUNT / NULLIF(t.COHORT_PATIENT_COUNT, 0), 2) AS BASE_RATE_PCT,
    x.EXCLUDED_BORN_ON_OR_AFTER_INDEX,
    x.EXCLUDED_DEAD_ON_OR_BEFORE_INDEX,
    x.EXCLUDED_NO_PRIOR_ENCOUNTER,
    'Point count, not a validated stratifier and not a care recommendation. Score 2 sits below score 1 on this extract.' AS SCORE_STATEMENT
FROM (
    SELECT * FROM buckets
    UNION ALL
    SELECT * FROM ge2
) AS b
CROSS JOIN totals AS t
CROSS JOIN exclusions AS x;
