-- Roles and grants for Patient 360.
-- Run after 40_semantic_view.sql, as the owner of PATIENT_360 (the role that ran 00 through 40).
-- Idempotent. GRANT and REVOKE of an existing or absent privilege can be re-run.
-- No user is named here and no secret is stored.
--
-- PATIENT_360_ANALYST reads CORE views and the semantic view.
-- It cannot enter RAW. CORE.PATIENT is also minimized: direct identifiers, street/ZIP,
-- geolocation, and income/expense fields are not projected into the analyst profile.
-- PATIENT_360_LOADER can reload RAW. It is not the demo role.
-- PATIENT_360_ADMIN inherits both roles. SYSADMIN inherits admin. ACCOUNTADMIN is not modified.

USE DATABASE PATIENT_360;
USE WAREHOUSE PATIENT_360_WH;

CREATE ROLE IF NOT EXISTS PATIENT_360_ADMIN
    COMMENT = 'Owns the Patient 360 operating grants. Not a substitute for ACCOUNTADMIN.';

CREATE ROLE IF NOT EXISTS PATIENT_360_LOADER
    COMMENT = 'Reloads RAW from the internal stage. Can read RAW, including the three restricted identifiers.';

CREATE ROLE IF NOT EXISTS PATIENT_360_ANALYST
    COMMENT = 'Demo reader. CORE-only; no RAW identifiers, precise address/geolocation, or patient financial profile.';

GRANT ROLE PATIENT_360_ANALYST TO ROLE PATIENT_360_ADMIN;
GRANT ROLE PATIENT_360_LOADER TO ROLE PATIENT_360_ADMIN;
GRANT ROLE PATIENT_360_ADMIN TO ROLE SYSADMIN;

GRANT USAGE, OPERATE ON WAREHOUSE PATIENT_360_WH TO ROLE PATIENT_360_ADMIN;
GRANT USAGE ON WAREHOUSE PATIENT_360_WH TO ROLE PATIENT_360_LOADER;
GRANT USAGE ON WAREHOUSE PATIENT_360_WH TO ROLE PATIENT_360_ANALYST;

GRANT USAGE ON DATABASE PATIENT_360 TO ROLE PATIENT_360_ADMIN;
GRANT USAGE ON DATABASE PATIENT_360 TO ROLE PATIENT_360_LOADER;
GRANT USAGE ON DATABASE PATIENT_360 TO ROLE PATIENT_360_ANALYST;

GRANT USAGE ON SCHEMA PATIENT_360.RAW TO ROLE PATIENT_360_ADMIN;
GRANT USAGE ON SCHEMA PATIENT_360.RAW TO ROLE PATIENT_360_LOADER;
GRANT USAGE ON SCHEMA PATIENT_360.CORE TO ROLE PATIENT_360_ADMIN;
GRANT USAGE ON SCHEMA PATIENT_360.CORE TO ROLE PATIENT_360_ANALYST;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PATIENT_360.CORE TO ROLE PATIENT_360_ADMIN;
GRANT CREATE SEMANTIC VIEW ON SCHEMA PATIENT_360.CORE TO ROLE PATIENT_360_ADMIN;
GRANT CREATE TABLE ON SCHEMA PATIENT_360.RAW TO ROLE PATIENT_360_ADMIN;

-- Analyst must not enter RAW. Revoke first so a previous grant does not survive a re-run.
REVOKE USAGE ON SCHEMA PATIENT_360.RAW FROM ROLE PATIENT_360_ANALYST;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PATIENT_360.RAW FROM ROLE PATIENT_360_ANALYST;
REVOKE SELECT ON ALL VIEWS IN SCHEMA PATIENT_360.RAW FROM ROLE PATIENT_360_ANALYST;
REVOKE SELECT ON FUTURE TABLES IN SCHEMA PATIENT_360.RAW FROM ROLE PATIENT_360_ANALYST;
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA PATIENT_360.RAW FROM ROLE PATIENT_360_ANALYST;
REVOKE READ, WRITE ON STAGE PATIENT_360.RAW.STG_CSV FROM ROLE PATIENT_360_ANALYST;

GRANT SELECT ON ALL VIEWS IN SCHEMA PATIENT_360.CORE TO ROLE PATIENT_360_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PATIENT_360.CORE TO ROLE PATIENT_360_ANALYST;
GRANT SELECT ON SEMANTIC VIEW PATIENT_360.CORE.SEM_MEMBER TO ROLE PATIENT_360_ANALYST;

GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA PATIENT_360.RAW TO ROLE PATIENT_360_LOADER;
GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA PATIENT_360.RAW TO ROLE PATIENT_360_LOADER;
GRANT READ, WRITE ON STAGE PATIENT_360.RAW.STG_CSV TO ROLE PATIENT_360_LOADER;
GRANT USAGE ON FILE FORMAT PATIENT_360.RAW.FF_SYNTHEA_CSV TO ROLE PATIENT_360_LOADER;
GRANT USAGE ON FILE FORMAT PATIENT_360.RAW.FF_DOCUMENT_CSV TO ROLE PATIENT_360_LOADER;

GRANT SELECT ON ALL TABLES IN SCHEMA PATIENT_360.RAW TO ROLE PATIENT_360_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA PATIENT_360.CORE TO ROLE PATIENT_360_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PATIENT_360.CORE TO ROLE PATIENT_360_ADMIN;
GRANT SELECT ON SEMANTIC VIEW PATIENT_360.CORE.SEM_MEMBER TO ROLE PATIENT_360_ADMIN;
GRANT READ, WRITE ON STAGE PATIENT_360.RAW.STG_CSV TO ROLE PATIENT_360_ADMIN;
GRANT USAGE ON FILE FORMAT PATIENT_360.RAW.FF_SYNTHEA_CSV TO ROLE PATIENT_360_ADMIN;
GRANT USAGE ON FILE FORMAT PATIENT_360.RAW.FF_DOCUMENT_CSV TO ROLE PATIENT_360_ADMIN;
