-- Streamlit access for the analyst role.
-- Run after `snow streamlit deploy` (from patient-360/) has created CORE.PATIENT_360_APP.

GRANT USAGE ON STREAMLIT PATIENT_360.CORE.PATIENT_360_APP TO ROLE PATIENT_360_ANALYST;
GRANT USAGE ON STREAMLIT PATIENT_360.CORE.PATIENT_360_APP TO ROLE PATIENT_360_ADMIN;
